### ISSUE TITLE
Bug: Elsa 2.0 Activity StartAt triggers a new workflow, although it is not a start trigger

### ISSUE THREAD

**Issue by Rafael94** [elsa-workflows/elsa-core#507] opened 2020-12-11 15:10 UTC
I want to trigger a specific action when a ticket expires. For this I want to use StartAt and use the expiration date as the execution point.

I noticed that every time I start the program, the workflow is created. As I have seen, it is ignored that it is not a start trigger.

I use startAt in several places and so I defined it as follows.

```
var startAt = workflow.Add<StartAt>(startAt => startAt.Set(x => x.Instant, context => {
                var ticket = context.GetWorkflowContext<Ticket>();
                return Instant.FromDateTimeUtc(ticket.FollowupBy.Value.ToUniversalTime());
            }));

 workflow
                .WithContextType<Ticket>()
                .StartWith<EntityChangedTrigger>(.......
```

**Comment by sfmskywalker** [comment] 2020-12-11 15:19
Two things:

1. When you do `workflow.Add<>`, that activity automatically becomes a start activity because it has no incoming connections, unless of course you connect to it from another activity (which isn't clear from your snippet).
2. When the application starts, the `StartJobs` hosted service (in `Elsa.Activities.Timers.HostedServices`) will select all workflow classes that start with `StartAt` activities and then evaluate its `Instant` property expression. This operation should not cause any workflow instances to be created, but you would see your workflow class being instantiated.

**Comment by Rafael94** [comment] 2020-12-11 16:16
I use the activity in two places. 

```
var nvRemainer = workflow.Add<StartAt>(startAt => startAt.Set(x => x.Instant, context => {
                var ticket = context.GetWorkflowContext<IncidentBase>();
                if(ticket == null)
                {
                    return SystemClock.Instance.GetCurrentInstant();
                }
                return Instant.FromDateTimeUtc(ticket.FollowupBy.Value.ToUniversalTime()); 
            })).Then<TestActivity>(); // Later send emails
          
            workflow
                .WithContextType<IncidentBase>()
                .StartWith<EntityChangedTrigger>(setup => setup.Set(x => x.EntityName, typeof(Incident).FullName).Set(x => x.Action, new[] { EntityChangedTriggerAction.Added }))
                .Then(nvRemainer)
                .Then<Fork>(
                    activity => activity.Set(x => x.Branches, new HashSet<string>(new[] { "NV Anpassen", "Next" })),
                    fork =>
                    {
                        fork.When("NV Anpassen").Then(nvRemainer);
                        fork.When("Next")
                            .Then<Fork>(
                                 activity => activity.Set(x => x.Branches, new HashSet<string>(new[] { "NV Anpassen", "Resolved", "Cancled" })),
                                 fork =>
                                 {
                                     fork.When("NV Anpassen")
                                        .EntityChanged<Incident>(new[] { EntityChangedTriggerAction.Updated })
                                        .Then(nvRemainer);
                                     fork.When("Finish")
                                        .TicketStateChanged(new[] { Incident.States.Resolved })
                                        .Finish();
                                     fork.When("Cancled")
                                      .TicketStateChanged(new[] { Incident.States.Canceled })
                                      .Finish();
                                 });
                    });
```

**Comment by sfmskywalker** [comment] 2020-12-11 21:09
Indeed, in this case the StartAt activity should not trigger the workflow when the application starts. I'll try and see if I can reproduce this behavior.

**Comment by Rafael94** [comment] 2020-12-14 07:20
I've recreated it so you can look at it directly without having to recreate it.

https://github.com/Rafael94/elsa-core/tree/start-trigger-bug/src/samples/worker/Elsa.Samples.Timers

**Comment by sfmskywalker** [comment] 2020-12-14 20:14
Sweet, thank you :)

**Comment by sfmskywalker** [comment] 2020-12-14 20:50
I see now. The issue is this part:

```csharp
var nvRemainer = workflow
	.Add<StartAt>(...)
	.Then<TestActivity>();
```

The `nvRemainer ` variable is not what you think it is (`StartAt`). Instead, it is a `TestActivity`.
So when you do this:

```csharp
fork.When("NV Anpassen").Then(nvRemainer);
```

You are connecting the "NV Anpassen" branch to the `TestActivity`, and not the `StartAt` activity. Which causes the latter to be a starting activity (since it doesn't have any incoming connections).

Admittedly this is quite subtle! I didn't see it myself immediately.
I'm not sure how to make this more intuitive, because if you strictly follow the fluid API logic, it makes sense.
If I would somehow return the first activity of the chain (StartAt instead of TestActivity), your code would have worked, but I wonder if this would make sense to users.

**Comment by Rafael94** [comment] 2020-12-15 06:43
Many thanks, that was the problem. I imagined this part of the workflow as a subgraph which is appended by `Then` and didn't think that only the last activity is returned.

I have not yet dealt with it in depth. I am currently trying to improve superficially (separating YesSql and Qartz). Could a new WorkflowBuilder be created and then attached to it? You could then introduce a new function to get the first activities to attach them.

**Comment by sfmskywalker** [comment] 2020-12-16 08:12
Indeed, that might be a nice solution. There’s already a way to build child graphs (used when creating composite activities), so perhaps this can be reused as-is or with some small tweaks.

**Comment by sfmskywalker** [comment] 2021-01-12 19:40
@Rafael94 Can we close this and perhaps open a separate issue for the subgraph thing?

**Closed** 2021-01-13 06:26 UTC
Labels: enhancement
