### ISSUE TITLE
System.NotSupportedException: Deserialization of interface types is not supported.

### ISSUE THREAD

**Issue by witoldkaras** [elsa-workflows/elsa-core#4527] opened 2023-10-12 11:11 UTC
Version: elsaworkflows/elsa-v3:sha-2b90999

Repro:
1. Create and publish workflow containing Switch or SwitchFlow activity with some expression, or alternatively import [expression-bug-test.json](https://github.com/elsa-workflows/elsa-core/files/12880690/expression-bug-test.json)
2. Execute workflow 

Expected result:
Workflow is executed

Actual result:
Following exception appears:
```
System.NotSupportedException: Deserialization of interface types is not supported. Type 'Elsa.Expressions.Contracts.IExpression'. Path: $.condition | LineNumber: 0 | BytePositionInLine: 53.
 ---> System.NotSupportedException: Deserialization of interface types is not supported. Type 'Elsa.Expressions.Contracts.IExpression'.
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at Elsa.Workflows.Core.Serialization.Converters.PolymorphicObjectConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /source/src/modules/Elsa.Workflows.Core/Serialization/Converters/PolymorphicObjectConverter.cs:line 140
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at Elsa.Workflows.Core.Serialization.Serializers.JsonWorkflowStateSerializer.DeserializeAsync(String serializedState, CancellationToken cancellationToken) in /source/src/modules/Elsa.Workflows.Core/Serialization/Serializers/JsonWorkflowStateSerializer.cs:line 53
   at Elsa.EntityFrameworkCore.Modules.Management.EFCoreWorkflowInstanceStore.OnLoadAsync(ManagementElsaDbContext managementElsaDbContext, WorkflowInstance entity, CancellationToken cancellationToken) in /source/src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowInstanceStore.cs:line 126
   at Elsa.EntityFrameworkCore.Common.Store`2.QueryAsync(Func`2 query, Func`4 onLoading, CancellationToken cancellationToken) in /source/src/modules/Elsa.EntityFrameworkCore.Common/Store.cs:line 309
   at Elsa.EntityFrameworkCore.Common.Store`2.QueryAsync(Func`2 query, Func`4 onLoading, CancellationToken cancellationToken) in /source/src/modules/Elsa.EntityFrameworkCore.Common/Store.cs:line 309
   at Open.Linq.AsyncExtensions.Extensions.FirstOrDefault[TSource](Task`1 source)
   at Elsa.EntityFrameworkCore.Modules.Management.EFCoreWorkflowInstanceStore.FindAsync(WorkflowInstanceFilter filter, CancellationToken cancellationToken) in /source/src/modules/Elsa.EntityFrameworkCore/Modules/Management/WorkflowInstanceStore.cs:line 33
   at Elsa.Extensions.WorkflowInstanceStoreExtensions.FindAsync(IWorkflowInstanceStore store, String id, CancellationToken cancellationToken) in /source/src/modules/Elsa.Workflows.Management/Extensions/WorkflowInstanceStoreExtensions.cs:line 18
   at Elsa.Workflows.Runtime.Services.DefaultWorkflowRuntime.ExportWorkflowStateAsync(String workflowInstanceId, CancellationToken cancellationToken) in /source/src/modules/Elsa.Workflows.Runtime/Services/DefaultWorkflowRuntime.cs:line 246
   at Elsa.Workflows.Api.Endpoints.WorkflowDefinitions.Execute.Execute.HandleAsync(Request request, CancellationToken cancellationToken) in /source/src/modules/Elsa.Workflows.Api/Endpoints/WorkflowDefinitions/Execute/Endpoint.cs:line 94
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Elsa.Http.Middleware.WorkflowsMiddleware.InvokeAsync(HttpContext httpContext) in /source/src/modules/Elsa.Http/Middleware/WorkflowsMiddleware.cs:line 147
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

Note: This briefly looks like missing or not working json deserialization discriminator configuration for classes implementing IExpression interface.

**Comment by witoldkaras** [comment] 2023-10-12 11:29
This seems to be regression since 3.0.0-preview.4

**Comment by sfmskywalker** [comment] 2023-10-12 13:30
I’m pretty sure this has been fixed. Would you mind trying out the latest preview packages from feedz.io, even if just to confirm?

**Comment by sfmskywalker** [comment] 2023-10-15 11:41
I just tried to reproduce this issue using the latest source code and the attached workflow JSON, and it worked with no issue. I'll close this issue as "can't reproduce", but if you are still seeing this issue with the latest preview packages and or when running from the latest source code, then please feel free to reopen. Thanks!

**Closed by sfmskywalker** 2023-10-15 11:41 UTC
Labels: bug, elsa 3

**Comment by witoldkaras** [comment] 2023-10-16 12:05
Can confirm as fixed - it's not reproducible when built from source from v3 branch.
