### ISSUE TITLE
As a user I want to change connection between activities in worflow editor

### ISSUE THREAD

**Issue by dust63** [elsa-workflows/elsa-core#1079] opened 2021-06-01 08:53 UTC
In the last version of Elsa dashboard we can change connection between activities in the UI.
I can't do that in the new version.
We also cannot move activities in the place that we want in the grid.

**Comment by matt4446** [comment] 2021-06-01 14:27
Changing connections:
- shift+left-click on the outcome and then on the activity to connect 
- right-click on a connection to remove it

**Comment by dust63** [comment] 2021-06-03 18:53
Hi thank your for the tips. no very user friendly. 
Should be have a tip or help to indicate to user how to achieve it.

**Comment by sfmskywalker** [comment] 2021-06-06 19:07
>Hi thank your for the tips. no very user friendly.

It's documented, but I agree it could be more user friendly or at least documented in the designer itself as suggested in #954

>We also cannot move activities in the place that we want in the grid.

This is by design, but after having worked with the new designer for a while I am considering to investigate a hybrid form where we can still drag around activities and apply an auto-layout on demand, so that we can perhaps have the best of both worlds.

Closing this issue since it's possible to change connections as per @matt4446 's instructions and we are tracking designer improvements elsewhere.

Thanks for the feedback!

**Closed by sfmskywalker** 2021-06-06 19:07 UTC
