### ISSUE TITLE
[BUG]elsa3.2.1版本自定义活动中无法获取变量的值

### ISSUE THREAD

**Issue by lijie66** [elsa-workflows/elsa-core#6101] opened 2024-11-07 06:29 UTC
using Elsa.Extensions;
using Elsa.Workflows;
using Elsa.Workflows.Activities.Flowchart.Attributes;
using Elsa.Workflows.Attributes;
using Elsa.Workflows.Contracts;
using Elsa.Workflows.Helpers;
using Elsa.Workflows.Models;
using Elsa.Workflows.UIHints;
using System.ComponentModel;
using System.Reflection;
namespace Tsz.ServiceApps.Workflow.Elsa.Activity;

[Activity("审批", "审批", "审批")]
[FlowNode("同意", "拒绝")]
[DisplayName("审批")]
public class OutcomeActivity : CodeActivity, IActivityPropertyDefaultValueProvider
{
    public OutcomeActivity()
    {
    }
    [Input(
            Description = "状态码",
            UIHint = InputUIHints.MultiText,
            DefaultValueProvider = typeof(OutcomeActivity)
        )]
    public Input<ICollection<int>> StatusCodes { get; set; } = default!;
    object IActivityPropertyDefaultValueProvider.GetDefaultValue(PropertyInfo property)
    {
        if (property.Name == nameof(StatusCodes))
        {
            return new List<int>
            {
                200,300,400,500
            };
        }
        return default!;
    }
    protected override async ValueTask ExecuteAsync(ActivityExecutionContext context)
    {
        context.SetVariable("id", "123456");
        context.SetVariable("Foo", "Bar");
        CreateBookmarkArgs bookmarkArgs = new CreateBookmarkArgs();
        bookmarkArgs.Payload = "";
        bookmarkArgs.BookmarkName = ActivityTypeNameHelper.GenerateTypeName<OutcomeActivity>();
        bookmarkArgs.Callback = Resume;
        bookmarkArgs.IncludeActivityInstanceId = true;
        var workflowInstanceId = context.WorkflowExecutionContext.Id;
        var correlationId = context.WorkflowExecutionContext.CorrelationId;
        var bookmark = context.CreateBookmark(bookmarkArgs);
        var activityInstanceId = bookmark.ActivityInstanceId;
        await Task.CompletedTask;
    }
    private async ValueTask Resume(ActivityExecutionContext context)
    {
        var id = context.GetVariable<string>("id");
        string outcome = "同意";
        await context.CompleteActivityWithOutcomesAsync(new string[] { outcome });
    }
}

using Elsa.Extensions;
using Elsa.Workflows;
using Elsa.Workflows.Attributes;
using System.ComponentModel;
namespace Tsz.ServiceApps.Workflow.Elsa.Activity;
[Activity("审批", "审批成功", "审批成功")]
[DisplayName("审批成功")]
public class SuccessActivity : CodeActivity
{
    public SuccessActivity()
    {
    }
    protected override async ValueTask ExecuteAsync(ActivityExecutionContext context)
    {
        var foo = context.GetVariable<string>("Foo");
        Console.WriteLine($"foo：{foo}");
        await context.CompleteActivityAsync();
        await Task.CompletedTask;
    }
}

**Comment by sfmskywalker** [comment] 2024-11-11 17:15
Hi @lijie66 , Kindly format your code so we can better see what's going on, and provide a description of what you are trying to do, what you are seeing and what you expected to see. A sample of a workflow of how you're using your activity could be helpful as well. This way, we'll be better able to try and help.

**Comment by sfmskywalker** [comment] 2024-11-11 17:15
Also, please use English to make it easier for us to understand you.

**Comment by lijie66** [comment] 2024-11-13 00:56
Custom Activities can not get Variable

[Custom Activities Code.zip](https://github.com/user-attachments/files/17724556/Custom.Activities.Code.zip)

![image](https://github.com/user-attachments/assets/a45a4008-13f7-488c-96e7-9346af235cb7)

**Comment by lijie66** [comment] 2024-11-13 00:58
![image](https://github.com/user-attachments/assets/89ba22e9-b513-4652-abdc-c266eee643a8)

**Comment by sfmskywalker** [comment] 2024-11-21 20:44
Thanks for sharing your code. When activities set a variable, and that variable doesn't exist on the workflow definition, then the variable will be created within the scope of that activity (e.g. in the scope of `Approve`). This means that when `ApproveSuccess` executes and tries to read the variable, it will not "see" the variable created by the other activity, because it too, has its own scope.

To handle this, you have three options, ordered from worst to best:

- Option 1. Create the variables on the workflow using the designer.
- Option 2. Create & read the variables from a shared scope (e.g. the parent scope of the activity which would be the Flowchart activity's context itself).
- Option 3: Don't create variables from activities that other activities expect to read - instead, treat your activities as "pure functions" that only receive input and produce output. Use workflow variables to capture that output, and use them as input into other activities.

Ideally, your activities have no knowledge at all of the workflow level variables, because that would tight-couple them with your workflow, which is poor design. For this reason, I would advise against option 1.

Option 2 is a little bit better, but here you run the slight risk that other activities that have know knowledge of your activities also try and set a variable with the same name on the same parent context, which would lead to very hard to find bugs.

Option 3 is the best option, because it decouples your activities from each other as well as from workflows that should magically understand to have a certain set of workflow variables defined.

**Comment by sfmskywalker** [comment] 2024-11-21 20:46
Closing the issue because the observed behavior is by design. However, feel free to continue the conversation.

**Closed by sfmskywalker** 2024-11-21 20:46 UTC
Labels: wontfix

**Comment by lijie66** [comment] 2024-11-22 01:36
[activity.zip](https://github.com/user-attachments/files/17853988/activity.zip)
![image](https://github.com/user-attachments/assets/4ac61669-b5c9-402c-b190-85b67e13b598)
![image](https://github.com/user-attachments/assets/04f6a341-d38f-4f2d-ab57-01c319cc783e)

There is no problem with getting variables without using bookmarks, why can't you get variables after using bookmarks
