### ISSUE TITLE
provide Chinese Language pack?

### ISSUE THREAD

**Issue by Dysheng** [elsa-workflows/elsa-core#5854] opened 2024-07-30 15:56 UTC
can this project provide other language support?

**Comment by sfmskywalker** [comment] 2024-11-26 12:51
Hi @Dysheng 

Elsa Studio now supports localization, and we're looking for contributors to help create translations. We use [Weblate](https://hosted.weblate.org/projects/elsa-studio/) to make managing translations simple and collaborative. If you're interested in contributing Chinese translations, please sign up for a Weblate account and share your username or email address with me.

We'd greatly appreciate your help!

**Comment by sfmskywalker** [comment] 2024-11-26 12:52
Marking this issue as a duplicate of #5346

**Closed by sfmskywalker** 2024-11-26 12:52 UTC
Labels: enhancement
