### ISSUE TITLE
[BUG] Variables value with default value cannot be set during execution with RunJavascript

### ISSUE THREAD

**Issue by jeanbaptistedalle** [elsa-workflows/elsa-core#6197] opened 2024-12-10 09:29 UTC
## Description
In a workflow definition, when I create a variable, for example "Variable1" of type "String" and with default value "1", if later in the workflow a use an activity Run JavaScript with the code "setVariable("Variable1", "12")", the value of "Variable1" will not be changed. 

It seems that when I use the activity SetVariable, the variable is set correctly, it's only when I set the variable in RunJavascript that have an issue.

![image](https://github.com/user-attachments/assets/e882e2fb-a0e2-4678-88c4-a95d27c32f3f)

Even if I remove the default value, during execution, the variable's default value will still be an empty string and Run Javascript's setVariable will not work.

The only thing I found to avoid this issue is to remove the line "value" in the json, but I also need default values for some of my workflows

    {
      "id": "f511d27c03fd27eb",
      "name": "Variable1",
      "typeName": "String",
      "value": "",
      "storageDriverTypeName": "Elsa.Workflows.WorkflowInstanceStorageDriver, Elsa.Workflows.Core"
    },

## Steps to Reproduce
1. Import the workflow : [workflow-set-variable.json](https://github.com/user-attachments/files/18076423/workflow-set-variable.json)
2. Execute the workflow
3. See on the instance that the value of Variable1 displayed in the WriteLine activity is still "1", even if I set it to "12" in the RunJavascript activity

## Expected Behavior
Set a variable should modify his value, even if there was some default value set in the variable definition.

**Comment by sfmskywalker** [comment] 2024-12-12 17:37
Hi @jeanbaptistedalle , thank you for the detailed description and workflow JSON file.
However, when I try in the latest version of the main branch, the workflow works as expected: the variable **does** get updated to "12".

<img width="2552" alt="image" src="https://github.com/user-attachments/assets/5eaad7d3-4be6-468e-92d5-1273c4785644" />


I'll close the issue as "can't reproduce" for now, but please feel free to reopen if you can reproduce the issue on the latest preview version, and if so, maybe attach a zipped solution that demonstrates the issue.

**Closed by sfmskywalker** 2024-12-12 17:37 UTC
Labels: bug
