### ISSUE TITLE
Issue in Serializing Workflow

### ISSUE THREAD

**Issue by sagargolu** [elsa-workflows/elsa-core#4132] opened 2023-06-13 13:59 UTC
@sfmskywalker 

I need your help in achieving the serialization. Actually, I am adding new activity from code in existing workflowdefinition but some how it is not getting serialized at the end. I am providing you whole code so that you can review it and let us know where is the issue.

`var filterWf = new WorkflowDefinitionFilter { DefinitionId = workflowInstance.DefinitionId };`

            var wfDefinition = await _definitionStore.FindLastVersionAsync(filterWf, cancellationToken);
            var mapper = new WorkflowDefinitionMapper();
            var response = await mapper.FromEntityAsync(wfDefinition, cancellationToken);
				var activities = ((Flowchart)response.Root).Activities;
				WorkflowDefinitionActivity activity = new WorkflowDefinitionActivity();
				activity.Id = $"subproc_{suppDefId.Name}";
				activity.Type = suppDefId.Name;
				activity.Version = suppDefId.Version;
				activity.Source = null;
				activity.CanStartWorkflow = false;
				activity.LatestAvailablePublishedVersion = suppDefId.Version;
				activity.Result = null;
				activity.RunAsynchronously = false;
				activity.Line = null;
				activity.WorkflowDefinitionId = suppDefId.DefinitionId;
				activity.Metadata = null;
				((Flowchart)response.Root).Activities.Add(activity);
				
				var workflowJson = System.Text.Json.JsonSerializer.Serialize(response.Root, _serializerOptionsProvider.CreatePersistenceOptions());`

**Comment by sfmskywalker** [comment] 2023-10-15 11:20
Hi @sagargolu , I don't see the issue when looking at the code. Would you be able to send me a sample program I can run? And what exactly is the issue you are seeing?

**Comment by sfmskywalker** [comment] 2023-11-03 19:48
I'll close this for now since I am unable to reproduce the issue. Please feel free to reopen the issue if you have repro steps that I can try.

**Closed** 2023-11-03 19:49 UTC
Labels: bug, elsa 3
