### ISSUE TITLE
Slow performance of workflow-instances Page

### ISSUE THREAD

**Issue by kelvenray** [elsa-workflows/elsa-core#3513] opened 2022-12-08 06:01 UTC
As I try to get the run records of the Workflows, I found that the page loading is extremy slow.
It takes around 14-15 seconds to load the page. Even I only get 41 records and the pageSize is default to 15.
![image](https://user-images.githubusercontent.com/2155845/206368276-4a6aae85-f007-4525-903d-b9b9e3268be7.png)

The response size is only 6.3K so we can ignore the network issue.
I think I find something when I look into the database.
I try to query out all the data in the **WorkflowInstances** table (without joinning any other table).
You can refer to the result below, it takes around 8 seconds...... There are only 41 rows!
![image](https://user-images.githubusercontent.com/2155845/206368893-56695240-d073-44fd-ad4e-fcf79159d8be.png)
Then I try again with comment out the [Data] column, the query run very fast this time, almost come out "realtime".
![image](https://user-images.githubusercontent.com/2155845/206369321-b2a61f4f-b4bc-4b6e-8a04-b324c071e547.png)

So I think the dev teams need to consider how to improve this.

**Comment by sfmskywalker** [comment] 2023-02-09 07:44
This is fixed in V3.

**Closed** 2023-02-22 09:32 UTC

**Comment by Reinhartdelille** [comment] 2023-04-27 12:51
Hi, I stumbled As there is no V3 nuget release yet, is there a hack we can apply to V2.11 to get this problem out of the way? I reckon it's an EF thing?

**Comment by sfmskywalker** [comment] 2023-05-10 20:39
Indeed, the issue is that the EF provider is including the `Data` column when querying workflow instances.
It can probably be fixed, but it may or may not be trivial.

If you want to give V3 a spin, you can find it on the preview feed (feedz.io), details here: https://v3.elsaworkflows.io/docs/installation/packages#feeds

V3 RC is slated for later this month (May 31).

**Comment by Reinhartdelille** [comment] 2023-05-11 12:21
Hi

Will certainly give it a try! I was able to bypass the problem btw by using YesSQL as a DB provider for MSSQLServer. works out of the box :)
