### ISSUE TITLE
[suggested bug] InMemoryStore is not thread safe

### ISSUE THREAD

**Issue by Invenisso** [elsa-workflows/elsa-core#2453] opened 2021-11-05 15:04 UTC
Hello Community! 

InMemoryStore is not thread safe because it is using simple Dictionary underneath. Exception may appear when many bus workers.

![image](https://user-images.githubusercontent.com/57659054/140522750-813a5339-9aa6-4cec-aed2-a97a7a69369c.png)

Steps to reproduce.

Modify Elsa.Samples.CustomOutcomeActivityConsole example like this and run few times until the error occurs.

```
 class Program
    {
        private static async Task Main()
        {
            // Create a service container with Elsa services.
            var services = new ServiceCollection()
                .AddElsa(options =>
                   {
                       options
                          .AddConsoleActivities()
                          .AddActivity<SomeCustomActivity>()
                          .AddWorkflow<DemoWorkflow>();

                       options.ElsaOptions.ServiceBusOptions.NumberOfWorkers = 100;
                       options.ElsaOptions.ServiceBusOptions.MaxParallelism = 50;

                   }

                )
                .BuildServiceProvider();

            // Run startup actions (not needed when registering Elsa with a Host).
            var startupRunner = services.GetRequiredService<IStartupRunner>();
            await startupRunner.StartupAsync();

            var dispatcher = services.GetRequiredService<IWorkflowDefinitionDispatcher>();
            for (int i = 0; i < 5000; i++)
            {
                await dispatcher.DispatchAsync(new ExecuteWorkflowDefinitionRequest("DemoWorkflow"));
            }

            Console.ReadLine();

        }
    }
```
(I know that MaxParallelism < NumberOfWorkflows is a stupid configuration, but I found this exception to be easier to raise with these settings.)

PS. Another error may appear during execution - System.UnauthorizedAccessException: 'Access to the path' C: \ Users \ Invenisso \ AppData \ Local \ Temp \ execute_workflow_definitionZDIA7GR5FQLVK2GQ6WQSLQLW3FV3XHCL.lock 'is denied.'
This exception is also strange, but it does not affect the number of workflows executed, so you can skip it and continue the program execution.

**Comment by sfmskywalker** [comment] 2021-11-22 20:04
Thanks for the great repro! @Kinani has fixed the concurrency issue with the in-memory provider. I just tested his fix with your code sample, and was unable to reproduce the issue.

I'll close this issue as fixed, but feel free to reopen if you think there still may be an issue.

**Closed by sfmskywalker** 2021-11-22 20:04 UTC
