### ISSUE TITLE
Docker Image not bringing up the dashboard, shows a blank screen with a java error in the console

### ISSUE THREAD

**Issue by Steven23456** [elsa-workflows/elsa-core#4668] opened 2023-11-29 19:25 UTC
From Console
`Uncaught (in promise) TypeError: r.originalAdapter.call is not a function
    at e (p-e37496bc.js:2:897)
    at async Object.list (p-04c30d61.js:1:4811)
    at async se.componentWillLoad (p-23353c0b.entry.js:1:21264)`

**Comment by jdevillard** [comment] 2023-12-05 14:18
Hello, is this for v2 or v3?

**Comment by ErnestManukyanPlatAi** [comment] 2023-12-05 14:20
hello, v3

**Comment by YuriiFozekosh** [comment] 2023-12-05 21:21
same for me with v2. Using command from quickstart: 
`docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:13000' -p 13000:80 elsaworkflows/elsa-dashboard-and-server:latest`
I have tried older versions of the container up to **sha-6e73b73** 5 months ago, but the error is the same

**Comment by Day-Go** [comment] 2023-12-06 02:44
Same issue for me. Even happened with older docker images.

**Comment by BostrongLonsec** [comment] 2023-12-06 04:12
Same issue for me ... using v2 ... elsaworkflows/elsa-dashboard:latest

**Comment by BostrongLonsec** [comment] 2023-12-06 04:13
Sorry some more detail:

![image](https://github.com/elsa-workflows/elsa-core/assets/115444347/68238502-a6ab-4a87-8117-9dd1c4309d87)

**Comment by BostrongLonsec** [comment] 2023-12-06 06:05
Could it possibly be related to this release (Bump axios from 0.26.1 to 1.6.0) ...
https://github.com/elsa-workflows/elsa-core/actions/runs/6854901019/job/18638799084

I came across some breaking changes other axios users have run into.
One is specifically related to stencil which assumed might be relevant:
https://github.com/axios/axios/issues/6093

Apologies if this is not relevant. Just new to Elsa (and\or Axios\Stencil) .. tried to run the Elsa dashboard in docker for first time today and running into same above issue as everybody else.

**Comment by BostrongLonsec** [comment] 2023-12-07 00:31
same as this issue https://github.com/elsa-workflows/elsa-core/issues/4645

**Comment by lebatuananh** [comment] 2023-12-10 02:15
@BostrongLonsec I also have the same problem as you, did you solve it?

**Comment by sfmskywalker** [comment] 2023-12-13 09:08
The [V3 Docker documentation page](https://v3.elsaworkflows.io/docs/installation/docker) has been updated with the correct command to pull & run the All In One reference application.

**Comment by sfmskywalker** [comment] 2023-12-13 09:10
For V2, I also get a blank page with the following JS error:

```
p-e37496bc.js:2  Uncaught (in promise) TypeError: r.originalAdapter.call is not a function
    at e (p-e37496bc.js:2:897)
    at async Object.list (p-04c30d61.js:1:4811)
    at async se.componentWillLoad (p-23353c0b.entry.js:1:21264)
```

**Comment by sfmskywalker** [comment] 2023-12-13 09:12
Looks like this issue is a duplicate of #4645, which was reported a week earlier, so I will close this one out as duplicate. Thanks for reporting!

**Closed by sfmskywalker** 2023-12-13 09:12 UTC
Labels: elsa 2

**Comment by BostrongLonsec** [comment] 2023-12-13 23:42
> @BostrongLonsec I also have the same problem as you, did you solve it?

I think Spike is on it. Please comments above.
