### ISSUE TITLE
Hello "Workflow Instance Storage" not work in Variable  [BUG]

### ISSUE THREAD

**Issue by zesmaili** [elsa-workflows/elsa-core#5653] opened 2024-06-24 09:55 UTC
hi

In Elsa's workflow document, there is a section titled "Storage Providers" in the "Variables" section, which clearly states that it is possible to store the variable value in "Workflow Instance", but I have never seen such a thing.
Can you guide me in this regard, how to get the value of the variable in the "Execute" method of my activity only through "ActivityExecutionContext" without defining it as the input of my activity.

https://v3.elsaworkflows.io/docs/core-concepts/variables

**Comment by zesmaili** [comment] 2024-06-24 10:48
> Certainly! In Elsa, variables can be stored in the workflow instance, which allows them to be accessed throughout the workflow's execution. To retrieve the value of a variable within the `Execute` method of your activity using only the `ActivityExecutionContext`, you can use the `GetVariable` method provided by the context.
> 
> Here's an example of how you might retrieve a variable named "MyVariable" within an activity:
> 
> ```cs
> protected override async ValueTask<IActivityExecutionResult> OnExecuteAsync(ActivityExecutionContext context)
> {
>     // Retrieve the variable value from the workflow instance storage.
>     var myVariableValue = context.GetVariable<string>("MyVariable");
> 
>     // Use the variable value as needed in your activity logic.
>     // ...
> 
>     return Done();
> }
> ```
> 
> In this example, `GetVariable<T>` is a generic method where `T` is the type of the variable you are retrieving. Replace `string` with the appropriate data type of your variable.
> 
> Please note that for this to work, the variable "MyVariable" must have been previously created and stored in the workflow instance. This can be done programmatically when building the workflow or through the designer interface.
> 
> For more information on variables and their usage in Elsa, you can refer to the documentation on variables at the provided link.
> 
> This comment was generated by [Glime](https://glimelab.ai/?utm_source=dRbvTb7IhCSYiI&utm_medium=github).

No, this command doesn't work either, for example in the "Onboarding" workflow created in the link:
https://v3.elsaworkflows.io/docs/guides/external-app-integration

I made changes 
![Elsa_Test](https://github.com/elsa-workflows/elsa-core/assets/110331566/5f7b066a-11fc-458a-853d-d28a3803bb59)

and created a new variable called testVar, and then changed the value of the variable through the SetVariable activity, 

![Elsa_Test2](https://github.com/elsa-workflows/elsa-core/assets/110331566/baa4cf37-24a3-43ce-bd99-a4829d6ca7f9)

and finally received the value using the mentioned method in the SendEmail activity.
**The value was equal to null**

**Comment by sfmskywalker** [comment] 2024-07-05 18:49
@zesmaili Are you able to reproduce this issue with the latest 3.2-preview packages?

**Comment by sfmskywalker** [comment] 2024-07-05 18:56
I have tested it just now, and it works correctly with the latest 3.2 preview (which is currently being built as 3.2.0-rc2 for deployment to NuGet).

I tested with this custom activity:

```csharp
public class MyVariableSetterActivity : CodeActivity
{
    protected override void Execute(ActivityExecutionContext context)
    {
        context.SetVariable("Foo", "baz");
    }
}
```

In my workflow, I defined a variable called `Foo` with a default value of `X`.
The workflow looks like this:

<img width="2550" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/938393/6b108824-7aa8-48b2-94a6-53a5bdd02a5a">

Since I am unable to reproduce the reported symptom in the latest version, I will close this bug. However, please feel free to reopen if you can provide a reproduction using the latest (preview) version.

**Closed** 2024-07-05 18:57 UTC
Labels: bug

**Comment by zesmaili** [comment] 2024-07-17 11:21
> @zesmaili Are you able to reproduce this issue with the latest 3.2-preview packages?

yes
