### ISSUE TITLE
[BUG] ELSA 3.3.0-rc3: Cancelling of Workflow Instance via REST API fails

### ISSUE THREAD

**Issue by r-kernberger** [elsa-workflows/elsa-core#6222] opened 2024-12-17 13:54 UTC
## Description
When Executing the Cancel Endpoint of the ELSA 3 REST API there is an Exception stating that there is no handler for CancelWorkflowsCommand available. 

So Cancelling is not possible via REST.

Is this a known issue?

Find the Stacktrace and screenshot of Swagger result below:
```c#
System.InvalidOperationException: There is no handler to handle the Elsa.Workflows.Runtime.Commands.CancelWorkflowsCommand command
   at Elsa.Mediator.Middleware.Command.Components.CommandHandlerInvokerMiddleware.InvokeAsync(CommandContext context)
   at Elsa.Mediator.Middleware.Command.CommandPipeline.InvokeAsync(CommandContext context)
   at Elsa.Mediator.Services.DefaultMediator.SendAsync(ICommand command, ICommandStrategy strategy, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.BackgroundWorkflowCancellationDispatcher.DispatchAsync(DispatchCancelWorkflowRequest request, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.WorkflowCancellationService.CancelWorkflows(IList`1 workflowInstances, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.WorkflowCancellationService.CancelWorkflowAsync(String workflowInstanceId, CancellationToken cancellationToken)
   at Elsa.Workflows.Api.Endpoints.WorkflowInstances.Cancel.Cancel.HandleAsync(Request request, CancellationToken cancellationToken)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)`
``` 

![image](https://github.com/user-attachments/assets/f027ca37-5cc6-4f05-9403-2817b592be20)

**Comment by sfmskywalker** [comment] 2024-12-28 13:30
I just tried with the latest version (current tip from `main` branch), and cancelling a suspended workflow instance succeeds. Perhaps you encountered an issue that has been fixed after the RC3 release.

I'll close the issue as "cannot reproduce", but please feel free to add repro steps in case you're encountering this issue still with the latest preview builds.

Thank you.

**Closed by sfmskywalker** 2024-12-28 13:30 UTC
Labels: bug
