### ISSUE TITLE
elsa v3  Except for JoinFlow, other nodes should only allow one left connection

### ISSUE THREAD

**Issue by Nokecy** [elsa-workflows/elsa-core#4443] opened 2023-09-15 09:06 UTC
@sfmskywalker

**Comment by Nokecy** [comment] 2023-09-15 09:15
```
public class SequenceFlowOneActivityTwoBuiltInConnectWorkflow : WorkflowBase
{
    protected override void Build(IWorkflowBuilder builder)
    {
        var setName = new SetName()
        {
            Value = new("abc")
        };

        var userTask1 = new WriteLine("user task1")
        {
            Name = "userTask1",
        };

        var userTask2 = new WriteLine("user task2")
        {
            Name = "userTask2",
        };

        var userTask3 = new WriteLine("user task3")
        {
            Name = "userTask3",
        };

        builder.Root = new Flowchart
        {
            Activities =
                {
                    setName,
                    userTask1,
                    userTask2,
                    userTask3
                },

            Connections =
                {
                    new Connection(new Endpoint(setName),new Endpoint(userTask1,"In")),
                    new Connection(new Endpoint(userTask1,"下一步"),new Endpoint(userTask3,"In")),
                    new Connection(new Endpoint(userTask2,"下一步"),new Endpoint(userTask3,"In"))
                }
        };
    }
}
```

like this workflow instance never completes

**Comment by sfmskywalker** [comment] 2023-09-18 10:23
I can confirm the issue.

**Comment by sfmskywalker** [comment] 2023-09-18 10:37
Actually, upon further investigation, the flowchart operates as designed.

Here's the same flowchart, visualised:

<img width="979" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/938393/b54cd39f-40fd-435a-a61d-ac9846b34c7b">

Notice that "user task3" has two inbound paths: one from "user task1" and one from "user task2".

When this flowchart executes, it will start with "Set Name" and then "user task1".
In turn, the flowchart will try to schedule "user task3", but only after all of its inbound paths have executed - which is not the case, because "user task2" hasn't executed.

Essentially, the implicit **join** between task1 and task2 into task3 implements the **Wait All** join mode.
If you want to use **Wait Any** instead, you can model the joining of two branches explicitly using the **Flow Join** activity:

<img width="1209" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/938393/833a218a-e969-48ed-85b9-296730b96ff1">

Notice that using a Wait Any join, the workflow does complete.

I will close this issue as "by design", but please feel free to continue the conversation and or if I misunderstood something.

**Closed by sfmskywalker** 2023-09-18 10:37 UTC
Labels: bug, elsa 3

**Comment by Nokecy** [comment] 2023-09-18 11:20
> Essentially, the implicit join between task1 and task2 into task3 implements the Wait All join mode.

Can add a configurable option waitAll/waitAny  ? @sfmskywalker

**Comment by sfmskywalker** [comment] 2023-09-18 11:24
@Nokecy We certainly could! I'm wondering if we need to expose this as an option at two levels:

1. Application level
2. Workflow level

**Application level**
We could configure the implicit join behaviour using options that is used for all workflows.

**Workflow level**
We could also add an option to the workflow itself, so that the user creating the workflow can control the implicit join behavior per workflow.

But, I also think this could potentially lead to massive confusion if some workflows behave differently from others, even if they are structurally the same,

Thoughts?

**Comment by Nokecy** [comment] 2023-09-18 11:50
Just like what you did for Incidents ，Provide a workflow level setting and default values. @sfmskywalker
