### ISSUE TITLE
Signal URL Link Executes Workflow On Second Click !!!

### ISSUE THREAD

**Issue by baraanaser** [elsa-workflows/elsa-core#662] opened 2021-02-25 10:18 UTC
Hi,
i have Elsa workflow last version already installed  and running successfully (.net 5 core) and i have created a workflow that sends email with an rejection/activation links , when i click first time on the link nothing happens just link loads quickly in the browser, second click  on the link it takes a while and executes the workflow instance successfully.

I have 3 blocking activities , one of them timeout activity (5 min timeout)
https://prnt.sc/106iv1y

When i remove timeout activity it works

Elsa In App Settings :

"Elsa": {
    "Http": {
      "BaseUrl": "https://localhost:44302/"
    },
    "Smtp": {
      my-smtp-configs..........
    },
    "BackgroundRunner": {
      "SweepInterval": "PT01S"
    }
  },

Thanks for your replies!

**Comment by sfmskywalker** [comment] 2021-02-25 12:10
Can you show us your workflow?

**Comment by baraanaser** [comment] 2021-02-25 12:31
This workflow was for testing

https://prnt.sc/106k5sp

**Comment by baraanaser** [comment] 2021-02-25 12:32
> Can you show us your workflow?

This workflow was for testing

https://prnt.sc/106k5sp

**Comment by sfmskywalker** [comment] 2021-02-25 12:57
Interesting. Any chance you can send over the exported JSON so I can try and reproduce (and troubleshoot)?

**Comment by baraanaser** [comment] 2021-02-25 13:01
{"activities":[{"id":"bfa5c700-0480-433a-8434-9e1173eb4632","type":"SendEmail","left":231,"top":878,"state":{"from":{"expression":"","syntax":"Literal"},"to":{"expression":"","syntax":"Liquid"},"subject":{"expression":"Document is Accepted","syntax":"Literal"},"body":{"expression":"The document of name is accepted successfully","syntax":"Liquid"},"name":"","title":"Approved Email","description":"Send Approved Email"},"blocking":false,"executed":false,"faulted":false},{"id":"ca7c3c26-3b57-4fdf-92ec-0acf23c4c60f","type":"Finish","left":311,"top":1129,"state":{"name":null},"blocking":false,"executed":false,"faulted":false},{"id":"d485ad05-b2ed-4e92-8857-58e380482a68","type":"TimerEvent","left":561,"top":489,"state":{"name":"","timeoutExpression":{"expression":"00:05:00","syntax":"Literal"},"title":"Timeout Activation","description":""},"blocking":false,"executed":false,"faulted":false},{"id":"bc71c41c-b4fc-452b-84d1-deaa4d3a8eb6","type":"Signaled","left":27,"top":7,"state":{"signal":{"expression":"DocumentActivation","syntax":"Literal"},"name":"","title":"Document Activation Signal","description":"Waiting for a signal"},"blocking":false,"executed":false,"faulted":false},{"id":"52d5cd11-54a6-48d7-b283-cd5f69f43fb2","type":"SendEmail","left":939,"top":1211,"state":{"from":{"expression":"","syntax":"Literal"},"to":{"expression":"","syntax":"Liquid"},"subject":{"expression":"Document is Rejected","syntax":"Literal"},"body":{"expression":"The document of name  is rejected","syntax":"Liquid"},"name":"","title":"Rejected Email","description":"Send Rejected Email"},"blocking":false,"executed":false,"faulted":false},{"id":"997e39fa-3bf6-4f05-af0b-85567d45a5d3","type":"Join","left":572,"top":691,"state":{"mode":"WaitAny","name":"","title":"","description":""},"blocking":false,"executed":false,"faulted":false},{"id":"9a6851b1-31f2-4f59-b2f8-d8d278df6781","type":"SendEmail","left":556,"top":36,"state":{"from":{"expression":"","syntax":"Literal"},"to":{"expression":"","syntax":"Literal"},"subject":{"expression":"Document Activation","syntax":"Literal"},"body":{"expression":"A new document is created or updated with the following details :\r\n<br><br>\r\n\r\n\r\n\r\n<a href=\"{{ 'AcceptDocument' | signal_url}}\">Accept Document</a>\r\n<br>\r\n<a href=\"{{ 'RejectDocument' | signal_url}}\">Reject Document</a>\r\n<br>","syntax":"Liquid"},"name":"","title":"Send Activation Email","description":""},"blocking":false,"executed":false,"faulted":false},{"id":"0d2d8bb4-d3b3-485d-8d4b-52100f1df883","type":"SetVariable","left":953,"top":685,"state":{"variableName":"Approved","valueExpression":{"expression":"{{ \"false\" }}","syntax":"Liquid"},"name":"","title":"","description":""},"blocking":false,"executed":false,"faulted":false},{"id":"347e4207-638b-44b1-b40d-fb7732d95fed","type":"IfElse","left":560,"top":866,"state":{"conditionExpression":{"expression":"Approved ==  \"true\"","syntax":"Liquid"},"name":"","title":"Send Email When Reject/Approve","description":""},"blocking":false,"executed":false,"faulted":false},{"id":"764e2974-edd1-4f74-8d93-e64fbd783c14","type":"IfElse","left":1090,"top":932,"state":{"conditionExpression":{"expression":"Approved == \"false\"","syntax":"Liquid"},"name":"","title":"If not Approved","description":""},"blocking":false,"executed":false,"faulted":false},{"id":"16aadc7c-4b2b-4785-add2-b34cd63446a2","type":"Signaled","left":165,"top":351,"state":{"signal":{"expression":"AcceptDocument","syntax":"Literal"},"name":"","title":"Accept Document Signal","description":"Waiting for a signal"},"blocking":false,"executed":false,"faulted":false},{"id":"8336c49f-4307-4100-9b06-4a87bc96b486","type":"ReceiveHttpRequest","left":28,"top":125,"state":{"path":"/test","method":"GET","readContent":null,"name":"","title":"","description":""},"blocking":false,"executed":false,"faulted":false},{"id":"7a7a6224-9f4f-4cd4-b8d6-1f8b0645bda6","type":"SetVariable","left":903,"top":39,"state":{"variableName":"Approved","valueExpression":{"expression":"{{ \"undefined\" }}","syntax":"Liquid"},"name":"","title":"Initialize Approved Variable","description":""},"blocking":false,"executed":false,"faulted":false},{"id":"ae341b74-b702-4026-bd5c-d4ac283a1ee0","type":"SetVariable","left":234,"top":683,"state":{"variableName":"Approved","valueExpression":{"expression":"{{ \"true\" }}","syntax":"Liquid"},"name":"","title":"","description":""},"blocking":false,"executed":false,"faulted":false},{"id":"60564d22-70fd-414c-a5e2-602b49dcac01","type":"Fork","left":583,"top":307,"state":{"branches":["Accept Document","Reject Document","Time Out"],"name":"","title":"","description":"reject/accept/timeout"},"blocking":false,"executed":false,"faulted":false},{"id":"10083ce4-c618-46dc-b791-124bad353c7d","type":"Signaled","left":911,"top":375,"state":{"signal":{"expression":"RejectDocument","syntax":"Literal"},"name":"","title":"Reject Document Signal","description":"Waiting for a signal"},"blocking":false,"executed":false,"faulted":false}],"connections":[{"sourceActivityId":"ae341b74-b702-4026-bd5c-d4ac283a1ee0","destinationActivityId":"997e39fa-3bf6-4f05-af0b-85567d45a5d3","outcome":"Done"},{"sourceActivityId":"7a7a6224-9f4f-4cd4-b8d6-1f8b0645bda6","destinationActivityId":"60564d22-70fd-414c-a5e2-602b49dcac01","outcome":"Done"},{"sourceActivityId":"997e39fa-3bf6-4f05-af0b-85567d45a5d3","destinationActivityId":"347e4207-638b-44b1-b40d-fb7732d95fed","outcome":"Done"},{"sourceActivityId":"347e4207-638b-44b1-b40d-fb7732d95fed","destinationActivityId":"764e2974-edd1-4f74-8d93-e64fbd783c14","outcome":"False"},{"sourceActivityId":"764e2974-edd1-4f74-8d93-e64fbd783c14","destinationActivityId":"ca7c3c26-3b57-4fdf-92ec-0acf23c4c60f","outcome":"False"},{"sourceActivityId":"16aadc7c-4b2b-4785-add2-b34cd63446a2","destinationActivityId":"ae341b74-b702-4026-bd5c-d4ac283a1ee0","outcome":"Done"},{"sourceActivityId":"8336c49f-4307-4100-9b06-4a87bc96b486","destinationActivityId":"9a6851b1-31f2-4f59-b2f8-d8d278df6781","outcome":"Done"},{"sourceActivityId":"bc71c41c-b4fc-452b-84d1-deaa4d3a8eb6","destinationActivityId":"9a6851b1-31f2-4f59-b2f8-d8d278df6781","outcome":"Done"},{"sourceActivityId":"347e4207-638b-44b1-b40d-fb7732d95fed","destinationActivityId":"bfa5c700-0480-433a-8434-9e1173eb4632","outcome":"True"},{"sourceActivityId":"bfa5c700-0480-433a-8434-9e1173eb4632","destinationActivityId":"ca7c3c26-3b57-4fdf-92ec-0acf23c4c60f","outcome":"Done"},{"sourceActivityId":"10083ce4-c618-46dc-b791-124bad353c7d","destinationActivityId":"0d2d8bb4-d3b3-485d-8d4b-52100f1df883","outcome":"Done"},{"sourceActivityId":"0d2d8bb4-d3b3-485d-8d4b-52100f1df883","destinationActivityId":"997e39fa-3bf6-4f05-af0b-85567d45a5d3","outcome":"Done"},{"sourceActivityId":"60564d22-70fd-414c-a5e2-602b49dcac01","destinationActivityId":"16aadc7c-4b2b-4785-add2-b34cd63446a2","outcome":"Accept Document"},{"sourceActivityId":"764e2974-edd1-4f74-8d93-e64fbd783c14","destinationActivityId":"52d5cd11-54a6-48d7-b283-cd5f69f43fb2","outcome":"True"},{"sourceActivityId":"9a6851b1-31f2-4f59-b2f8-d8d278df6781","destinationActivityId":"7a7a6224-9f4f-4cd4-b8d6-1f8b0645bda6","outcome":"Done"},{"sourceActivityId":"52d5cd11-54a6-48d7-b283-cd5f69f43fb2","destinationActivityId":"ca7c3c26-3b57-4fdf-92ec-0acf23c4c60f","outcome":"Done"},{"sourceActivityId":"60564d22-70fd-414c-a5e2-602b49dcac01","destinationActivityId":"10083ce4-c618-46dc-b791-124bad353c7d","outcome":"Reject Document"},{"sourceActivityId":"60564d22-70fd-414c-a5e2-602b49dcac01","destinationActivityId":"d485ad05-b2ed-4e92-8857-58e380482a68","outcome":"Time Out"},{"sourceActivityId":"d485ad05-b2ed-4e92-8857-58e380482a68","destinationActivityId":"997e39fa-3bf6-4f05-af0b-85567d45a5d3","outcome":"Done"}]}

**Comment by baraanaser** [comment] 2021-02-25 16:59
> Interesting. Any chance you can send over the exported JSON so I can try and reproduce (and troubleshoot)?

https://drive.google.com/file/d/18-5zRI1g-88KPBqZdYrOMTyaew2LFAlF/view

you need to set your FROM/TO email in email activities

**Comment by baraanaser** [comment] 2021-02-26 21:12
@sfmskywalker 
any news thanks!

**Comment by sfmskywalker** [comment] 2021-02-26 21:35
Not yet, sorry. I hope to be able to look into it soon.

**Comment by sfmskywalker** [comment] 2021-02-28 10:35
I just tried your workflow, but it's working fine when I try. The workflow responds as soon as I click either Approve or Reject.

One thing you can try is do what I did:
Clone the Elsa Core project, checkout the master branch, and launch the Elsa.Dashboard.Web application. Then import the JSON you sent me (making sure you provide from/to values) and see if you can reproduce the issue.
I know this won't help your current project immediately, but it would be a good first step into getting a working baseline.

**Comment by baraanaser** [comment] 2021-02-28 11:39
> I just tried your workflow, but it's working fine when I try. The workflow responds as soon as I click either Approve or Reject.
> 
> One thing you can try is do what I did:
> Clone the Elsa Core project, checkout the master branch, and launch the Elsa.Dashboard.Web application. Then import the JSON you sent me (making sure you provide from/to values) and see if you can reproduce the issue.
> I know this won't help your current project immediately, but it would be a good first step into getting a working baseline.

Hi and thanks for your time ,
I know it works with default sweepInterval but seems not with   **"SweepInterval": "PT01S"**
https://prnt.sc/1099lym

Can you try it with "SweepInterval": "PT01S"? Thanks!

With default  "SweepInterval": "0:00:00:10" it works with me before but sometimes workflow instance stay **executing** and not finished , that's why i used **PT01S**

Best Regards

**Comment by baraanaser** [comment] 2021-03-02 09:20
any replies ?

**Comment by sfmskywalker** [comment] 2021-03-05 12:59
It sounds like you are facing a number of bugs, one less subtle than the other. Unfortunately I do not currently have the bandwidth to dig into this, but I suspect the majority of the issues are caused by the scheduler implementation. In which case all of the issues you are seeing will have been fixed with Elsa 2. I wish I had a better answer for you, but I'm afraid we'll have to wait for the release of Elsa 2 end of this month (barring any delays).

In the meantime, you might consider switching to the Elsa 2 preview packages. Although the designer isn't ready yet, you could leverage the workflow builder API and write your workflows using C# code. You'd be using the same activities, so functionally it will be the same when you switch back to using the designer.

**Comment by sfmskywalker** [comment] 2021-05-25 14:57
Closing the issue since it's working as advertised in Elsa 2 (which will be released this week 🥳 ).

**Closed by sfmskywalker** 2021-05-25 14:57 UTC
Labels: help wanted
