### ISSUE TITLE
Setting UsableAsActivity to true results in exception

### ISSUE THREAD

**Issue by Eitanski** [elsa-workflows/elsa-core#4700] opened 2023-12-13 07:38 UTC
I have this super simple barebones code:
```
using Elsa.Workflows.Core;
using Elsa.Workflows.Core.Activities;
using Elsa.Workflows.Core.Contracts;

namespace ElsaTrial;

public class TrialWorkflow:WorkflowBase
{
    protected override ValueTask BuildAsync(IWorkflowBuilder builder, CancellationToken cancellationToken = new CancellationToken())
    {
        builder.Root = new WriteLine("text");
        builder.WorkflowOptions.UsableAsActivity = true;
        return base.BuildAsync(builder, cancellationToken);
    }
}


my Program.cs:
using Elsa.Extensions;
using ElsaTrial;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddElsa(elsa => elsa.AddWorkflow<TrialWorkflow>());
var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.Run();
```

The code results in this exception:
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at Humanizer.InflectorExtensions.Pascalize(String input) in /_/src/Humanizer/InflectorExtensions.cs:line 74
   at Elsa.Workflows.Management.Activities.WorkflowDefinitionActivity.WorkflowDefinitionActivityProvider.CreateDescriptor(Workflow
Definition definition, ICollection`1 allDefinitions)
   at Elsa.Workflows.Management.Activities.WorkflowDefinitionActivity.WorkflowDefinitionActivityProvider.<>c__DisplayClass4_0.<Cre
ateDescriptors>b__0(WorkflowDefinition x)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at Elsa.Workflows.Core.Services.ActivityRegistry.AddMany(Type providerType, IEnumerable`1 descriptors)
   at Elsa.Workflows.Management.Services.ActivityRegistryPopulator.PopulateRegistryAsync(IActivityProvider provider, CancellationT
oken cancellationToken)
```

When I set the flag to false, everything works fine. What is this 'input' parameter?

**Comment by jdevillard** [comment] 2023-12-13 09:30
Hello ,

The input is the `definition.Name` that is pascalized using an extension method.
It seems to be null in your case. I can't reproduce, using your code (I've got `TrialWorkflow` as the Name which seems to be correct ), what version of Elsa / nugget are you using?

**Comment by jdevillard** [comment] 2023-12-14 21:38
Hello , 

I've tested without filling the Name property and it work. 

But the latest version is not 3.0.0-preview.727 for me (727 is dated from 17 sept. 2023). 

Could you test with a version later than .890 ?

**Comment by sfmskywalker** [comment] 2024-01-06 13:56
Hi @Eitanski , I also tried to reproduce the issue, but to no avail. I will close the issue as such, but please feel free to reopen it if you can still reproduce this behaviour with the latest version. In that case, it would be great if you could attach a zip file of a sample project that demonstrates the behaviour. Thank you.

**Closed by sfmskywalker** 2024-01-06 13:56 UTC
