### ISSUE TITLE
Start a workflow from IWorkflowDefinitionDispatcher 

### ISSUE THREAD

**Issue by Juandavi1** [elsa-workflows/elsa-core#1199] opened 2021-07-01 17:12 UTC
Hi guy, 

I am starting workflows through IWorkflowDefinitionDispatcher but after updating to version 2.1 it throws the following exception

code:

```
private readonly IWorkflowDefinitionDispatcher _dispacher;

 await dispacher.DispatchAsync(
  new ExecuteWorkflowDefinitionRequest(
      message.WorkflowDefinition.DefinitionId,
      null,
      input,
      correlationId
));

```
exception: 

`System.ArgumentException: Cannot get destination for message of type Elsa.Services.ExecuteWorkflowDefinitionRequest because it has not been mapped!`

`You need to ensure that all message types that you intend to bus.Send or bus.Subscribe to are mapped to an endpoint - it can be done by calling .Map<SomeMessage>(someEndpoint) or .MapAssemblyOf<SomeMessage>(someEndpoint) in the routing configuration.`

Should I do something additional in this new version?

thank you very much for this super project

**Comment by sfmskywalker** [comment] 2021-07-01 18:39
Hi Juan,

I ran into the exact same issue this afternoon. A fix has been pushed since, so if you update to the latest preview package then it should work for you too.

Let me know otherwise.

**Comment by sfmskywalker** [comment] 2021-07-04 19:40
Closing this issue assuming the issue is resolved. If not, please feel free to reopen. Thanks!

**Closed by sfmskywalker** 2021-07-04 19:40 UTC
