### ISSUE TITLE
 server restart problem

### ISSUE THREAD

**Issue by pandeygautamkumar** [elsa-workflows/elsa-core#4405] opened 2023-09-06 16:39 UTC
I have create one workflow with three HTTP Endpoint activities. first I trigger the first HTTP Endpoint after then stop the server again restart the server & try to trigger second Http Endpoint activity , but it is not triggered get 400 error . below is our workflow
![Screenshot (22)](https://github.com/elsa-workflows/elsa-core/assets/106687927/055392c0-a0c6-4687-87a2-f2c6b90ebd0f)

but Second Endpoint is stored in bookmark Table.
out sample workflow json file is bellow : -
{
  "$id": "1",
  "definitionId": "72b79f595ead40b4938bf80d2d08fc45",
  "versionId": "668204cb644b428cb11eb1c920f8a614",
  "name": "Sample",
  "displayName": "Sample",
  "channel": "",
  "version": 41,
  "variables": {
    "$id": "2",
    "data": {}
  },
  "customAttributes": {
    "$id": "3",
    "data": {}
  },
  "contextOptions": {
    "$id": "4",
    "contextFidelity": "Burst"
  },
  "isSingleton": false,
  "persistenceBehavior": "WorkflowBurst",
  "deleteCompletedInstances": false,
  "isPublished": false,
  "isLatest": true,
  "createdAt": "2023-09-06T14:40:12.8672412Z",
  "activities": [
    {
      "$id": "5",
      "activityId": "eb05dc54-de7c-479c-a676-6f64573508f6",
      "type": "HttpEndpoint",
      "displayName": "HTTP Endpoint 1",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "6",
          "name": "Path",
          "expressions": {
            "$id": "7",
            "Literal": "/Sample"
          }
        },
        {
          "$id": "8",
          "name": "Methods",
          "expressions": {
            "$id": "9",
            "Json": "[\"GET\"]"
          }
        },
        {
          "$id": "10",
          "name": "ReadContent",
          "expressions": {
            "$id": "11"
          }
        },
        {
          "$id": "12",
          "name": "TargetType",
          "expressions": {
            "$id": "13"
          }
        },
        {
          "$id": "14",
          "name": "Schema",
          "syntax": "Literal",
          "expressions": {
            "$id": "15",
            "Literal": ""
          }
        },
        {
          "$id": "16",
          "name": "Authorize",
          "expressions": {
            "$id": "17"
          }
        },
        {
          "$id": "18",
          "name": "Policy",
          "expressions": {
            "$id": "19"
          }
        }
      ],
      "propertyStorageProviders": {
        "$id": "20"
      }
    },
    {
      "$id": "21",
      "activityId": "e87b83be-d50d-4cc8-90ec-795d7fd4e7df",
      "type": "WriteHttpResponse",
      "displayName": "HTTP Response",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "22",
          "name": "Content",
          "expressions": {
            "$id": "23",
            "Literal": "Sample"
          }
        },
        {
          "$id": "24",
          "name": "ContentType",
          "expressions": {
            "$id": "25",
            "Literal": "text/plain"
          }
        },
        {
          "$id": "26",
          "name": "StatusCode",
          "expressions": {
            "$id": "27",
            "Literal": "OK"
          }
        },
        {
          "$id": "28",
          "name": "CharSet",
          "expressions": {
            "$id": "29",
            "Literal": "utf-8"
          }
        },
        {
          "$id": "30",
          "name": "ResponseHeaders",
          "expressions": {
            "$id": "31"
          }
        }
      ],
      "propertyStorageProviders": {
        "$id": "32"
      }
    },
    {
      "$id": "33",
      "activityId": "5ee8d223-5ec0-4a6c-8115-ef95ad556bbd",
      "type": "HttpEndpoint",
      "name": "EndPoint1",
      "displayName": "HTTP Endpoint 2",
      "persistWorkflow": true,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "34",
          "name": "Path",
          "expressions": {
            "$id": "35",
            "Literal": "/Sample2"
          }
        },
        {
          "$id": "36",
          "name": "Methods",
          "expressions": {
            "$id": "37",
            "Json": "[\"GET\"]"
          }
        },
        {
          "$id": "38",
          "name": "ReadContent",
          "expressions": {
            "$id": "39"
          }
        },
        {
          "$id": "40",
          "name": "TargetType",
          "expressions": {
            "$id": "41"
          }
        },
        {
          "$id": "42",
          "name": "Schema",
          "syntax": "Literal",
          "expressions": {
            "$id": "43",
            "Literal": ""
          }
        },
        {
          "$id": "44",
          "name": "Authorize",
          "expressions": {
            "$id": "45"
          }
        },
        {
          "$id": "46",
          "name": "Policy",
          "expressions": {
            "$id": "47"
          }
        }
      ],
      "propertyStorageProviders": {
        "$id": "48"
      }
    },
    {
      "$id": "49",
      "activityId": "ebae366f-b570-44f1-8842-6a1685426fe4",
      "type": "WriteHttpResponse",
      "displayName": "HTTP Response",
      "persistWorkflow": true,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "50",
          "name": "Content",
          "expressions": {
            "$id": "51",
            "Literal": "Sample2"
          }
        },
        {
          "$id": "52",
          "name": "ContentType",
          "expressions": {
            "$id": "53",
            "Literal": "text/plain"
          }
        },
        {
          "$id": "54",
          "name": "StatusCode",
          "expressions": {
            "$id": "55",
            "Literal": "OK"
          }
        },
        {
          "$id": "56",
          "name": "CharSet",
          "expressions": {
            "$id": "57",
            "Literal": "utf-8"
          }
        },
        {
          "$id": "58",
          "name": "ResponseHeaders",
          "expressions": {
            "$id": "59"
          }
        }
      ],
      "propertyStorageProviders": {
        "$id": "60"
      }
    },
    {
      "$id": "61",
      "activityId": "a457a166-27ab-4221-8b21-d6d9f1989aa3",
      "type": "HttpEndpoint",
      "name": "EndPoint2",
      "displayName": "HTTP Endpoint 2",
      "persistWorkflow": true,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "62",
          "name": "Path",
          "expressions": {
            "$id": "63",
            "Literal": "Sample3"
          }
        },
        {
          "$id": "64",
          "name": "Methods",
          "expressions": {
            "$id": "65",
            "Json": "[\"GET\"]"
          }
        },
        {
          "$id": "66",
          "name": "ReadContent",
          "expressions": {
            "$id": "67"
          }
        },
        {
          "$id": "68",
          "name": "TargetType",
          "expressions": {
            "$id": "69"
          }
        },
        {
          "$id": "70",
          "name": "Schema",
          "syntax": "Literal",
          "expressions": {
            "$id": "71",
            "Literal": ""
          }
        },
        {
          "$id": "72",
          "name": "Authorize",
          "expressions": {
            "$id": "73"
          }
        },
        {
          "$id": "74",
          "name": "Policy",
          "expressions": {
            "$id": "75"
          }
        }
      ],
      "propertyStorageProviders": {
        "$id": "76"
      }
    },
    {
      "$id": "77",
      "activityId": "0a20413f-73cf-4b0f-838b-b2e5127adbf9",
      "type": "WriteHttpResponse",
      "displayName": "HTTP Response",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "78",
          "name": "Content",
          "expressions": {
            "$id": "79",
            "Literal": "Sample3"
          }
        },
        {
          "$id": "80",
          "name": "ContentType",
          "expressions": {
            "$id": "81",
            "Literal": "text/plain"
          }
        },
        {
          "$id": "82",
          "name": "StatusCode",
          "expressions": {
            "$id": "83",
            "Literal": "OK"
          }
        },
        {
          "$id": "84",
          "name": "CharSet",
          "expressions": {
            "$id": "85",
            "Literal": "utf-8"
          }
        },
        {
          "$id": "86",
          "name": "ResponseHeaders",
          "expressions": {
            "$id": "87"
          }
        }
      ],
      "propertyStorageProviders": {
        "$id": "88"
      }
    }
  ],
  "connections": [
    {
      "$id": "89",
      "sourceActivityId": "ebae366f-b570-44f1-8842-6a1685426fe4",
      "targetActivityId": "a457a166-27ab-4221-8b21-d6d9f1989aa3",
      "outcome": "Done"
    },
    {
      "$id": "90",
      "sourceActivityId": "5ee8d223-5ec0-4a6c-8115-ef95ad556bbd",
      "targetActivityId": "ebae366f-b570-44f1-8842-6a1685426fe4",
      "outcome": "Done"
    },
    {
      "$id": "91",
      "sourceActivityId": "a457a166-27ab-4221-8b21-d6d9f1989aa3",
      "targetActivityId": "0a20413f-73cf-4b0f-838b-b2e5127adbf9",
      "outcome": "Done"
    },
    {
      "$id": "92",
      "sourceActivityId": "eb05dc54-de7c-479c-a676-6f64573508f6",
      "targetActivityId": "e87b83be-d50d-4cc8-90ec-795d7fd4e7df",
      "outcome": "Done"
    },
    {
      "$id": "93",
      "sourceActivityId": "e87b83be-d50d-4cc8-90ec-795d7fd4e7df",
      "targetActivityId": "5ee8d223-5ec0-4a6c-8115-ef95ad556bbd",
      "outcome": "Done"
    }
  ],
  "id": "668204cb644b428cb11eb1c920f8a614"
}

**Comment by sfmskywalker** [comment] 2023-09-07 21:08
Hello @pandeygautamkumar , I started to look into this issue, but when I try to import your workflow, the JSON serializer fails to deserialize due to an invalid JSON structure.

Can you please create a new export and attach it to this issue as a zipped file?

**Comment by pandeygautamkumar** [comment] 2023-09-08 05:28
[Sample_Workflow.zip](https://github.com/elsa-workflows/elsa-core/files/12555844/Sample_Workflow.zip)
as you asked here I'm attaching the zip folder 
ping if you need anything else

**Comment by sfmskywalker** [comment] 2023-09-09 10:44
Thanks @sfmskywalker for the workflow, I was able to reproduce the issue you reported and have just pushed a fix.

**Closed** 2023-09-09 10:43 UTC
Labels: bug, elsa 2
