### ISSUE TITLE
Serialization Exception on Composite Activity

### ISSUE THREAD

**Issue by michelveloso** [elsa-workflows/elsa-core#4466] opened 2023-09-21 19:48 UTC
Firstly, @sfmskywalker , congratulations on the project initiative!!

I am using elas v3 version, an exception occurred when I tried to serialize the Activity using Composite.

Below is an example of integration with OpenAI where the error occurs

/https://github.com/michelveloso/elsa-core-fork-01/blob/main/src/samples/console/Elsa.Samples.ConsoleApp.OpenAi/Program.cs

![image](https://github.com/elsa-workflows/elsa-core/assets/346317/c4fafd08-96dc-47dd-afec-120736d0cc27)

![image](https://github.com/elsa-workflows/elsa-core/assets/346317/6e51c326-c88b-4fa0-a0dc-14988d976f5d)

Error:
`System.NullReferenceException: Object reference not set to an instance of an object.`

**Comment by sfmskywalker** [comment] 2023-09-24 17:48
Hi @michelveloso 

Thank you for your appreciative words!

I checked out your fork and the sample project and was able to reproduce the issue you reported exactly.
Please replace line 69 in **Program.cs** with the following:

```csharp
services.AddElsa(elsa => elsa.AddActivitiesFrom<Program>());
```

In the meantime, I'll see if there's a way to allow the serializer to not require activity types to be registered with the activity registry, and, at the very least, provide a proper exception that there's an activity being referenced not present in the activity registry with instructions to get it registered.

**Comment by sfmskywalker** [comment] 2023-09-24 18:18
Upon further inspection, the reason for the exception was that the `IActivitySerializer` attempts to get an activity descriptor for the activities being serialized, in order to serialize any synthetic properties, if any.

When it comes to writing custom (composite or not) activities, I suspect not too many people may use these advanced features, in which case it's unnecessary to serialize synthetic properties (since there won't be any).

So, I made the the serializer more forgiving by simply skipping synthetic properties, but with a warning.
See eebb58e094b1b145e4c90b10c24885df7ea9bab5

**Comment by sfmskywalker** [comment] 2023-09-24 20:06
I'll close this issue as solved, but please feel free to reopen if you still think it's an issue!

**Closed by sfmskywalker** 2023-09-24 20:06 UTC
Labels: bug, elsa 3

**Comment by sfmskywalker** [comment] 2023-10-17 20:36
That's an interesting use case. When you import the JSON, would you expect it to basically run the C# workflow again, or would you expect to be able to delete the C# code and still run the workflow purely from JSON?

That scenario should work, except that it wouldn't know what to do with C# lambda expressions, since that code isn't copied into the JSON. Instead, right now you would have to replace the C# lambda expressions with JS expressions, which will be serialized as part of the JSON.

Out of curiosity: how are you exporting the C# workflow to JSON?
