### ISSUE TITLE
Elsa 2 - Designer - JavaScript Activity Editor property editor regression 

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#948] opened 2021-05-07 15:03 UTC
Version: 2.0.0-rc1.22
1. Create a workflow
2. Add a JavaScript activity to the editor
3. Open activity and check for Errors (breaks the blazer app till restart) 

![image](https://user-images.githubusercontent.com/1550939/117469242-67939580-af4d-11eb-8901-0945fcf98e11.png)

![image](https://user-images.githubusercontent.com/1550939/117469323-8134dd00-af4d-11eb-8ab8-657c578a7676.png)

n.opions is undefined:
![image](https://user-images.githubusercontent.com/1550939/117469492-b6d9c600-af4d-11eb-9dde-bb49a3e5ce33.png)

**Comment by sfmskywalker** [comment] 2021-05-10 14:13
Could not reproduce this with the latest packages on MyGet, so closing. Feel free to reopen if you do still see this issue. Thanks.

**Closed by sfmskywalker** 2021-05-10 14:13 UTC

**Comment by matt4446** [comment] 2021-05-10 14:44
This is working again. I had upgraded to rc1.36 a few minutes ago (not quite the latest) and no errors so far after checking.

**Comment by sfmskywalker** [comment] 2021-05-10 15:00
Sweet. Thanks for confirming!
