### ISSUE TITLE
Elsa 2 - Fast multiple signal bug

### ISSUE THREAD

**Issue by riatdyl** [elsa-workflows/elsa-core#992] opened 2021-05-17 09:27 UTC
Hello,

I used this guide to make a signal based workflow : https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-signaling-workflows

The problem is that if I run the workflow many times in a short amount of time, this is happening : 
![image](https://user-images.githubusercontent.com/43779018/118465806-8b4f9c00-b702-11eb-9ccc-7c48e84f882a.png)

**Comment by sfmskywalker** [comment] 2021-05-17 10:04
I can confirm. Not sure if it might have to do with quickly pressing F5 on the browser causing existing requests to be aborted (in which case it might be expected behavior), but I will try also with firing multiple simultaneous requests in parallel to see what happens.

**Comment by riatdyl** [comment] 2021-05-17 10:53
This is the lines I get in the console after pressing multiple times F5 : 
```console
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexing bookmarks
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexed 0 bookmarks in 00:00:00.0245471
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexing bookmarks
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexed 0 bookmarks in 00:00:00.0240409
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (0ms) [Parameters=[@__p_0='?' (Size = 32)], CommandType='Text', CommandTimeout='30']
      SELECT "w"."Id", "w"."ActivityId", "w"."ActivityType", "w"."Data", "w"."EventName", "w"."Message", "w"."Source", "w"."TenantId", "w"."Timestamp", "w"."WorkflowInstanceId"
      FROM "WorkflowExecutionLogRecords" AS "w"
      WHERE "w"."Id" = @__p_0
      LIMIT 1
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Elsa.Persistence.EntityFramework.Core.ElsaContext'.
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
fail: Microsoft.EntityFrameworkCore.Database.Transaction[20205]
      An error occurred using a transaction.
warn: Elsa.Services.WorkflowRunner[0]
      Failed to run workflow 43b646a0d1944937bb5d9c471f8016f9
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`1.<>c__DisplayClass6_0.<<SaveAsync>b__0>d.MoveNext() in C:\Users\a\Desktop\elsa-core-master\src\persistence\Elsa.Persistence.EntityFramework\Elsa.Persistence.EntityFramework.Core\Stores\EntityFrameworkStore.cs:line 38
      --- End of stack trace from previous location ---
         at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`1.DoWork(Func`2 work, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\persistence\Elsa.Persistence.EntityFramework\Elsa.Persistence.EntityFramework.Core\Stores\EntityFrameworkStore.cs:line 156
         at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`1.DoWork(Func`2 work, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\persistence\Elsa.Persistence.EntityFramework\Elsa.Persistence.EntityFramework.Core\Stores\EntityFrameworkStore.cs:line 157
         at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`1.SaveAsync(T entity, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\persistence\Elsa.Persistence.EntityFramework\Elsa.Persistence.EntityFramework.Core\Stores\EntityFrameworkStore.cs:line 35
         at Elsa.Services.WorkflowExecutionLog.AddEntryAsync(String workflowInstanceId, String activityId, String activityType, String eventName, String message, String tenantId, String source, JObject data, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowExecutionLog.cs:line 28
         at Elsa.WorkflowExecutionLogExtensions.AddEntryAsync(IWorkflowExecutionLog log, String eventName, WorkflowInstance workflowInstance, IActivityBlueprint activity, String message, JObject data, String source, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Abstractions\Extensions\WorkflowExecutionLogExtensions.cs:line 46
         at Elsa.WorkflowExecutionLogExtensions.AddEntryAsync(IWorkflowExecutionLog log, String eventName, WorkflowInstance workflowInstance, IActivityBlueprint activity, String message, Object data, String source, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Abstractions\Extensions\WorkflowExecutionLogExtensions.cs:line 37
         at Elsa.Handlers.WriteWorkflowExecutionLog.WriteEntryAsync(String eventName, String message, ActivityExecutionContext activityExecutionContext, Object data, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Handlers\WriteWorkflowExecutionLog.cs:line 60
         at Elsa.Handlers.WriteWorkflowExecutionLog.Handle(ActivityExecutionResultExecuted notification, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Handlers\WriteWorkflowExecutionLog.cs:line 40
         at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
         at Elsa.Services.WorkflowRunner.RunCoreAsync(WorkflowExecutionContext workflowExecutionContext, ActivityOperation activityOperation, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowRunner.cs:line 252
         at Elsa.Services.WorkflowRunner.RunAsync(WorkflowExecutionContext workflowExecutionContext, ActivityOperation activityOperation, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowRunner.cs:line 205
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Medallion.Threading.Internal.BusyWaitHelper.WaitAsync[TState,TResult](TState state, Func`3 tryGetValue, TimeoutValue timeout, TimeoutValue minSleepTime, TimeoutValue maxSleepTime, CancellationToken cancellationToken) in C:\Users\mikea_000\Documents\Interests\CS\DistributedLock\DistributedLock.Core\Internal\BusyWaitHelper.cs:line 44
         at Medallion.Threading.Internal.Helpers.Convert[TDerived,TBase](ValueTask`1 task, ValueTaskConversion _) in C:\Users\mikea_000\Documents\Interests\CS\DistributedLock\DistributedLock.Core\Internal\Helpers.cs:line 24
         at Elsa.Services.DistributedLockProvider.AcquireLockAsync(String name, Nullable`1 timeout, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\DistributedLockProvider.cs:line 28
         at Elsa.Services.WorkflowLaunchpad.CollectStartableWorkflowAsync(IWorkflowBlueprint workflowBlueprint, String activityId, String correlationId, String contextId, String tenantId, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowLaunchpad.cs:line 119
         at Elsa.Services.WorkflowLaunchpad.CollectStartableWorkflowAsync(IWorkflowBlueprint workflowBlueprint, String activityId, String correlationId, String contextId, String tenantId, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowLaunchpad.cs:line 149
         at Elsa.Services.WorkflowLaunchpad.CollectStartableWorkflowsAsync(CollectWorkflowsContext context, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowLaunchpad.cs:line 87
         at Elsa.Services.WorkflowLaunchpad.CollectResumableAndStartableWorkflowsAsync(CollectWorkflowsContext context, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowLaunchpad.cs:line 232
         at Elsa.Services.WorkflowLaunchpad.CollectWorkflowsAsync(CollectWorkflowsContext context, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowLaunchpad.cs:line 73
         at Open.Linq.AsyncExtensions.Extensions.ToList[TSource](Task`1 source)
         at Elsa.Activities.Http.Middleware.HttpEndpointMiddleware.InvokeAsync(HttpContext httpContext, IWorkflowLaunchpad workflowLaunchpad, IWorkflowInstanceStore workflowInstanceStore, IWorkflowRegistry workflowRegistry, IWorkflowBlueprintReflector workflowBlueprintReflector, IEnumerable`1 contentParsers) in C:\Users\a\Desktop\elsa-core-master\src\activities\Elsa.Activities.Http\Middleware\HttpRequestMiddleware.cs:line 45
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'Elsa.Persistence.EntityFramework.Core.ElsaContext'.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexing bookmarks
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexed 0 bookmarks in 00:00:00.1517049
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`1.DoWork(Func`2 work, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\persistence\Elsa.Persistence.EntityFramework\Elsa.Persistence.EntityFramework.Core\Stores\EntityFrameworkStore.cs:line 157
         at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`1.DoWork(Func`2 work, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\persistence\Elsa.Persistence.EntityFramework\Elsa.Persistence.EntityFramework.Core\Stores\EntityFrameworkStore.cs:line 157
         at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`1.SaveAsync(T entity, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\persistence\Elsa.Persistence.EntityFramework\Elsa.Persistence.EntityFramework.Core\Stores\EntityFrameworkStore.cs:line 35
         at Elsa.Persistence.Decorators.EventPublishingWorkflowInstanceStore.SaveAsync(WorkflowInstance entity, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Persistence\Decorators\EventPublishingWorkflowInstanceStore.cs:line 26
         at Elsa.Services.WorkflowLaunchpad.CollectStartableWorkflowAsync(IWorkflowBlueprint workflowBlueprint, String activityId, String correlationId, String contextId, String tenantId, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowLaunchpad.cs:line 141
         at Elsa.Services.WorkflowLaunchpad.CollectStartableWorkflowAsync(IWorkflowBlueprint workflowBlueprint, String activityId, String correlationId, String contextId, String tenantId, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowLaunchpad.cs:line 142
         at Elsa.Services.WorkflowLaunchpad.CollectStartableWorkflowAsync(IWorkflowBlueprint workflowBlueprint, String activityId, String correlationId, String contextId, String tenantId, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowLaunchpad.cs:line 149
         at Elsa.Services.WorkflowLaunchpad.CollectStartableWorkflowsAsync(CollectWorkflowsContext context, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowLaunchpad.cs:line 87
         at Elsa.Services.WorkflowLaunchpad.CollectResumableAndStartableWorkflowsAsync(CollectWorkflowsContext context, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowLaunchpad.cs:line 232
         at Elsa.Services.WorkflowLaunchpad.CollectWorkflowsAsync(CollectWorkflowsContext context, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowLaunchpad.cs:line 73
         at Open.Linq.AsyncExtensions.Extensions.ToList[TSource](Task`1 source)
         at Elsa.Activities.Http.Middleware.HttpEndpointMiddleware.InvokeAsync(HttpContext httpContext, IWorkflowLaunchpad workflowLaunchpad, IWorkflowInstanceStore workflowInstanceStore, IWorkflowRegistry workflowRegistry, IWorkflowBlueprintReflector workflowBlueprintReflector, IEnumerable`1 contentParsers) in C:\Users\a\Desktop\elsa-core-master\src\activities\Elsa.Activities.Http\Middleware\HttpRequestMiddleware.cs:line 45
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexing bookmarks
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`1.SaveAsync(T entity, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\persistence\Elsa.Persistence.EntityFramework\Elsa.Persistence.EntityFramework.Core\Stores\EntityFrameworkStore.cs:line 31
         at Elsa.Persistence.Decorators.EventPublishingWorkflowInstanceStore.SaveAsync(WorkflowInstance entity, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Persistence\Decorators\EventPublishingWorkflowInstanceStore.cs:line 26
         at Elsa.Handlers.PersistWorkflow.SaveWorkflowAsync(WorkflowExecutionContext workflowExecutionContext, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Handlers\PersistWorkflow.cs:line 109
         at Elsa.Handlers.PersistWorkflow.Handle(WorkflowExecuted notification, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Handlers\PersistWorkflow.cs:line 68
         at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
         at Elsa.Services.WorkflowRunner.RunWorkflowAsync(IWorkflowBlueprint workflowBlueprint, WorkflowInstance workflowInstance, String activityId, Object input, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowRunner.cs:line 116
         at Elsa.Decorators.LockingWorkflowRunner.RunWorkflowAsync(IWorkflowBlueprint workflowBlueprint, WorkflowInstance workflowInstance, String activityId, Object input, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Decorators\LockingWorkflowRunner.cs:line 40
         at Elsa.Decorators.LockingWorkflowRunner.RunWorkflowAsync(IWorkflowBlueprint workflowBlueprint, WorkflowInstance workflowInstance, String activityId, Object input, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Decorators\LockingWorkflowRunner.cs:line 42
         at Elsa.Services.WorkflowResumer.ResumeWorkflowAsync(WorkflowInstance workflowInstance, String activityId, Object input, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowResumer.cs:line 79
         at Elsa.Services.WorkflowInstanceExecutor.ExecuteAsync(WorkflowInstance workflowInstance, String activityId, Object input, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowInstanceExecutor.cs:line 39
         at Elsa.Services.WorkflowInstanceExecutor.ExecuteAsync(String workflowInstanceId, String activityId, Object input, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowInstanceExecutor.cs:line 31
         at Elsa.Services.WorkflowLaunchpad.ExecutePendingWorkflowsAsync(IEnumerable`1 pendingWorkflows, Object input, CancellationToken cancellationToken) in C:\Users\a\Desktop\elsa-core-master\src\core\Elsa.Core\Services\WorkflowLaunchpad.cs:line 186
         at Elsa.Activities.Http.Middleware.HttpEndpointMiddleware.InvokeAsync(HttpContext httpContext, IWorkflowLaunchpad workflowLaunchpad, IWorkflowInstanceStore workflowInstanceStore, IWorkflowRegistry workflowRegistry, IWorkflowBlueprintReflector workflowBlueprintReflector, IEnumerable`1 contentParsers) in C:\Users\a\Desktop\elsa-core-master\src\activities\Elsa.Activities.Http\Middleware\HttpRequestMiddleware.cs:line 81
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexed 0 bookmarks in 00:00:00.0906634
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexing bookmarks
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexed 0 bookmarks in 00:00:00.0335967
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexing bookmarks
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexed 0 bookmarks in 00:00:00.0278139
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexing bookmarks
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexed 0 bookmarks in 00:00:00.0291601
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexing bookmarks
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexed 0 bookmarks in 00:00:00.0295681
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexing bookmarks
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexed 0 bookmarks in 00:00:00.0301256
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexing bookmarks
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexed 0 bookmarks in 00:00:00.0385427
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexing bookmarks
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexed 0 bookmarks in 00:00:00.0309729
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexing bookmarks
info: Elsa.Bookmarks.BookmarkIndexer[0]
      Indexed 0 bookmarks in 00:00:00.0311708
```

**Comment by sfmskywalker** [comment] 2021-05-17 11:17
Just pushed a fix. The root issue was that the `HttpEndpointMiddleware` component used the `RequestAborted` cancellation token throughout the request.

Although this would perhaps be less of an issue when the HTTP client (e.g. web browser) cancels the request (e.g. because of refreshing the page using F5), it is also caused when one does a `HttpResponse.WriteAsync()` - which happens mid-way if a workflow executes the `WriteHttpResponse` activity.

To workaround this issue, I am no longer listening to the RequestAborted cancellation token.
I think this is fine, but if we do for some reason need the ability to cancel an ongoing HTTP request, we would have to change the implementation of `WriteHttpResponse` to ensure it only actually writes to the HTTP response stream AFTER workflow execution completes entirely. Doable, but a little bit more involved.

**Closed by sfmskywalker** 2021-05-17 11:17 UTC
Labels: bug, prio high
