### ISSUE TITLE
Retention policy options for workflow statuses

### ISSUE THREAD

**Issue by tsoG2000** [elsa-workflows/elsa-core#2743] opened 2022-02-10 12:47 UTC
Retention deletes all workflows except suspended ones. Retention should not delete faulted workflows, they should be in DB waiting for retry (some service was down in time of execution) and should always have finished status in the end or in very rare situation handled case by case scenario but never deleted without detailed inspection (if N retries failed). 
Also retention policy should consider there are parent and child workflows.

services.AddRetentionServices(options =>
            {
                options.SweepInterval = Duration.FromHours(2);
                options.TimeToLive = Duration.FromHours(1); 
                options.PageSize = 1000; 
            });

Perhaps there might be an option for whitelist/blacklist workflow statuses that are eligible for deletion.

**Comment by sfmskywalker** [comment] 2022-03-03 13:05
Makes sense. Even better, we should allow the application to apply custom logic to determine if a workflow instance needs to be removed or not.

This could be done using a simple "pipeline" of filters that can be implemented. For example, we could have the following filter interface:

```csharp
interface IRetentionFilter
{
   ValueTask<bool> GetShouldDeleteAsync(CleanupContext context);
}
```

Then out of the box we'd provide the following filter:

```csharp
class WorkflowStatusFilter : IRetentionFilter
{
   WorkflowStatusFilter(params WorkflowStatus[] Statuses);

   ValueTask<bool> GetShouldDeleteAsync(CleanupContext context)
   {
      var status = context.WorkflowInstance.WorkflowStatus;
      return Statuses.Contains(status);
   }
}
```

The application would then configure the filter pipeline like this:

```csharp
services.AddRetentionServices(options => options.ConfigurePipeline(pipeline => pipeline.Use(new WorkflowStatusFilter(WorkflowStatus.Finished, WorkflowStatus.Cancelled))));
```

But imagine an application does want to also consider faulted workflows that failed due to a specific reason. With the filter pipeline, you can create a custom filter and add it:

```csharp
services.AddRetentionServices(options => options.ConfigurePipeline(pipeline => pipeline
   .Use<WorkflowStatusFilter>() // Will instantiate a default status filter using e.g. Finished and Cancelled values.
   .Use<MyFaultedWorkflowFilter>() // Instantiates a custom filter that only considers faulted workflows that failed for a specific reason.
  // Add more filters as appropriate
));
```

One important aspect of the filter pipeline is that the more specific rules should appear first, because the cleanup service will consider the workflow for deletion as soon as the currently executing filter returns `true`.

**Comment by sfmskywalker** [comment] 2022-03-03 20:41
For the scenario where we don't want to delete "child" workflow instances, we would first have to determine what a child workflow is. As it stands right now, Elsa does not have a notion of parent/child workflow relationships, despite the fact that the **Run Workflow** activity starts another workflow and is treated by *it* as a child, the engine itself is unaware of this relationship.

One thing we could do is update the **Run Workflow** activity to store its created child workflow instance IDs in its workflow instance's metadata. Then there could be a retention filter that checks for the existence of this metadata (e.g. "child-workflows"), and if it exists, get the statuses of each child workflow and determine if they are eligible for deletion or not (reusing the retention filter pipeline).

I consider this out of scope for this issue, but we can certainly create a separate issue for this if there's any demand.

**Closed** 2022-03-10 07:42 UTC
Labels: bug, prio high

**Comment by sfmskywalker** [comment] 2023-08-24 11:23
Hi @jayachandra21,

Thank you for reaching out and providing detailed information about your configuration.

At the moment, due to other pressing priorities, I'm unable to delve deep into this issue personally. However, I'd recommend cloning the project and debugging the issue on your end. This might give you a clearer insight into what's happening and potentially lead to a quicker resolution.

Additionally, it would be helpful if you could open a separate issue dedicated to this problem. When doing so, please provide steps to reproduce the issue in an isolated Elsa project. This will make it easier for the community and other contributors to assist and potentially find a solution.

I understand this might not be the ideal response you were hoping for, but I believe this approach might be the most efficient way to address the issue given the circumstances. If you do find a solution or need further assistance, please don't hesitate to share or ask.
