### ISSUE TITLE
Http Request run Asynchronously but the workflow got suspended and never return the result

### ISSUE THREAD

**Issue by jordanpedro** [elsa-workflows/elsa-core#4737] opened 2024-01-02 13:34 UTC
Hi, im starting to use Elsa v3 ( i got previous experience with elsa 2.13) and there is something that i have not figured out yet. When i use multiple httprequest  Asynchronously( i selected the option run Asynchronously in each http activity ) and try to wait for the result of them all, the workflow got a suspended status and i have not been able to get the result of these multiples http calls   

im wondering if it`s a bug or something that im doing wrong. can someone give some help ?

Workflow : 
[http-async-calls.json](https://github.com/elsa-workflows/elsa-core/files/13810397/http-async-calls.json)

![image](https://github.com/elsa-workflows/elsa-core/assets/5852880/b23b7a8b-d2d9-428d-8955-687a23269e1b)

**Comment by sfmskywalker** [comment] 2024-01-02 14:05
I can reproduce this behaviour. Investigating.

**Comment by sfmskywalker** [comment] 2024-01-02 14:57
I think that the issue is with synchronising workflow state back from the background job executing the activity, where one version overwrites the other. Will fix.

**Comment by sfmskywalker** [comment] 2024-01-06 09:47
Fixed via 7c632a5b5529df2d61b3a1e8187dd069ad09323f

**Closed by sfmskywalker** 2024-01-06 09:47 UTC
Labels: elsa 3

**Comment by jordanpedro** [comment] 2024-01-07 12:29
Hi, i believe The Problem now is that the next activity after the multiple Async http calls never gets executed
[http-async-calls (2).json](https://github.com/elsa-workflows/elsa-core/files/13853404/http-async-calls.2.json)

![image](https://github.com/elsa-workflows/elsa-core/assets/5852880/bebc5f34-b929-4d9c-b61b-e4305b9123e0)

and also the activity Http Request (Flow) still has the suspendend problem that i mentioned in the title of the issue.

[http-flow-async-calls.json](https://github.com/elsa-workflows/elsa-core/files/13853415/http-flow-async-calls.json)

![image](https://github.com/elsa-workflows/elsa-core/assets/5852880/b5d83add-a426-41cc-85c8-83560f2a7c68)
