### ISSUE TITLE
"Input" is the property of  workflowinstance,but it is empty in database

### ISSUE THREAD

**Issue by 1402524470** [elsa-workflows/elsa-core#331] opened 2020-06-17 03:38 UTC
Hello ,I want to Use  "Input",but the property is Empty in database.I find the code of Method 【ToWorkflowInstance】.That Method does not Map. so the empty object inserted into database.
Is It a code bug？I appreciate to receive your reply，thanks

**Comment by sfmskywalker** [comment] 2020-06-23 18:11
Hi @1402524470 , can you please provide me with a simple console project demonstrating this issue?

**Comment by 1402524470** [comment] 2020-07-07 09:33
```
 var workflowInstance = await _workflowInstanceStore.GetByIdAsync(instance.Id, cancellationToken);
var input = workflowInstance.Input;
```
the value of  "input" is null, but  it had a value when i use the workflow ,it not be saved in the database. however,the Input property is created in database.the elsa  is not use the property . i look up the elsa source code ,That Method of "ToWorkflowInstance" does not Map the input property

**Comment by sfmskywalker** [comment] 2020-07-07 10:36
That does indeed sound like a bug. Please feel free to send a PR. Alternatively, I’ll fix it soon as I can. Thanks!

**Comment by brightermatter** [comment] 2020-08-26 14:29
Hi @sfmskywalker, Thank your for your efforts. Do you have any update on this bug?

**Comment by sfmskywalker** [comment] 2021-03-12 12:36
In Elsa 2, "input" supplied while starting or resuming a workflow is no longer persisted _automatically_. Here are some questions to consider when thinking of the scenario where we actually do persist the input when starting a workflow but now also start resuming the workflow with new input:

1. Should it overwrite the stored input?
2. Should we simply not persist input that is received when resuming a workflow instance?
3. Or perhaps the initially received input is to be conceptually regarded differently than input received when resuming a workflow?
4. Should the workflow input be associated with the activity being invoked instead? If so, what if multiple activities were scheduled as starting activities?

These are some interesting questions to which I don't have a clear answer at this point. For that reason, I think it's more practical to leave it up to the workflow developer to decide what to do with input. You want to ignore it? Then nothing to do. Want to persist it? Then set a workflow variable. This allows the developer to choose the appropriate thing to do in any given situation.

As always, I'm happy to hear other thoughts.

**Comment by sfmskywalker** [comment] 2021-03-12 12:38
As outlined in my previous comment, input not being stored in Elsa 2 is not a bug, but a design choice. Although this behavior was intended differently in Elsa 1, I am going to close this issue with the advice to use the `SetVariable` activity to persist workflow input.

**Closed by sfmskywalker** 2021-03-12 12:38 UTC
Labels: bug, prio low

**Comment by sfmskywalker** [comment] 2021-03-12 12:39
PS: It looks like the bug was actually fixed, so for Elsa 1 input does get stored. Just keep in mind this won't be the case for Elsa 2 at the time of this writing at least.
