### ISSUE TITLE
Timer Activity - Timer Trigger Issue 

### ISSUE THREAD

**Issue by jayachandra21** [elsa-workflows/elsa-core#1116] opened 2021-06-10 14:58 UTC
Hello @sfmskywalker,

I am facing an issue with timer activity in the workflow for elsa 1.4.3. Below is the configuration for timer settings:
- SweepInterval is configured for 1 min. Refer below snap.
![AppConfig_sweepInterval](https://user-images.githubusercontent.com/67507118/121537214-67832b80-ca0c-11eb-8941-00f4feb07157.png)
- Timer event timeout expression configured as 1 min. Refer below snap.
![TimerActivityConfiguration](https://user-images.githubusercontent.com/67507118/121537600-bcbf3d00-ca0c-11eb-946a-7b4197a6c93f.png)

Now the workflow is supposed to execute after every one min but taking almost 20 mins to trigger.
Below is snap of finished workflows where the timer event Timeout expression is configured as **1 min**.

Example:  In the below screenshot, the second record shows the Workflow started at **2021-06-09 12:46:54** and ended at **2021-06-09 13:01:54**

![WorkflowInstances](https://user-images.githubusercontent.com/67507118/121537862-fabc6100-ca0c-11eb-8586-66f3b37700a3.png)

One more strange behavior I noticed is when I check the execution Log,
![ExecutionLog](https://user-images.githubusercontent.com/67507118/121538880-d1500500-ca0d-11eb-8a0c-352297bff458.png)

The Workflow started at 2021-06-09 12:46:54 But execution log shows it started at 2021-06-09 12:56:22 and waited till 2021-06-09 13:02:56  to and execution completed 2021-06-09 13:02:54  where in it was expected to start at 2021-06-09 12:46:54.

Can you help me with some information as to why a particular Workflow is getting additional delays.

**Comment by sfmskywalker** [comment] 2021-06-14 09:27
It's hard to say what's causing this. Given a sweep interval of 1 minute, Elsa should trigger timer events configured with a timeout of 1 minute at least every 2 minutes (in case it was a fraction of a moment too early when evaluating the timeout expression).

What you can do is set a breakpoint in the background task that performs the sweep, and also a breakpoint where Elsa tries to determine if it is time to trigger the activity.

**Comment by sfmskywalker** [comment] 2021-06-14 09:30
Although I can't seem to reproduce the issue with a clean project, I strongly encourage you to migrate to Elsa 2, which fixes many issues and has a much stronger implementation for timer events thanks to the use of Quartz.NET.

**Comment by sfmskywalker** [comment] 2021-06-19 18:25
As mentioned by @jayachandra21 on Gitter, the cause of the delayed execution turns out to be slow-performing workflows when triggering them and/or while running these workflows.

Closing this issue since OP discovered the underlying cause of the observed delays, which are caused by a poor performing Elsa 1.

**Closed by sfmskywalker** 2021-06-19 18:25 UTC
Labels: elsa 1, wontfix
