### ISSUE TITLE
[BUG] Cannot import serialized samples to elsa studio?

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [elsa-workflows/elsa-core#5881] opened 2024-08-10 06:58 UTC
## Description
I'm trying to import one of the Elsa samples into Elsa Studio and test it on my local Elsa server. Specifically, I attempted to serialize the `Elsa.Samples.AspNet.DocumentApproval` sample to a JSON file using the following code:

```csharp
protected override async ValueTask AfterBuildAsync(IWorkflowBuilder builder, CancellationToken cancellationToken = default)
{
    await base.AfterBuildAsync(builder, cancellationToken);
    var vv = await builder.BuildWorkflowAsync();
    var json = _WorkflowSerializer.Serialize(vv);
}
```

I saved the resulting JSON to a file and then tried to import it into Elsa Studio version 3.2, which I have running on Docker. However, the designer does not display the workflow correctly, and it seems to have a bug.

## Steps to Reproduce
1. **Detailed Steps**:
    - Use the above code snippet to serialize the `Elsa.Samples.AspNet.DocumentApproval` workflow into a JSON file.
    - Save the JSON output to a file.
    - Run Elsa Studio version 3.2 on Docker.
    - Attempt to import the saved JSON file into Elsa Studio.
    - Observe the issues in the designer.

2. **Code Snippets**:
    - The code snippet provided in the **Description** section demonstrates how the JSON file was generated.

3. **Attachments**:
   - **Workflow JSON**: The JSON file generated from the code.
   - **Sample Project**: The `Elsa.Samples.AspNet.DocumentApproval` sample.
   - [workflowexample.json](https://github.com/user-attachments/files/16568765/workflowexample.json)

4. **Reproduction Rate**: The issue occurs every time the steps are followed.

5. **Video/Screenshots**: If needed, I can provide screenshots or a video of the import process and the resulting designer view.
![image](https://github.com/user-attachments/assets/df1417dd-4721-4ed3-bfbe-ced50fcaba80)

6. **Additional Configuration**:
   - The issue occurs with Elsa Studio version 3.2 running on Docker.

## Expected Behavior
The imported JSON file should correctly display the workflow in the Elsa Studio designer.

## Actual Behavior
The designer does not render the workflow correctly and seems to have a bug.

## Screenshots
If needed, I can provide screenshots showing the incorrect rendering in the Elsa Studio designer.

## Environment
- **Elsa Package Version**: Using Elsa Studio version 3.2.
- **Operating System**: Docker running on  Windows 10.
- **Browser and Version**: If applicable, mention the browser and version used to access Elsa Studio (e.g., Chrome 127).

## Log Output
If necessary, I can provide log output or error messages from Elsa Studio or the Elsa server that might help diagnose the issue.

## Troubleshooting Attempts
I've tried checking the JSON file for any obvious issues, and I've ensured that the Elsa Studio and server are correctly configured.

## Additional Context
I'm wondering if there is another method for importing Elsa samples from the source code that could allow me to view the workflow in the designer correctly. I want to understand which objects are being used in the designer.

## Related Issues
N/A

---

**Comment by sfmskywalker** [comment] 2024-08-12 08:54
Hi @Ali-YousefiTelori , this is actually expected behavior. The workflow from the sample project is a **Sequence** activity, for which the designer has currently no support. When the designer encounters an activity for which it has no support, it uses a fallback component that simply displays the activity.

At the moment, the designer only supports designing **Flowchart** activities.
I will close this issue as "by design", but please feel free to continue the conversation.

**Closed by sfmskywalker** 2024-08-12 08:54 UTC
Labels: bug
