### ISSUE TITLE
Server shutdown recovery

### ISSUE THREAD

**Issue by valsov** [elsa-workflows/elsa-core#1182] opened 2021-06-28 07:44 UTC
When the server hosting Elsa is shutdown while a workflow instance is running, during the restart of the server, the system discovers that a workflow instance is indeed running and thus resumes it (that's the console output provided by Elsa).
The problem is that the instance doesn't resume as expected. The activities don't run but the instance is flagged as executed in the database.
The activities should resume where they stopped, restarting the last activity if it didn't complete, else the next one (?).

My Sample workflow is:
1. HTTP endpoint (maybe this is the problem, but this shouldn't be executed because the workflow instance stopped at the 2nd step)
2. Some long process writing to the console
3. A decision
4. Logging

I didn't see documentation about workflows recovery, maybe there is ?

**Comment by sfmskywalker** [comment] 2021-06-28 08:53
When you say: "the instance doesn't resume as expected", do you mean that the instance does not resume, which is something you would have expected, or: the instances did resume, but in a different manner than what I expected? If the latter, could you elaborate on this point?

I've executed many workflows where I stopped execution mid-stream by stopping the application. After restarting the application, the unfinished workflows got picked up and resumed. So maybe there is something specific about your workflow that I missed. If you can provide me with a sample project containing a workflow that does not resume (as expected), then that would be mighty helpful.

There's no documentation yet about workflow recovery, but I will scaffold a page with that topic to be filled out :+1:.

**Comment by valsov** [comment] 2021-06-28 11:05
Thank you for your help.
I meant to say the instance is said to be resumed by ELsa (written in console by Elsa server), but the activities aren't executed.
Here is the sample project to help : [https://github.com/valsov/Sample-elsa](url)
You will find a json file to import in order to create the workflow.

The moment to shutdown the server is suring the "LongRunningProc" activity execution. On restart, it should be executed again.

**Comment by DavidPx** [comment] 2021-06-29 21:52
Funny, I just ran into this similar behavior.

My persisted workflow has a single step, this activity:

```
public class SlowActivity : Activity
{
    protected override async ValueTask<IActivityExecutionResult> OnExecuteAsync(ActivityExecutionContext context)
    {
        Console.WriteLine($"Starting my slow task.. {context.WorkflowInstance.Id}.{context.ActivityId}.  {DateTime.Now.TimeOfDay}");

        await Task.Delay(10000);

        Console.WriteLine($"Phew, I finished!  {context.WorkflowInstance.Id}. {context.ActivityId}.  {DateTime.Now.TimeOfDay}");

        return Done();
    }
}
```

During a normal run the console looks like this:
```
info: Elsa.Bookmarks.BookmarkIndexer[0]                                               
      Indexed 0 bookmarks in 00:00:00.0447259                                         
Starting my slow task.. 1922e6fa9a3047aabbfb14239f2926da.activity-1.  16:48:46.4455681
Phew, I finished!  1922e6fa9a3047aabbfb14239f2926da. activity-1.  16:48:56.4616438    
info: Elsa.Bookmarks.BookmarkIndexer[0]                                               
      Indexing bookmarks                                                              
```

If I kill the console while it is thread.sleeping no runnable workflows are detected when I re-start it.  The execution log for the terminated workflow instance looks like this:

```
{
    "items": [
        {
            "tenantId": null,
            "workflowInstanceId": "09848e92619a45feb8fb1ea052f1ea48",
            "activityId": "activity-1",
            "activityType": "SlowActivity",
            "timestamp": "2021-06-29T21:49:52.566834Z",
            "eventName": "Executing",
            "message": null,
            "source": "SlowActivityWorkflow.cs:11",
            "data": {
                "Input": null,
                "State": {
                    "_Lifecycle": {
                        "$id": "1",
                        "Executing": true,
                        "Executed": false
                    }
                }
            },
            "id": "3e59cac4791a4fafa07a35224e678418"
        }
    ],
    "page": null,
    "pageSize": null,
    "totalCount": 1
}
```

P.S.  By running the same activity twice in the workflow (StartsWith, Then) I am able to duplicate the behavior where upon resumption the runnable instance is found but then nothing happens.

**Comment by DavidPx** [comment] 2021-07-01 14:50
I added a [repro case](https://github.com/DavidPx/elsa-core/blob/interrupted-repo/src/samples/aspnet/Elsa.Samples.InterruptedActivity/SlowActivityWorkflow.cs) to the Elsa solution and debugged into to where the activity is being passed over... WorkflowRunner, line 227.

The workflow instance has a CurrentActivity but no ScheduledActivities.  In the call stack leading to the WorkflowRunner there is some "or" logic that considers both Current and Scheduled activities, but at this point only scheduled ones are considered.  Is this the issue?

![image](https://user-images.githubusercontent.com/6942673/124144011-35844880-da51-11eb-9950-c611837fb30d.png)

**Comment by sfmskywalker** [comment] 2021-07-03 19:51
Thanks for the detailed observations, that was tremendously helpful!

As it turns out, the issue you are seeing is because when the workflow begins executing, the created workflow instance is persisted into the database with the "Idle" status, while the "resume running workflows" startup task only looks for workflow instances in the "Running" state (which would be an indication that a node has suddenly stopped).

For this reason, it is possible to configure exactly when and how often the workflow runner should persist the workflow instance.
By default, this happens as little as possible to increase workflow throughput, but at the cost of reliability in terms of recovery (as you have observed). This is suitable for most workflows that have suspension points (where the workflow would automatically get persisted), but not for all workflows, as in your example.

In your example, you want to make sure the workflow gets persisted right before the slow poke activity begins execution, so that in the event of the node gets shut down, the workflow runner will pick up at that activity.

One way to do is is by changing the workflow **persistence behavior** to **Activity Executed** (but there's a bug here related to what @DavidPx observed - I will get into that in a second) .
With this setting, the workflow will be persisted every time an activity finished execution.

A potential downside of that strategy is increased database writes, which impacts workflow throughput. This may or may not be a problem, but if it is, the next best thing is to configure specific activities to instruct the engine to persist the workflow instance once that activity finishes execution.

For example, if we take @valsov 's sample workflow, we can check the first **Write Line** activity's **Save Workflow Instance** field:

![image](https://user-images.githubusercontent.com/938393/124365407-13085000-dc48-11eb-8bbe-07fffe07ddc5.png)

That will actually work (no bugs here) - with that enabled, you can start the workflow, let it run until the **Long running process** activity executes for a short while, kill the server, start the server again, and observe that the workflow engine picks up where it left off. It will of course begin at the start of the `for` loop with index 0, but you can of course store the current index in the activity's state itself (simply by creating a property and updating it, and persist the workflow instance after every iteration (or however often you want this persisted).

Regarding the bug with the **Activity Executed** strategy for the **persistence behavior** setting, the issue here is that the engine only persists the currently executing activity at the time, which is the first Write Line activity, and it does not persist the scheduled activities (which is an empty stack because the scheduled long running process activity was already popped from it).

I will look into this and push a fix.

**Comment by sfmskywalker** [comment] 2021-07-03 20:02
Should be fixed with c00585241eca96c0b8a8cc8466c5929f3522f569, but please reopen if you can still reproduce the issue. Thanks!

**Comment by DavidPx** [comment] 2021-07-12 15:13
In a contrived example I was able to reproduce the bug.  If the process is killed during the very first activity the runnable state is not persisted.  I think that most workflows will have setup-style tasks at the top so while this isn't a likely scenario it's still bug-ish.

```
    public class SlowActivityWorkflow : IWorkflow
    {
        public void Build(IWorkflowBuilder builder)
        {
            builder
                .WithPersistenceBehavior(Models.WorkflowPersistenceBehavior.WorkflowPassCompleted)
                .WriteLine(x => "foo") // dummy activity to coerce persistence
                .Then<SlowActivity>(x => x.WithId("number1")) // If the process is stopped during this activity, number1 will be resumed
                .Then<SlowActivity>(x => x.WithId("number2"));

            //builder
            //    .WithPersistenceBehavior(Models.WorkflowPersistenceBehavior.WorkflowPassCompleted)
            //    .StartWith<SlowActivity>(x => x.WithId("number1")) // When the process is killed during this activity no runnable tasks are found
            //    .Then<SlowActivity>(x => x.WithId("number2"));
        }
    }
```

[Code is here](https://github.com/DavidPx/elsa-core/blob/interrupted-repo/src/samples/aspnet/Elsa.Samples.InterruptedActivity/SlowActivityWorkflow.cs)

**Comment by DavidPx** [comment] 2021-07-13 14:52
@valsov could you please re-open so that Sipke can take a look at this?

**Comment by valsov** [comment] 2021-07-13 15:07
Here you go

**Comment by sfmskywalker** [comment] 2021-07-14 11:32
@DavidPx 

I see. So this would be expected, depending on how you execute the workflow. For example, if you use the `IBuildsAndStartsWorkflow` service to build and start a new workflow, the workflow instance will be created in memory before executing and will not get a chance to persist.

If, on the other hand, you create **and persist** the workflow beforehand, then the expectation should indeed be for the workflow to be picked up. Except for the little fact that creating a new workflow instance will have a default status of `Idle`, while the `ContinueRunningWorkflows` task only looks for instances with the `Running` status.

The `IWorkflowLaunchpad` does pre-create **and persist** Idle workflows before they get executed, so that's something.
We could update `WorkflowStarter` (which implements `IBuildsAndStartsWorkflow`) to also do this, but not all workflows require workflow instances to be persisted. In fact, there are users who are interested only in quick executing short-running workflows. You could the higher-level service `IStartsWorkflow` instead, which does exactly that: instantiate a workflow instance, persist it, then execute it.

Here's what I think we should do:

- Update `WorkflowInstanceExecutor` to change workflow status from `Idle` to `Running` and persist this change **before executing** - this will ensure the `ContinueRunningWorkflows` startup task will pick it up if the node got killed before the workflow instance was persisted.

**Comment by sfmskywalker** [comment] 2021-07-14 11:59
I started to look into making this change, but it's going to be tricky to set the status from `Idle` to `Running` because the `IWorkflowRunner` service does some initial work when the status is `Idle`. Which means if we feed it a workflow that's `Running`, it will skip this initial work.

I'll look into the `ContinueRunningWorkflows` startup tasks instead to see what it would take for it to also pickup `Idle` workflows.

**Comment by sfmskywalker** [comment] 2021-07-14 12:11
I can make that work, but there's a different issue: what if the workflow that was started received some input? This input isn't persisted anywhere.

Although we could implement a storage provider for workflow input like we did for activity input & output properties, maybe we need to look at this issue differently.

When an application is about to perform something, whether it's a workflow execution or even just invoking an API endpoint, if it is critical that this succeeds even in the event of a node shutdown, the appropriate way is to schedule this work on a queue.

This way, if the worker node crashed, the message will still be in the queue ready to be picked up by another worker.

Similarly, if it is critical that a start workflow call succeeds, maybe you should do it from a queue worker. You could do this using `IWorkflowDispatcher`, which will schedule the work on a queue in the form of a message. If the node crashes after the message was delivered to the queue, then another worker will pick it up.

Thoughts?

**Comment by DavidPx** [comment] 2021-07-14 13:03
From the perspective of an Elsa user, I would see the database persistence option giving me a durable queue.  I wouldn't want to have to use/configure a separate queueing mechanism apart from Elsa.

It sounds like there are some edge cases around this bug report, it's good that some of them have been documented.  I would be OK with this not being fixed for the next release.  

A solution that comes to mind would be to work off of the WorkflowPersistenceBehavior enum to give users the option of super-durable, yet slower persistence behavior.  

Thank you for your attention on this one!

**Comment by sfmskywalker** [comment] 2021-07-14 15:29
> From the perspective of an Elsa user, I would see the database persistence option giving me a durable queue. I wouldn't want to have to use/configure a separate queueing mechanism apart from Elsa.

Good point, you're right.

Looks like I just gotta bite the bullet and serialize workflow input as well. Today, input can be any type of non-serializable object, but this will have to be changed. Which doesn't need to be a too big a deal. If someone wanted to say pass in a big file, they'd simply need to store it somewhere first and then pass e.g. a filename as input. The workflow can then load the file in memory so it can process it.

I'll create a separate issue for that for the 2.2 milestone and link it to this one.

> A solution that comes to mind would be to work off of the WorkflowPersistenceBehavior enum to give users the option of super-durable, yet slower persistence behavior.

I'll keep that in mind should I find the need to update the `WorkflowRunner` in some way to persist workflow status changes.

Thanks for thinking with!

**Closed** 2021-07-22 20:13 UTC
Labels: bug, prio high

**Comment by dwevedivaibhav** [comment] 2022-11-21 08:52
> 

Hi @sfmskywalker ,

How can i persist the workflow instance after every iteration (or however often want this persisted). as you mentioned we can persistence the workflow in every iteration in activity.
Can you please provide the some one line example for code how we can achieve that?

Thanks
