### ISSUE TITLE
Open Suspended instance

### ISSUE THREAD

**Issue by avhovsepyan** [elsa-workflows/elsa-core#5138] opened 2024-03-26 15:20 UTC
I have a problem. It isn't possible to open Suspended instance.
I am using Run Task activity in my workflow and while instance status is Suspended, it is throwing error when I want to open instance. After completing task, when instance status is already Finished it is possible to open.
What should I do?

Endpoint: https://elsa-server.azurewebsites.net/elsa/hubs/workflow-instance/negotiate?negotiateVersion=1

Thanks in advance.
![image](https://github.com/elsa-workflows/elsa-core/assets/75392065/1d46d3e5-3998-4e55-bacd-85ea0c50c0ae)

**Comment by avhovsepyan** [comment] 2024-03-28 13:53
@sfmskywalker, maybe any news?

**Comment by sfmskywalker** [comment] 2024-03-28 14:50
Which version of Elsa are you using? Also, could you attach a zip file containing your project that we can look at?
When I try with the latest version, I can execute & open the workflow instance, except that we broke something that prevents RunTask from executing successfully (but that's a different issue).

**Comment by avhovsepyan** [comment] 2024-03-29 06:28
So, did you able to open instance which status is Suspended?

**Comment by ErnestManukyanPlatAi** [comment] 2024-03-29 11:56
@sfmskywalker after upgrading the packages versions there are issues. Which packages is responsible for Run Task + Dispatcher service ? Maybe we need to upgrade only that one ?
![image](https://github.com/elsa-workflows/elsa-core/assets/144734589/893e710f-c4d2-4a66-81c7-4068f1bfef4f)
![image](https://github.com/elsa-workflows/elsa-core/assets/144734589/118115ac-1f70-4222-9af9-6774bc9e69bc)

**Comment by sfmskywalker** [comment] 2024-03-29 20:41
@avhovsepyan Yes, I am able to open the instance:

<img width="2552" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/938393/0a177b95-8bc7-4e11-ac93-bd728ab3307b">

I haven't tried with version 3.0.6, however, so it's possible that it is indeed broken in that version.

@ErnestManukyanPlatAi Make sure to update ALL Elsa packages to the latest version, which also means they must all be on the same version (mixing different versions of Elsa packages will cause issues). Please ensure that you do this for both the Studio and Server project.

**Comment by sfmskywalker** [comment] 2024-04-01 14:44
Can you attach a repro of this issue? From my end, everything seems to work fine.

**Comment by avhovsepyan** [comment] 2024-04-02 13:34
@sfmskywalker, I can attach example of workflow and Program.cs and csproj files of my Studio and Studio.Server projects.

FYI: Connection strings changed and set "localhost"
https://github.com/avhovsepyan/Elsa.Example

[workflow-for-suspended-status-test.json](https://github.com/elsa-workflows/elsa-core/files/14835822/workflow-for-suspended-status-test.json)

**Comment by avhovsepyan** [comment] 2024-04-05 07:43
@sfmskywalker, maybe any news?

**Comment by sfmskywalker** [comment] 2024-04-05 19:58
Hi @avhovsepyan , thank you for the sample projects - I can indeed reproduce the issue with this project. I will investigate.

**Comment by sfmskywalker** [comment] 2024-04-05 21:08
@avhovsepyan  The issue is as follows:

- In the Studio.Server project, the "RealtimeWorkflows" feature is enabled, which installs SignalR services.
- The Studio project inspects the enabled features, and identifies that the "RealtimeWorkflows" feature is enabled.
- It proceeds to try and connect to the SignalR WorkflowInstances hub <-- **This is what is failing**
- The reason this fails is because Studio.Server's request pipeline isn't configured with the SignalR middleware component

To fix that, add the following two lines at the correct places (I added a comment before each line you need to add in the Studio.Server project's Program.cs file):

```csharp
...
app.UseRouting();
...
app.UseWorkflowsSignalRHubs();
```

Here's a screenshot for better context of where to add these lines:

<img width="1792" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/938393/3d214f62-bf3d-413c-a489-8ed252027f3d">

What I will do as an improvement is catch the SignalR exception so that it doesn't cause a 404 response, and instead, generate a warning or something along those lines as a hint that there's something not right with the configuration.

**Comment by ErnestManukyanPlatAi** [comment] 2024-04-05 21:11
@sfmskywalker thank you really much

**Comment by sfmskywalker** [comment] 2024-04-05 21:30
No worries, thank you for your patience. I will now proceed and close this issue as resolved. Please do feel free to continue the conversation.

**Closed by sfmskywalker** 2024-04-05 21:30 UTC
Labels: bug, elsa 3

**Comment by avhovsepyan** [comment] 2024-04-07 18:40
@sfmskywalker thanks a lot
