### ISSUE TITLE
Elsa 2.0 Interrupting a sleeping workflow does not take the workflow to finish status.

### ISSUE THREAD

**Issue by AvtsVivek** [elsa-workflows/elsa-core#1013] opened 2021-05-20 05:30 UTC
I have created a [sample asp.net core project](https://github.com/AvtsVivek/ElsaBugReports/tree/main/src/P257WakeupSleepingWorkflow) and configured workflows to it. This is based on [Interrupt sample here](https://github.com/elsa-workflows/elsa-core/tree/master/src/samples/aspnet/Elsa.Samples.Interrupts).

The [IWorkflowTriggerInterruptor](https://github.com/elsa-workflows/elsa-core/blob/master/src/core/Elsa.Abstractions/Services/IWorkflowTriggerInterruptor.cs) service which can interrupt a [sleep activity](https://github.com/elsa-workflows/elsa-core/blob/master/src/samples/aspnet/Elsa.Samples.Interrupts/Activities/Sleep.cs) with the method InterruptActivityTypeAsync does not seem to work.  The workflow continues to be in Suspended state and only after the sleep time elapses does the workflow attains the Finished state. 

The UI looks as follows. You can start multiple workflows and query their current status by clicking the blue button. 

![image](https://user-images.githubusercontent.com/41255281/118920552-428f2180-b954-11eb-9ead-b9774cd6209c.png)

The problem is as follows. Lets say the workflow is configured to sleep for 5 minutes and I launch such workflow. Before the time of 5 minutes elapses, if I interrupt a workflow, I get the message that the workflow is interrupted, but if I query the status its still suspended.

![image](https://user-images.githubusercontent.com/41255281/118921005-08724f80-b955-11eb-866a-f2a4220906b6.png)

![image](https://user-images.githubusercontent.com/41255281/118921193-5be49d80-b955-11eb-81c9-a0cccc20b360.png)

![image](https://user-images.githubusercontent.com/41255281/118921325-9e0ddf00-b955-11eb-90b9-d902e3bda212.png)

But if I query again after 5 minutes have elapsed, the status shows finished. You can try that out by [running the project here](https://github.com/AvtsVivek/ElsaBugReports/tree/main/src/P257WakeupSleepingWorkflow). 

The [workflow here](https://github.com/elsa-workflows/elsa-core/blob/master/src/samples/aspnet/Elsa.Samples.Interrupts/Workflows/InterruptableWorkflow.cs) reads 

    .WriteLine("This workflow will sleep for 5 minutes before it continues.")                
    .WriteLine("Can't wait that long? Send me a message at https://localhost:6171/wakeup.")

What I understood from that is that if I interrupt a sleeping workflow, it should proceed to finish immediately. I dont have to wait for full 5 minutes to elapse. Am I wrong here? This does not seem to happen.

I referenced the source code and placed a breakpoint in CanExecuteAsync in the WorkflowRunner.cs class. After I click the link in my app to interrupt, I observed that the canExecute variable is false. If I force it to true using Visual Studio, then it proceeds to Finish status immediately.

![image](https://user-images.githubusercontent.com/41255281/118922886-66546680-b958-11eb-9bc6-fd6c240444c1.png)

I tried doing F11 there, but could not figure out what's happening. Why it is false even when I interrupt. 

Is there some bug there? The [sample is available here](https://github.com/AvtsVivek/ElsaBugReports/tree/main/src/P257WakeupSleepingWorkflow). 

![image](https://user-images.githubusercontent.com/41255281/118923496-3fe2fb00-b959-11eb-8a35-8494b6d6a044.png)

**Comment by sfmskywalker** [comment] 2021-05-21 11:14
> What I understood from that is that if I interrupt a sleeping workflow, it should proceed to finish immediately. I dont have to wait for full 5 minutes to elapse. Am I wrong here? This does not seem to happen.

You understood correctly. Definitely sounds like a bug and will investigate further. Thank you.

**Comment by sfmskywalker** [comment] 2021-05-21 11:36
Although I could not reproduce the issue exactly using the latest version of Elsa (`master`), I did notice that due to the fact you're using the `Sleep` custom activity, it wasn't successfully unscheduled from Quartz because the handler was using a white list of activity types to listen for (when being removed as a blocking activity).

I pushed a fix for that, which makes everything work nicely. Except of course that if you start multiple workflows, only one of them will finish successfully when you interrupt it, since your current implementation will attempt to interrupt ALL workflows, which will indeed interrupt all instances, causing them all to try and write to the HTTP response, which is what fails ("a response is already started").

Please try out the latest bits (from source code or until the MyGet package is available once [this builds](https://ci.appveyor.com/project/sfmskywalker/elsa/builds/39264298) finishes).

**Comment by sfmskywalker** [comment] 2021-05-21 11:37
Fixed with bd012d0965ea3b25ca8a62859a0df6af7d8884ab

**Closed by sfmskywalker** 2021-05-21 11:37 UTC
Labels: bug, prio high

**Comment by AvtsVivek** [comment] 2021-05-21 15:28
Thank You. With the latest code, its working.
