### ISSUE TITLE
ActivityExecutionContext - ConvertTo method of object results in issues

### ISSUE THREAD

**Issue by cristinamudura** [elsa-workflows/elsa-core#3166] opened 2022-06-27 08:35 UTC
The generic method Get of the ActivityExecutionContext results in issues when trying to convert ExpandoObject to Dictionary.

Current version
```csharp
    public T? Get<T>(MemoryBlockReference blockReference)
    {
        var value = Get(blockReference);
        return value != default ? value.ConvertTo<T>() : default;
    }
```

An solution would be to use the json deserializer
```csharp
    public T? Get<T>(MemoryBlockReference blockReference)
    {
        var value = Get(blockReference);
        var convertedValue = JsonSerializer.Deserialize<T>(JsonSerializer.Serialize(value));
        return value != default ? convertedValue : default;
    }
```

However this might impact other parts.

**Comment by sfmskywalker** [comment] 2022-12-21 21:10
@cristinamudura Do you have steps to reproduce this by any chance?

**Comment by sfmskywalker** [comment] 2023-03-23 11:22
I haven't seen this issue occurring since the many improvements that have gone in, so I'm closing this one.

**Closed by sfmskywalker** 2023-03-23 11:22 UTC
Labels: bug, core
