### ISSUE TITLE
Elsa3.1.0 package dependency

### ISSUE THREAD

**Issue by daconglee** [elsa-workflows/elsa-core#5163] opened 2024-04-01 05:34 UTC
I use PostgreSql ，why dependency MySqlConnector package. restult in not compile. 

ps:I not internet，net6.0

**Comment by Suchiman** [comment] 2024-04-01 15:30
Duplicate of #5158

**Comment by Suchiman** [comment] 2024-04-03 15:40
Should be resolved as of version 3.1.2 @daconglee

**Comment by sfmskywalker** [comment] 2024-04-05 18:49
As per @Suchiman 's remark, this is now fixed. Thanks for reporting @daconglee , and many thanks @Suchiman for the fix 👍🏻

**Closed by sfmskywalker** 2024-04-05 18:49 UTC
