### ISSUE TITLE
Nested Fork activity workflow never finishes

### ISSUE THREAD

**Issue by jcavalieri8619** [elsa-workflows/elsa-core#1342] opened 2021-08-02 13:11 UTC
I have a workflow that is similar to the example Document Approval demo, but there are multiple tiers of people that need to give their approval. It seemed natural to achieve this with a nested Fork, so that after the 1st person approves, we can move onto the 2nd, etc. But, this workflow never Finishes, whether i hit Approve or Reject in the emails, it stays in Suspended state. Am i doing something wrong? 

this example is identical to the Document Approval sample, except for the nested Fork i added after the first Approve branch
```
  builder
                .WithDisplayName("Document Approval Workflow")
                .HttpEndpoint(activity => activity
                    .WithPath("/document/start")
                    .WithMethod(HttpMethod.Post.Method)
                    .WithReadContent())
                .SetVariable("Document", context => context.GetInput<HttpRequestModel>()!.Body)
                .SendEmail(activity => activity
                    .WithSender("workflow@acme.com")
                    .WithRecipient("josh@acme.com")
                    .WithSubject(context => $"(1) Document received from {context.GetVariable<dynamic>("Document")!.Author.Name}")
                    .WithBody(context =>
                    {
                        var document = context.GetVariable<dynamic>("Document")!;
                        var author = document!.Author;
                        return $"Document from {author.Name} received for review.<br><a href=\"{context.GenerateSignalUrl("Approve")}\">Approve</a> or <a href=\"{context.GenerateSignalUrl("Reject")}\">Reject</a>";
                    }))
                .WriteHttpResponse(
                    HttpStatusCode.OK,
                    "<h1>Request for Approval Sent</h1><p>Your document has been received and will be reviewed shortly.</p>",
                    "text/html")
                .Then<Fork>(activity => activity.WithBranches("Approve", "Reject", "Remind"), fork =>
                {
                    fork
                        .When("Approve")
                        .SignalReceived("Approve")
                        .WriteLine("1st level approved")
                        .SendEmail(activity => activity
                            .WithSender("workflow@acme.com")
                            .WithRecipient(context => context.GetVariable<dynamic>("Document")!.Author.Email)
                            .WithSubject(context =>
                                $" (2) Document {context.GetVariable<dynamic>("Document")!.Id} Approved!")
                            .WithBody(context =>
                            {
                                var document = context.GetVariable<dynamic>("Document")!;
                                var author = document!.Author;
                                return $"Document from {author.Name} received for review.<br><a href=\"{context.GenerateSignalUrl("Approve2")}\">Approve</a> or <a href=\"{context.GenerateSignalUrl("Reject2")}\">Reject</a>";
                            }))
                        .Then<Fork>(activity2 => activity2.WithBranches("Approve2", "Reject2"), fork2 =>
                        {
                            fork2.When("Approve2").SignalReceived("Approve2")
                                .WriteLine("2nd level approved").ThenNamed("Join2");


                            fork2
                                .When("Reject2")
                                .SignalReceived("Reject2")
                                .WriteLine("2nd level rejected").ThenNamed("Join2");


                        })
                        .Add<Join>(join => join.WithMode(Join.JoinMode.WaitAny)).WithName("Join2")
                        .ThenNamed("Join");

                    fork
                        .When("Reject")
                        .SignalReceived("Reject")
                        .WriteLine("1st level rejected")
                        .SendEmail(activity => activity
                            .WithSender("workflow@acme.com")
                            .WithRecipient(context => context.GetVariable<dynamic>("Document")!.Author.Email)
                            .WithSubject(context => $"Document {context.GetVariable<dynamic>("Document")!.Id} Rejected")
                            .WithBody(context => $"Nice try {context.GetVariable<dynamic>("Document")!.Author.Name}, but that document needs work."))
                        .ThenNamed("Join");
                    
                })
                .Add<Join>(join => join.WithMode(Join.JoinMode.WaitAny)).WithName("Join")
                .WriteHttpResponse(HttpStatusCode.OK, "Thanks for the hard work!", "text/html");
```

**Comment by sfmskywalker** [comment] 2021-08-02 20:38
I don't recall ever testing this scenario - it's possible that there's a bug in te `Join` activity. Will investigate.

**Comment by jcavalieri8619** [comment] 2021-08-02 23:33
We've been talking about contributing the to the repo; try to help out. I'll pull the source and see if i can offer an assist for a solve. I can say that if you create a child workflow that contains the nested FORK, it works perfectly.. it that helps narrow down the context for the bug.

**Comment by sfmskywalker** [comment] 2021-08-07 17:59
I was able to reproduce the issue exactly as you described. The problem was that the Join activity would only clear out blocking activities present on the first inbound path, ignoring any additional inbound pathways.

I pushed a fix that selects all inbound forks so that all blocking activities in between the Join and Fork activities are removed.

**Closed by sfmskywalker** 2021-08-07 17:59 UTC
Labels: bug, prio high

**Comment by jcavalieri8619** [comment] 2021-08-09 11:57
awesome. thanks for quick response. love the library
