### ISSUE TITLE
Activity Menu not visible when activity name is too long

### ISSUE THREAD

**Issue by Alexplose** [elsa-workflows/elsa-core#1258] opened 2021-07-13 15:59 UTC
As seen below 

![image](https://user-images.githubusercontent.com/18287013/125485249-5175f470-be35-4de6-99ee-77a49618eb3f.png)

Workaround is to use chrome inspector, to change text.

**Comment by sfmskywalker** [comment] 2021-07-14 12:21
Duplicate of #1227

**Closed by sfmskywalker** 2021-07-14 12:21 UTC
