### ISSUE TITLE
Edit Receive HTTP Request URL Parameters

### ISSUE THREAD

**Issue by mzck5y** [elsa-workflows/elsa-core#333] opened 2020-06-19 05:29 UTC
Hello first of all great framework. Quick question, it is possible to pass url parameters? like /customers/{id}?

**Comment by sfmskywalker** [comment] 2020-06-23 18:10
Thank you!

Route parameters aren't currently supported by the HTTP Request Received activity, but it would make for an important addition.

**Comment by craigfowler** [comment] 2021-03-04 17:59
@sfmskywalker or @jwillmer - do you think this looks like a dupe of #669 or #667?  I think it is but I'd like a nod from one of you instead of just killing it off.

**Comment by sfmskywalker** [comment] 2021-03-04 18:38
It’s related but not the same. This particular issue is about supporting route parameters like we have with controller routes. So I’d say let’s keep this open or create a separate issue with design notes for such a capability.

**Comment by sfmskywalker** [comment] 2024-07-05 17:35
This is supported in V3

**Closed by sfmskywalker** 2024-07-05 17:35 UTC
Labels: enhancement, prio low
