### ISSUE TITLE
Elsa2 dashboard problem

### ISSUE THREAD

**Issue by SaeedBolhasani** [elsa-workflows/elsa-core#1264] opened 2021-07-14 06:54 UTC
It is my pleasure to say Hello to you.
I have problem with new dashboard. here is the error:

TypeError: Cannot read property 'map' of undefined
    at Ee.render (p-aa71e17a.entry.js:1)
    at Y (p-2ef56300.js:1)
    at X (p-2ef56300.js:1)
    at p-2ef56300.js:1 <elsa-workflow-instance-list-screen class=​"hydrated">​</elsa-workflow-instance-list-screen>​
he @ p-2ef56300.js:1

The error happen when i click on workflow instances button.
All other thing work very good and pretty.

Thank you

**Comment by sfmskywalker** [comment] 2021-07-14 12:29
Hi Saeed,

Does this also happen even when there are no workflow instances?
What product and version are you using specifically? I.e. are you using the Docker image or your own project, and if so, which version of the packages?

Additionally, since the issue does not happen for me, can you provide me with steps to reproduce the problem?

**Comment by SaeedBolhasani** [comment] 2021-07-14 20:04
Thanks for your attention my friend.
Yes actually it happen when there is no instance.
I listed used nugets below:
elsadashboard.backend\2.0.0.159
elsadashboard.webassembly\2.0.0.159
elsadashboard.application\2.0.0.159
elsa.server.api\2.0.0.159
elsa.client\2.0.0.159
elsa.persistence.entityframework.sqlserver\2.0.0.159
elsa\2.0.0.159

And i used them directly in my project(no docker)

I dont know how to guide you to regenerate the error. I just set up a simple project to see elsa dashboard.
and here is my index.html
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Elsa Workflows</title>
    <link rel="icon" type="image/png" sizes="32x32" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-16x16.png">
    <link rel="stylesheet" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/fonts/inter/inter.css">
    <link rel="stylesheet" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/styles/tailwind.css">
    <script src="/_content/Elsa.Designer.Components.Web/monaco-editor/min/vs/loader.js"></script>
    <script type="module" src="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.esm.js"></script>
</head>
<body class="h-screen" style="background-size: 30px 30px; background-image: url(/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/tile.png); background-color: #FBFBFB;">
    <elsa-studio-root server-url="@serverUrl" monaco-lib-path="_content/Elsa.Designer.Components.Web/monaco-editor/min"></elsa-studio-root>
</body>
</html>`

**Comment by sfmskywalker** [comment] 2021-07-14 21:15
I see. Odds are that it will just work with the 2.1 release. Perhaps you can try going through [this document](https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-aspnetcore-server-dashboard-and-api-endpoints)? It should take no more than 10 minutes and result in a fully-functioning dashboard.

Let me know how it goes.

**Comment by SaeedBolhasani** [comment] 2021-07-17 03:47
It has same problem again!

**Comment by SaeedBolhasani** [comment] 2021-07-17 04:30
It seems  /v1/workflow-instances api has problem.
It returns nothing!
![image](https://user-images.githubusercontent.com/39827331/126025468-2543ebe5-e3e4-432d-a967-304fb575dcbc.png)

**Comment by sfmskywalker** [comment] 2021-07-17 06:29
Are you still getting the errors you mentioned in your initial post?

If so, what happens if you delete the workflow instances from the database, run your workflow again, and then try to list the workflows again?

That screenshot doesn’t show any issues that I can see. It only shows an example.

Can you provide me with steps to reproduce the issue you are seeing? Or send me your project so I can investigate?

**Comment by SaeedBolhasani** [comment] 2021-07-17 06:45
Yes i get same previous error.
I did every thing that you suggested.
In screenshot, i mean when i want to get all workflow instances it returns just status code(200).
And here is my project
Thank you so much
[Workflow.zip](https://github.com/elsa-workflows/elsa-core/files/6834294/Workflow.zip)

**Comment by sfmskywalker** [comment] 2021-07-23 08:16
Thanks for sending the project.

One curious thing I encountered is that your project references `Elsa.Designer.Components.Web` version `2.1.1.467`. However, the latest version that is on NuGet is `2.1.1.463`.

This prevents the project from restoring its dependencies, since some of them don't exist.
I'm wondering how you were able to compile the project in the first place?

Meanwhile, I'm going to try and reproduce the reported issue using latest prerelease packages from MyGet.

**Comment by sfmskywalker** [comment] 2021-07-23 08:29
After updating the packages and starting the project, I don't get any issues when clicking on the Workflow Instances tab:

![image](https://user-images.githubusercontent.com/938393/126756164-abecc71a-152d-44bc-b314-c107212018fd.png)

Here's what I suggest you do:

1. Update to the latest prerelease packages on MyGet.
2. Make sure to update your _host.cshtml file (see snippet below)
3. Try again.

If you are still seeing the issue, then create a copy of your project, remove anything unrelated to Elsa such as the `InspectDbContext` type and anything that depends on it. 
Make sure you can still reproduce the issue, and if so, send it over to me.

I'm closing this issue for now as I cannot reproduce it, but feel free to reopen when you have a repro for me.

Thank you.

**Closed by sfmskywalker** 2021-07-23 08:29 UTC

**Comment by SaeedBolhasani** [comment] 2021-07-27 11:36
Hi again.
Thank you very much for your follow-up.
Finally I found the problem comes from Elsa.Persistence.EntityFramework.SqlServer Version="2.2.0-preview.503".
It works with Sqlite properly, but it does not work with sql server.
Here is the error:

`Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'OFFSET'.
Invalid usage of the option NEXT in the FETCH statement.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.<>c__DisplayClass12_0.<<FindManyAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.DoWork[TResult](Func`2 work, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.DoWork[TResult](Func`2 work, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFramework.Core.Stores.EntityFrameworkStore`2.FindManyAsync(ISpecification`1 specification, IOrderBy`1 orderBy, IPaging paging, CancellationToken cancellationToken)
   at Open.Linq.AsyncExtensions.Extensions.ToList[TSource](Task`1 source)
   at Elsa.Server.Api.Endpoints.WorkflowInstances.List.Handle(String workflowDefinitionId, Nullable`1 workflowStatus, Nullable`1 orderBy, String searchTerm, Int32 page, Int32 pageSize, CancellationToken cancellationToken)
   at lambda_method74(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Elsa.Activities.Http.Middleware.HttpEndpointMiddleware.InvokeAsync(HttpContext httpContext, IOptions`1 options, IWorkflowLaunchpad workflowLaunchpad, IWorkflowInstanceStore workflowInstanceStore, IWorkflowRegistry workflowRegistry, IWorkflowBlueprintReflector workflowBlueprintReflector, IEnumerable`1 contentParsers)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
ClientConnectionId:41635c15-7378-41e8-af6e-3016bf2defbd
Error Number:102,State:1,Class:15`

And I attached my project.

**Comment by sfmskywalker** [comment] 2021-07-27 18:16
Thank you for the sample project! However it seems like something else is still missing. When I run your project using SQL Server, it just works. I created a couple of workflow instances, paginated through them, all without issue (except for the pagination JS not properly working for the workflow instances list, but that's a separate issue I just fixed).

Perhaps it's something with your SQL database? What version of SQL Server are you using? What happens if you try to update your connection string by pointing it to a new database name?

**Comment by SaeedBolhasani** [comment] 2021-07-28 07:14
I am using sql server 2017. 
I tried with new database, but make no difference.
It is very strange. however, according to your mention, it seems my sql server has problem.
So I try to figure out the problem and share result here.
Thank you agian.
Have a good time.
