### ISSUE TITLE
Designer | published changes to workflow are reflected only after server restart

### ISSUE THREAD

**Issue by SachinMehndiratta** [elsa-workflows/elsa-core#1107] opened 2021-06-09 10:31 UTC
Elsa 2 is coming out great, really impressed with the work done so far. However there's an issue I have noted while publishing the new versions of workflow via dashboard.

Published changes are not reflected until I restart the server, (though this could be a server side cache implementation in ELSA2 and changes may reflect in a while which I am not sure). I have updated the liquid expressions via UI and published the workflow but changes are not applicable till server restart. In past I have seen the same when adding the new activities in the workflow via UI and these are not executed until server is restarted, I assume this still stands as a bug.

I feel that published changes should come into effect immediately when workflow is published.

**Comment by sfmskywalker** [comment] 2021-06-10 07:56
Hi Sachin,

I tried to reproduce this, but publishing changes do take into effect when I try. Would it be possible for you to send me a repro that I can look at?

**Comment by SachinMehndiratta** [comment] 2021-06-10 08:30
Hi Sipke,

Sure, I'll share a sample or a recording for you late evening today. I realized, in each of my attempt my first activity was a signaled workflow. Could be an issue with signaled workflow as first activity.

Though, I'll share some helpful steps or a recording to demonstrate this.

**Comment by sfmskywalker** [comment] 2021-06-10 08:41
Much appreciated, thanks Sachin. By the way, I forgot to ask: which package versions are you using?

**Comment by sfmskywalker** [comment] 2021-07-14 17:33
I'm closing this issue since I haven't been able to reproduce it. Should you still have this issue with 2.1, please do reopen. Thanks!

**Closed by sfmskywalker** 2021-07-14 17:33 UTC
