### ISSUE TITLE
WorkflowFault got exception when deserialize

### ISSUE THREAD

**Issue by supertruong** [elsa-workflows/elsa-core#357] opened 2020-08-17 07:11 UTC
When I using ExpressionEvaluate and got an exception it threw an WorkflowException. The workflow serialized and stored it to the database. But when I got it back and deserialized it to exception, it threw an exception:
`Member 'HelpURL' was not found`.

Thanks

**Comment by syntaxonline-rewhitley** [comment] 2020-10-07 04:42
I was running to the same issue and used a custom serializer to manager serializing/deserializing the exception type. Still haven't looked to much into it, but for now I just return null on read to make the code backwards compatible with the logic prior to the change

**Comment by sfmskywalker** [comment] 2021-01-30 14:45
The issue is that Elsa 1 serializes the actual Exception object, which is problematic when being deserialized.,
This has been fixed in Elsa 2.

**Closed by sfmskywalker** 2021-01-30 14:45 UTC
