### ISSUE TITLE
[BUG] Cannot delete a Activity in Studio Canvas

### ISSUE THREAD

**Issue by anhlee97** [elsa-workflows/elsa-core#5757] opened 2024-07-13 14:44 UTC
I am using , Studio Blazor Server run on MacOS M1 local
![CleanShot 2024-07-13 at 21 43 56@2x](https://github.com/user-attachments/assets/454966e5-c586-4238-81b0-e94b4bbbf82a)
I selected a activity and then click a Delete Key but it not working.

**Comment by sfmskywalker** [comment] 2024-07-16 19:00
Duplicate of https://github.com/elsa-workflows/elsa-studio/issues/258

**Closed by sfmskywalker** 2024-07-16 19:00 UTC
Labels: bug
