### ISSUE TITLE
Automapper Issue

### ISSUE THREAD

**Issue by maharatha** [elsa-workflows/elsa-core#290] opened 2020-04-13 02:42 UTC
I use https://aspnetboilerplate.com/ framework and the moment I add Elsa into my project i get all sort of Mapping Issues.

I use :
 services.AddElsa();

An unhandled exception occurred while processing the request.
AutoMapperMappingException: Missing type map configuration or unsupported mapping.

The moment i remove Elsa everything works normal.

I tried the version from Nuget and MyGet and both have the same issue.

**Comment by sfmskywalker** [comment] 2020-04-13 06:05
Might be a regression or a typemap I missed. Would you mind sharing the full exception so that I can see what types are missing type maps?

**Comment by maharatha** [comment] 2020-04-13 07:32
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
User -> UserLoginInfoDto
DOCUHOLD.EDRMS.Authorization.Users.User -> DOCUHOLD.EDRMS.Sessions.Dto.UserLoginInfoDto
   at lambda_method(Closure , User , UserLoginInfoDto , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at Abp.AutoMapper.AutoMapperObjectMapper.Map[TDestination](Object source)
   at DOCUHOLD.EDRMS.Sessions.SessionAppService.GetCurrentLoginInformations() in C:\Softwares\Source Code\CANDW8.3.1\aspnet-core\src\DOCUHOLD.EDRMS.Application\Sessions\SessionAppService.cs:line 59
   at Abp.Domain.Uow.UnitOfWorkInterceptor.InternalInterceptAsynchronous[TResult](IInvocation invocation)
   at Abp.Auditing.AuditingInterceptor.InternalInterceptAsynchronous[TResult](IInvocation invocation)
   at Abp.Runtime.Validation.Interception.ValidationInterceptor.InternalInterceptAsynchronous[TResult](IInvocation invocation)
   at DOCUHOLD.EDRMS.Web.Session.PerRequestSessionCache.GetCurrentLoginInformationsAsync() in C:\Softwares\Source Code\CANDW8.3.1\aspnet-core\src\DOCUHOLD.EDRMS.Web.Core\Session\PerRequestSessionCache.cs:line 33
   at DOCUHOLD.EDRMS.Web.Controllers.UiController.Index() in C:\Softwares\Source Code\CANDW8.3.1\aspnet-core\src\DOCUHOLD.EDRMS.Web.Host\Controllers\UiController.cs:line 47
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Abp.AspNetZeroCore.Web.Authentication.JwtBearer.JwtTokenMiddleware.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by BeiMeng** [comment] 2020-04-13 07:39
Sample24 can reproduce this bug，thank you

**Comment by sfmskywalker** [comment] 2020-04-13 10:07
That's a great catch. Although I did not get the exact same error when running Sample24, I did discover an important bug to do with registering AutoMapper profiles.

I just pushed a fix to the `develop` branch, which will get built & deployed to MyGet creating version `1.2.2.49-preview`.

Please give that a go and let me know if you are still running into issues.

Thanks for reporting!

**Comment by maharatha** [comment] 2020-04-13 15:28
I don't see the package available yet.

**Comment by sfmskywalker** [comment] 2020-04-13 15:34
I see why; MyGet deleted it due to retention policies. I should remove the 2.0.0 preview bits.

**Comment by maharatha** [comment] 2020-04-13 19:17
> I see why; MyGet deleted it due to retention policies. I should remove the 2.0.0 preview bits.
Let me know when it's available. I will be waiting. I have some other issues to report but will do once i get pass this.

**Comment by sfmskywalker** [comment] 2020-04-13 19:47
Alright, I just ran the build again an the packages are now there on MyGet (1.2.2.52-preview).

**Comment by maharatha** [comment] 2020-04-13 20:11
I tried it and unfortunately it didn't resolve the issue. It's throwing up the same issue.

I tried with Elsa (didn't work ) and without Elsa (worked fine) as well as checked the Elsa version and I have the latest preview version from MyGit 1.2.2.52-preview

**Comment by sfmskywalker** [comment] 2020-04-13 20:13
OK. Any chance you can provide me with a sample project that I can try?

**Comment by maharatha** [comment] 2020-04-13 20:59
Is there a way I can securely share ?

**Comment by sfmskywalker** [comment] 2020-04-13 21:13
Email or TransferWise usually works for me, or else a OneDrive/GoogleDrive link. Or If you are part of an Org on GitHub, you could post your code to a private repo there and grant me (read) access.

Or maybe create a blank new project with only the bare minimum showing the issue. For example, a new Console app referencing ABP etc. This might be the best option.

**Comment by kion-admin** [comment] 2020-04-13 23:00
i have same problem with asp.net boilerplate framework, somethink ignore automapper configs

**Comment by maharatha** [comment] 2020-04-13 23:02
I have set the link to your email address. I am sending you instruction to compile and run inan email

**Comment by kion-admin** [comment] 2020-04-13 23:05
When i add, services.AddElsa() its disable abp automapper configurations

**Comment by sfmskywalker** [comment] 2020-04-14 20:37
Indeed. I checked out the project from @maharatha , and it looks like the following is what is happening:

1. Elsa creates a `MapperConfiguration` and uses it to create an `IMapper`, which is registered with IoC.
2. ABP also creates a `MapperConfiguration` and uses it to create an `IMapper`, which is also registered.

Because the one from Elsa is registered first, anytime something resolves/injects `IMapper`, it receives the instance from Elsa, which does not contain any of the mapping configuration from ABP.

I need a bit of time to think of a good solution to make Elsa and ABP play nice. If anyone has any suggestions, please do share.

**Comment by sfmskywalker** [comment] 2020-04-14 20:59
Of course, if both Elsa and ABP followed [AutoMapper Usage Guidelines](https://jimmybogard.com/automapper-usage-guidelines/), there wouldn't be an issue.

But it's probably unlikely either Elsa or ABP will do so, since both projects seem to have a preference of registering IMapper as a singleton for one thing, while AutoMapper's DI extensions are writen to use the Scoped lifetime.

Anyway, I'm thinking about the following solution:

1. Elsa will use AutoMapper completely internally by using an mapper factory class. Internally, it will create its own IServiceCollection and find all AutoMapper profiles, and then create an actual IMapper - but it won't be registered with the IoC that is used by ABP, so there won't be conflicts.

I'll investigate this option soon. If there are any alternative suggestions, do let me know.

**Comment by maharatha** [comment] 2020-04-14 22:53
Thank You. I will eagerly wait for you to find a solution

**Comment by kion-admin** [comment] 2020-04-15 13:07
abp have module class, and automapper configs could add somethink like that, if elsa have option disable automapper config auto, and we can inject from here maybe    

[DependsOn(
        typeof(ApplicationSharedModule),
        typeof(CoreModule)
        )]
    public class ApplicationModule : AbpModule
    {
        public override void PreInitialize()
        {
            //Adding authorization providers
            Configuration.Authorization.Providers.Add<AppAuthorizationProvider>();

            //Adding custom AutoMapper configuration
            Configuration.Modules.AbpAutoMapper().Configurators.Add(Application.CustomDtoMapper.CreateMappings);
        }

        public override void Initialize()
        {
            IocManager.RegisterAssemblyByConvention(typeof(ApplicationModule).GetAssembly());
        }
    }
}

**Comment by sfmskywalker** [comment] 2020-04-15 13:15
That would work, but Elsa itself consists of a number of NuGet packages, where each package has its own set of service registration methods which may include the registration of AutoMapper profiles. I don't want to move all of those profiles to a single method so that it becomes optional to be invoked.

Perhaps if I introduced some automapper abstraction, e.g. `IMappingProfileProvider`, then each package can implement that, and I would expose an optional extension method such as `.AddMappingProfiles` or whatever. Then from ABP, you would simply *not* call this method, and everyone else would.

I'll consider this option as well as my initial one where I keep the entire IMapper instance private to Elsa.

Thanks for the input!

**Comment by kion-admin** [comment] 2020-04-16 02:01
I understand, thanks for solution, i waiting you :)

**Comment by maharatha** [comment] 2020-04-22 20:11
Any updates?

**Comment by sfmskywalker** [comment] 2020-04-23 09:24
No updates on this, sorry. I've been swamped with the launch of another project. Hopefully I will find enough time to work on this next week or the week thereafter.

**Comment by LiuXiao617111** [comment] 2020-05-09 02:00
Waiting for repair

**Comment by kion-admin** [comment] 2020-05-13 21:51
any updates?

**Comment by sfmskywalker** [comment] 2020-05-13 23:16
No updates yet, sorry guys. But I will look into this tomorrow. Thank you for your understanding and patience, I do appreciate it.

**Comment by sfmskywalker** [comment] 2020-05-14 20:05
Quick update: I [drafted a PR](https://github.com/elsa-workflows/elsa-core/pull/309). Still need to test it and clean thins up, but should be able to merge in tomorrow.

**Closed** 2020-05-15 10:08 UTC
Labels: enhancement

**Comment by sfmskywalker** [comment] 2020-05-15 10:11
PR merged & preview packages (1.3.0.2-preview) have been deployed to MyGet. Please let me know if that works.

**Comment by kion-admin** [comment] 2020-05-27 07:53
Hi, i tried with 1.3.0.7 its worked together boilerplate but i didnt try yet elsa functions just project started without problems

**Comment by kion-admin** [comment] 2020-05-27 19:31
Hello, i tried

Error changed. Its throw

Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalModelAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalPropertyAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

I guess its because of elsa use ef core 3.1.1 but boilerplate use 3.1.3 on same project, how can we fix that

**Comment by pest1999** [comment] 2020-07-08 01:30
Any updates?
I tried with 1.3.0.7 and 1.3.0.12 its worked together boilerplate but esla cannot work
In abp vnext esla can work with [https://github.com/zrkcode/Elsa-Workflow-Issue](Elsa-Workflow-Issue)

**Comment by hyzx86** [comment] 2020-10-15 18:18
Hi guys, can ABP integrate Elsa now?
I report this error here:
```INFO  2020-10-16 02:03:58,213 [14   ] ft.AspNetCore.Routing.EndpointMiddleware - Executing endpoint 'Elsa.Dashboard.Areas.Elsa.Controllers.HomeController.Index (Elsa.Dashboard)'
INFO  2020-10-16 02:03:58,217 [14   ] c.Infrastructure.ControllerActionInvoker - Route matched with {area = "Elsa", action = "Index", controller = "Home"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller Elsa.Dashboard.Areas.Elsa.Controllers.HomeController (Elsa.Dashboard).
ERROR 2020-10-16 02:03:58,343 [14   ] Mvc.ExceptionHandling.AbpExceptionFilter - No component for supporting the service Elsa.Dashboard.Areas.Elsa.Controllers.HomeController was found
Castle.MicroKernel.ComponentNotFoundException: No component for supporting the service Elsa.Dashboard.Areas.Elsa.Controllers.HomeController was found
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, Arguments arguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, Arguments arguments)
   at Castle.Windsor.MsDependencyInjection.ScopedWindsorServiceProvider.ResolveInstanceOrNull(Type serviceType, Boolean isOptional)
   at Castle.Windsor.MsDependencyInjection.ScopedWindsorServiceProvider.GetServiceInternal(Type serviceType, Boolean isOptional)
   at Castle.Windsor.MsDependencyInjection.ScopedWindsorServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
INFO  2020-10-16 02:03:58,509 [14   ] c.Infrastructure.ControllerActionInvoker - Executed action Elsa.Dashboard.Areas.Elsa.Controllers.HomeController.Index (Elsa.Dashboard) in 292.2851ms
INFO  2020-10-16 02:03:58,553 [14   ] ft.AspNetCore.Routing.EndpointMiddleware - Executed endpoint 'Elsa.Dashboard.Areas.Elsa.Controllers.HomeController.Index (Elsa.Dashboard)'
ERROR 2020-10-16 02:03:58,798 [14   ] AspNetCore.Server.IIS.Core.IISHttpServer - Connection ID "18374686524231909400", Request ID "8000001b-000a-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Castle.MicroKernel.ComponentNotFoundException: No component for supporting the service Elsa.Dashboard.Areas.Elsa.Controllers.HomeController was found
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, Arguments arguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, Arguments arguments)
   at Castle.Windsor.MsDependencyInjection.ScopedWindsorServiceProvider.ResolveInstanceOrNull(Type serviceType, Boolean isOptional)
   at Castle.Windsor.MsDependencyInjection.ScopedWindsorServiceProvider.GetServiceInternal(Type serviceType, Boolean isOptional)
   at Castle.Windsor.MsDependencyInjection.ScopedWindsorServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Elsa.Activities.Http.Middleware.RequestHandlerMiddleware`1.InvokeAsync(HttpContext httpContext, THandler handler)
   at Abp.AspNetCore.Security.AbpSecurityHeadersMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()```

**Comment by hyzx86** [comment] 2020-10-15 18:40
I write like this, I can open `elsa/home`, but js still encounters a 404 error
```
        public override void Initialize()
        {
            IocManager.Register<Elsa.Dashboard.Areas.Elsa.Controllers.HomeController>(); 
            IocManager.Register<Elsa.Dashboard.Areas.Elsa.Controllers.WorkflowDefinitionController>(); 
            IocManager.Register<Elsa.Dashboard.Areas.Elsa.Controllers.WorkflowInstanceController>(); 
            IocManager.Register<Elsa.WorkflowDesigner.ViewComponents.WorkflowDesignerViewComponent>();
            IocManager.RegisterAssemblyByConvention(typeof(SGASCWebHostModule).GetAssembly());
        }
```

**Comment by hyzx86** [comment] 2020-10-15 18:50
After copying these files from the sample project, the display is normal

![image](https://user-images.githubusercontent.com/15613121/96173268-396f4980-0f5a-11eb-8c75-80b14bdd26a8.png)

**Comment by hyzx86** [comment] 2020-10-15 19:02
The interface is normal, but the database is not working anymore. My Elsa database is placed in the same database as other tables in ABP.

```
      //Elsa
            services
                   // Required services for Elsa to work. Registers things like `IWorkflowInvoker`.
                   .AddElsa(x => x.AddEntityFrameworkStores<SqlServerContext>(
                        options =>
                        {
                            options.UseSqlServer(_appConfiguration["ConnectionStrings:Default"]);
                        }))
                     // Registers necessary service to handle HTTP requests.
                     .AddHttpActivities()
                     // Registers a hosted service that periodically invokes workflows containing time-based activities. 
                     .AddTimerActivities()
                     .AddElsaDashboard();
```

```
NFO  2020-10-16 02:58:30,861 [38   ] c.Infrastructure.ControllerActionInvoker - Executed action Elsa.Dashboard.Areas.Elsa.Controllers.WorkflowDefinitionController.Index (Elsa.Dashboard) in 34.6322ms
INFO  2020-10-16 02:58:30,861 [38   ] ft.AspNetCore.Routing.EndpointMiddleware - Executed endpoint 'Elsa.Dashboard.Areas.Elsa.Controllers.WorkflowDefinitionController.Index (Elsa.Dashboard)'
ERROR 2020-10-16 02:58:30,861 [38   ] AspNetCore.Server.IIS.Core.IISHttpServer - Connection ID "18374686485577203724", Request ID "80000017-0001-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'SqlServerContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbContextDependencies.get_StateManager()
   at Microsoft.EntityFrameworkCore.Query.QueryContextDependencies.get_StateManager()
   at Microsoft.EntityFrameworkCore.Query.QueryContext.get_StateManager()
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFrameworkCore.Services.EntityFrameworkCoreWorkflowDefinitionStore.ListAsync(VersionOptions version, CancellationToken cancellationToken)
   at Elsa.Dashboard.Areas.Elsa.Controllers.WorkflowDefinitionController.Index(CancellationToken cancellationToken)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Elsa.Activities.Http.Middleware.RequestHandlerMiddleware`1.InvokeAsync(HttpContext httpContext, THandler handler)
   at Abp.AspNetCore.Security.AbpSecurityHeadersMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
INFO  2020-10-16 02:58:30,862 [38   ] Microsoft.AspNetCore.Hosting.Diagnostics - Request finished in 40.2572ms 500 
```
