### ISSUE TITLE
Elsa 2.4 Intercept Outgoing HTTP Requests does not work anymore

### ISSUE THREAD

**Issue by antoine-conserto** [elsa-workflows/elsa-core#2653] opened 2022-01-06 13:36 UTC
Hi,

We have a plugin to intercept requests and set an authorization as in the example : 
[https://elsa-workflows.github.io/elsa-core/docs/next/extensibility/extensibility-designer-plugins#intercept-outgoing-http-requests
](https://elsa-workflows.github.io/elsa-core/docs/next/extensibility/extensibility-designer-plugins#intercept-outgoing-http-requests
)

We tested the migration from version 2.3 to 2.4.
And our plugin no longer works in version 2.4 on a new route `/v1/features` 

I think it comes from this feature 
[https://github.com/elsa-workflows/elsa-core/pull/2619
](https://github.com/elsa-workflows/elsa-core/pull/2619
)

EDIT :
Same on the preview version: `2.4.1-preview.11`

![401-elsa-features](https://user-images.githubusercontent.com/65608561/148393364-c74a30c6-34d8-4440-91ad-ce763704d10f.png)

**Comment by Jejuni** [comment] 2022-01-06 18:21
I was thinking of opening an issue myself.
I ran into that problem yesterday as well.

The commit that broke it was the one that added the features call.

Here's what's going on:

There is a function called `createElsaClient` in `elsa-client.ts` that creates the client to access the backend.
The code emits the `'http-client-created'` event bus event on creation in which the middleware to intercept calls gets added.
**However, that client is cached an reused after creation. Any additional calls to `createElsaClient` will reuse the already created client with the middleware that it has registered.**

Here is the relevant code:

![image](https://user-images.githubusercontent.com/33608497/148427555-439effa7-90ce-43f9-b536-9b0c37d1f879.png)

So far so good.
The commit that broke interception middleware added a call to `createElsaClient` in the initialization function of `elsa-studio-root`.
Critically, **it creates the cached client BEFORE THE PLUGIN MANAGER IS INITIALIZED**.
That means that when the `'http-client-created'` event is emitted the plugin is not yet created and since the client is cached the event will never be emitted again.

Here is the relevant code:

![image](https://user-images.githubusercontent.com/33608497/148429208-ae469888-9857-4106-8c00-bda881504b65.png)

The quick fix would be to simply reorder the operations to that the client is created after the plugin manager is initialized, like so:

```js
   // other code in componentWillLoad()

    const elsaClient = await elsaClientFactory();
    elsaStudio.serverFeatures = await elsaClient.featuresApi.list();
```
(Move the `const elsaClient = await elsaClientFactory();` from line 71 to like 94)

@antoine-conserto depending on how you use the designer and how urgent you need the fix you can do this yourself, compile the assets from source via `build-assets.ps1` and then use the assets build from source instead of what you're using right now.

I have to say, though, I really don't like how this project treats authentication like an afterthought. 
The way it has to be set up and is integrated kind of feels like it's just a happy coincidence that it works at all.

**Comment by antoine-conserto** [comment] 2022-01-07 10:30
Thank you @Jejuni ! 

I tested with your modification and by building the assets, it's ok with this fix.

It's not particularly urgent for us, but it blocks the upgrade to version 2.4.
In a future patch version that would be good.

**Comment by sfmskywalker** [comment] 2022-01-07 11:32
@Jejuni nice find! I'll take a look at your PR 👍🏻

**Comment by sfmskywalker** [comment] 2022-01-07 11:36
PR looks good and was merged, so closing this issue since the OP confirmed the fix is working. Great stuff!

**Closed by sfmskywalker** 2022-01-07 11:36 UTC
