### ISSUE TITLE
Workflow-as-activity produces string instead of object

### ISSUE THREAD

**Issue by Nekrosis1** [elsa-workflows/elsa-core#4967] opened 2024-02-20 10:48 UTC
**Summary:**
Adding a Workflow as an activity to a workflow, setting its output to object and ensuring its output is an object, when writing that output into a variable of type object, the value in the object is of type string.

**How to reproduce:**

- Create a workflow and define a variable with type JSON.
- create dummy data, for example Set Variable with JSON and write it to the variable.
- Save and publish the Workflow.
- Run the Workflow.
- Change the Variable to type object.
- Create a Workflow usable as activity with output type object.
- use the Workflow activity in the Workflow and set the output to the variable.
- When running the workflow, the variable actually is a string, this can be confirmed by trying to access its props or by using Writeline Activity and printing `typeof(getMyVariable) `of the variable.

**Workaround:**
Set the output of the activity to JSON and add a SetVariable activity right after.
Configure the SetVariable to set the variable of type object with the output of the activity with
`JSON.parse(getMyOutputFromMyActivity()); `
Never changing the type of an Elsa Variable is recommended.

Edit:
The issue does not seem consistent
When creating a Workflow like according to my reproduce steps, it correctly sets the value to object.
[output-type-bug.json](https://github.com/elsa-workflows/elsa-core/files/14343413/output-type-bug.json)

In the following workflow, the output is of type string
[get-article-info.json](https://github.com/elsa-workflows/elsa-core/files/14343441/get-article-info.json)

Edit2: 
Updated how to reproduce, it seems Elsa Variables retain some knowledge about their type, even after the type has changed
[output-type-bug (1).json](https://github.com/elsa-workflows/elsa-core/files/14384045/output-type-bug.1.json)

**Comment by Nekrosis1** [comment] 2024-02-20 11:17
I tried to create a Workflow where I isolate the issue.
In that workflow, everything behaves as expected, the variable is of type object.
So the issue is not consistent or not where I assumed to be.
I added the workflow where the bug happens, which seems to do exactly the same thing as the example.

Is it possible that the variable somehow remembers that it once got a string, and then always converts its value to string, even when set to type object?

**Comment by sfmskywalker** [comment] 2024-02-25 13:11
Hi @Nekrosis1 , thank you for reporting this issue. When trying to reproduce the issue, I imported your workflows, but they contain references to custom activities:

<img width="1196" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/938393/ff420b97-9fe0-462e-bad9-153e14acb5bc">

Is there any chance you can reproduce the behavior without using custom activities?

**Comment by sfmskywalker** [comment] 2024-03-28 20:58
I will close this for now as "cannot reproduce", but please feel free to reopen it if you have steps to reproduce.

**Closed by sfmskywalker** 2024-03-28 20:58 UTC
Labels: bug
