### ISSUE TITLE
[BUG]Elsa.Workflows.Middleware.Activities.ExceptionHandlingMiddleware[0]       An exception was caught from a downstream middleware component

### ISSUE THREAD

**Issue by captaris** [elsa-workflows/elsa-core#5841] opened 2024-07-25 21:30 UTC
Elsa.Expressions.Exceptions.TypeConversionException: Failed to deserialize {"$values":["Sequence2"],"_type":"String[]"} to System.Collections.Generic.HashSet`1[System.String]
       ---> System.Text.Json.JsonException: A '$values' metadata property must always be preceded by other metadata properties, such as '$id' or '$type'. Path: $.$values | LineNumber: 0 | BytePositionInLine: 11.
         at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
         at System.Text.Json.JsonSerializer.TryReadMetadata(JsonConverter converter, JsonTypeInfo jsonTypeInfo, Utf8JsonReader& reader, ReadStack& state)
         at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
         at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
         at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
         at Elsa.Expressions.Helpers.ObjectConverter.ConvertTo(Object value, Type targetType, ObjectConverterOptions converterOptions)
         --- End of inner exception stack trace ---
         at Elsa.Expressions.Helpers.ObjectConverter.ConvertTo(Object value, Type targetType, ObjectConverterOptions converterOptions)
         at Elsa.Expressions.Helpers.ObjectConverter.ConvertTo(Object value, Type targetType, ObjectConverterOptions converterOptions)
         at Elsa.Expressions.Helpers.ObjectConverter.ConvertTo[T](Object value, ObjectConverterOptions converterOptions)
         at Elsa.Extensions.DictionaryExtensions.ConvertValue[T](Object value)
         at Elsa.Extensions.DictionaryExtensions.TryGetValue[TKey,T](IDictionary`2 dictionary, TKey key, T& value)
         at Elsa.Extensions.DictionaryExtensions.TryGetValue[T](IDictionary`2 dictionary, String key, T& value)
         at Elsa.Workflows.ActivityExecutionContext.GetProperty[T](String key)
         at Elsa.Workflows.ActivityExecutionContext.UpdateProperty[T](String key, Func`2 updater)
         at Elsa.Workflows.Activities.Fork.CompleteChildAsync(ActivityCompletedContext context)
         at Elsa.Workflows.Behaviors.ScheduledChildCallbackBehavior.OnActivityCompletedAsync(ActivityCompleted signal, SignalContext context)
         at Elsa.Workflows.Behavior.Elsa.Workflows.Contracts.ISignalHandler.ReceiveSignalAsync(Object signal, SignalContext context)
         at Elsa.Workflows.Activity.Elsa.Workflows.Contracts.ISignalHandler.ReceiveSignalAsync(Object signal, SignalContext context)
         at Elsa.Extensions.ActivityExecutionContextExtensions.SendSignalAsync(ActivityExecutionContext context, Object signal)
         at Elsa.Workflows.ActivityExecutionContext.CompleteActivityAsync(Object result)
         at Elsa.Workflows.Activities.Sequence.HandleItemAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Activities.Sequence.OnChildCompleted(ActivityCompletedContext context)
         at Elsa.Workflows.Behaviors.ScheduledChildCallbackBehavior.OnActivityCompletedAsync(ActivityCompleted signal, SignalContext context)
         at Elsa.Workflows.Behavior.Elsa.Workflows.Contracts.ISignalHandler.ReceiveSignalAsync(Object signal, SignalContext context)
         at Elsa.Workflows.Activity.Elsa.Workflows.Contracts.ISignalHandler.ReceiveSignalAsync(Object signal, SignalContext context)
         at Elsa.Extensions.ActivityExecutionContextExtensions.SendSignalAsync(ActivityExecutionContext context, Object signal)
         at Elsa.Workflows.ActivityExecutionContext.CompleteActivityAsync(Object result)
         at Elsa.Workflows.Activity.CompleteAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Activities.Fork.CompleteChildAsync(ActivityCompletedContext context)
         at Elsa.Workflows.Behaviors.ScheduledChildCallbackBehavior.OnActivityCompletedAsync(ActivityCompleted signal, SignalContext context)
         at Elsa.Workflows.Behavior.Elsa.Workflows.Contracts.ISignalHandler.ReceiveSignalAsync(Object signal, SignalContext context)
         at Elsa.Workflows.Activity.Elsa.Workflows.Contracts.ISignalHandler.ReceiveSignalAsync(Object signal, SignalContext context)
         at Elsa.Extensions.ActivityExecutionContextExtensions.SendSignalAsync(ActivityExecutionContext context, Object signal)
         at Elsa.Workflows.ActivityExecutionContext.CompleteActivityAsync(Object result)
         at Elsa.Workflows.Activities.Sequence.HandleItemAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Activities.Sequence.OnChildCompleted(ActivityCompletedContext context)
         at Elsa.Workflows.Behaviors.ScheduledChildCallbackBehavior.OnActivityCompletedAsync(ActivityCompleted signal, SignalContext context)
         at Elsa.Workflows.Behavior.Elsa.Workflows.Contracts.ISignalHandler.ReceiveSignalAsync(Object signal, SignalContext context)
         at Elsa.Workflows.Activity.Elsa.Workflows.Contracts.ISignalHandler.ReceiveSignalAsync(Object signal, SignalContext context)
         at Elsa.Extensions.ActivityExecutionContextExtensions.SendSignalAsync(ActivityExecutionContext context, Object signal)
         at Elsa.Workflows.ActivityExecutionContext.CompleteActivityAsync(Object result)
         at Elsa.Http.WriteHttpResponse.WriteResponseAsync(ActivityExecutionContext context, HttpResponse response)
         at Elsa.Http.WriteHttpResponse.ExecuteAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Activity.Elsa.Workflows.Contracts.IActivity.ExecuteAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Runtime.Middleware.Activities.BackgroundActivityInvokerMiddleware.ExecuteActivityAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Middleware.Activities.DefaultActivityInvokerMiddleware.InvokeAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Middleware.Activities.NotificationPublishingMiddleware.InvokeAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Middleware.Activities.ExecutionLogMiddleware.InvokeAsync(ActivityExecutionContext context)
         at Elsa.Workflows.Middleware.Activities.ExceptionHandlingMiddleware.InvokeAsync(ActivityExecutionContext context)

**Comment by sfmskywalker** [comment] 2024-07-26 18:03
This looks like the same error as reported via #5844. Can you provide detailed steps to reproduce this and or a sample project? Which version of Elsa are you seeing this?

**Comment by sfmskywalker** [comment] 2024-09-06 18:08
I will close this issue for now, but please feel free to reopen in case you have more information regarding steps to reproduce. Thanks for your contributions!

**Closed by sfmskywalker** 2024-09-06 18:08 UTC
Labels: bug
