### ISSUE TITLE
[CHORE] How to pass parameters to a Switch (flow) activity and call it?

### ISSUE THREAD

**Issue by shxylgithub** [elsa-workflows/elsa-core#5695] opened 2024-07-03 19:01 UTC
How to pass parameters to a Switch (flow) activity and call it?

**Comment by sfmskywalker** [comment] 2024-07-05 17:23
Duplicate of https://github.com/elsa-workflows/elsa-core/issues/5697

I've noticed that you've been opening multiple issues on the same or very similar topics. We greatly appreciate your enthusiasm and your contributions, but we kindly ask that you consolidate related questions and issues into a single thread.

This will help us manage our time more effectively and ensure that we can address your concerns thoroughly. If you need to add more details or clarify something, please use the comment section of the original issue or update its description as needed.

Thank you for your understanding and cooperation!

**Closed by sfmskywalker** 2024-07-05 17:23 UTC
Labels: maintenance
