### ISSUE TITLE
Parallel ForEach does not parallelize activities.

### ISSUE THREAD

**Issue by appmanstudio** [elsa-workflows/elsa-core#1309] opened 2021-07-26 14:59 UTC
My use case I have to make an HTTP request, the response returned will have a list that can be used as input to create another batch of HTTP requests so that I can collect all the results. The aim is to not to do it one by one because each call will have some delay. I thought that is the purpose of having Parallel foreach as opposed to forEach.

The issue is that the result seems to show that the foreach control flow is sequential. I have attached a basic workflow to show the behavior. Every time I run this workflow, multiple calls are made to an endpoint (which is just waiting for a random amount of time before returning) and I write to console at the start of each iteration
![Screen Shot 2021-07-26 at 9 59 04 PM](https://user-images.githubusercontent.com/36249580/127011194-5d19d000-9e05-4a72-8072-ade76cf414c1.png)
. However, each call always starts at the end of previous call. No parallelism is observed.

[test-parallel-definition.zip](https://github.com/elsa-workflows/elsa-core/files/6879174/test-parallel-definition.zip)

**Comment by sfmskywalker** [comment] 2021-07-26 17:55
Hi @appmanstudio,

Your correct, the **Parallel For Each** activity is not truly parallel. It is parallel compared to **For Each** in the sense that while **ForEach** schedules its **Iteration** branch only one after another, the **Parallel For Each** activity schedules the **iteration** branch for all items at the same time. 

This means that multiple activities will be scheduled with the workflow runner, but the workflow runner will still only execute each scheduled activity in sequence, i.e. one at a time.

For Elsa to truly execute activities in parallel, we have to wait for Elsa 3 which gives greater freedom in terms of how an activity schedules work, which could even be executed in parallel.

But you don't have to wait this long. What you can do is write a custom activity that accepts a list (like **For Each** and **Parallel For Each**) and have it process this list in its `OnExecuteAsync` method, from where you invoke your HTTP endpoints in paralel using e.g. `Task.WhenAll`.

It's of course not as flexible as being able to schedule any work in parallel using the workflow, but it will at least work for you.

**Comment by sfmskywalker** [comment] 2021-07-26 17:57
I'll close the issue since the raised concern is by design, but feel free to follow up as you want.

**Closed by sfmskywalker** 2021-07-26 17:57 UTC
Labels: wontfix
