### ISSUE TITLE
Unhandled exception when AddElsaDashboard  

### ISSUE THREAD

**Issue by salarvand** [elsa-workflows/elsa-core#166] opened 2019-11-16 13:43 UTC
There is unhandled exception when run Sample19

**Comment by sfmskywalker** [comment] 2019-11-16 14:27
What’s the exception?

**Comment by salarvand** [comment] 2019-11-16 15:54
it is general exception : 

> InvalidOperationException: Application is running inside IIS process but is not configured to use IIS server.

i think **AddElsaDashboard()** is cause of exception

**Comment by sfmskywalker** [comment] 2019-11-16 16:10
Are you using IIS Express? If so, can you try adding `webBuilder.UseIISIntegration()` in `Program`? See also this [SO answer](https://stackoverflow.com/questions/58080353/application-is-running-inside-iis-process-but-is-not-configured-to-use-iis-serve).

When I run the project using IIS Express, it works either way: with or without IIS Integration, so I'm not sure why you are getting that specific exception.

Another thing to be aware of: you will need to make sure your DB connection string points to an existing database with EF migrations run. By default, appsettings.json is configured with the connection string `"Data Source=c:\data\elsa.sample19.db;Cache=Shared"`, so make sure that DB path exists if you didn't make changes to appsettings.json.

To run migrations, run the following commands from the terminal from the following path: `"C:\Projects\Elsa\elsa-core\src\persistence\Elsa.Persistence.EntityFrameworkCore"` (your exact path might vary, depending on where you cloned the repo to)

```bash
cd C:\Projects\Elsa\elsa-core\src\persistence\Elsa.Persistence.EntityFrameworkCore
SET EF_CONNECTIONSTRING=Data Source=c:\data\elsa.sample19.db;Cache=Shared
dotnet ef database update
```

Once that worked, try launching the application again.

**Comment by salarvand** [comment] 2019-11-16 16:23
I created migration succefully and tested sample19.db (created tables) also try [https://stackoverflow.com/questions/58080353/application-is-running-inside-iis-process-but-is-not-configured-to-use-iis-serve](url) this before but did not solved problem

**Comment by sfmskywalker** [comment] 2019-11-16 22:04
Are you able to run Sample16? Just to try and figure out the exact problem. Sample16 also use Elsa Dashboard, but MongoDB.

**Comment by sfmskywalker** [comment] 2019-11-17 12:37
PS. When you do run Sample16, make sure you have a local MongoDB service running, or update appsettings.json to point to a running instance. If you have Docker installed, you can simply run the docker-compose file that's part of the project.

**Comment by salarvand** [comment] 2019-11-17 15:52
I traced and find there is bug in **TaskExecutingServer** class implementation  in **Elsa.Runtime** module .  When execute task in activity and reach to Task.Delay throw exception **Task canceled**

**Comment by sfmskywalker** [comment] 2019-11-17 16:24
Interesting. Can you try and see what happens if you comment out the code where the TaskExecutingServer is registered? It’s currently only used for the YesSqlProvider anyway. I would do it but I can’t seem to reproduce this issue.

**Comment by salarvand** [comment] 2019-11-27 08:59
I commented out  **AddTaskExecutingServer()**  on **DashboardServiceCollectionExtensions** class 
and then my exception problem solved, but dashboard path ( **/elsa/home**) dont work properly and can not redirect to dashboard!
I executed **Elsa.Dashboard.Web** project in Dashboard solution and redirect to **/elsa/home**  properly but now it can not find any path witch start with this **~/_content/Elsa.Dashboard** in _Layout.cshtml and also there are not exist such files **elsa-workflow-designer.esm.js** and **elsa-workflow-designer.js** in the entire solution !

**Comment by sfmskywalker** [comment] 2019-12-23 20:59
@salarvand I see. It looks like you didn't build the assets. Please try these instructions: https://github.com/elsa-workflows/elsa-core#building--running-elsa-workflows-dashboard

After that, build the solution and try again. Let me know how it goes!

**Comment by sfmskywalker** [comment] 2020-01-12 19:36
@salarvand I'm closing this issue as I can't repro it. Please reopen if you are still having issues after trying my suggestions.

**Closed by sfmskywalker** 2020-01-12 19:36 UTC
