### ISSUE TITLE
NullReferenceException when viewing workflow instance

### ISSUE THREAD

**Issue by VahidShir** [elsa-workflows/elsa-core#1159] opened 2021-06-21 14:57 UTC
I'm just following through the guide [Document Approval Workflow](https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-document-approval#first-run). It works just fine except when in Workflow Instances window I click to view the instance and it encounters `NullReferenceException`.
As the screenshot below shows the input value is null:
![image](https://user-images.githubusercontent.com/8729558/122783316-b2cbf280-d2c6-11eb-99ca-1e14fadb6fbf.png)

**Comment by sfmskywalker** [comment] 2021-06-22 18:38
This is by design - the workflow instance viewer tries to display the actual evaluated values, like e.g. `Duration.FromSeconds(5)` would result in `0:00:00:05`. But, as you can see, this won't work for expressions when they depend on contextual data that is not there, such as input that flowed in from a previous activity.

This does not cause any real issues (the exceptions are caught and logged as warnings), but I am going to redo this part by simply displaying the value that was computed when the workflow executed.

That has the benefit of improved workflow instance loading times and, less noise and less confusion.

**Comment by sfmskywalker** [comment] 2021-06-22 18:39
Related issues: #1120

**Comment by sfmskywalker** [comment] 2021-06-23 19:38
Closing this because we will track improvements in this area via #1163.

Thanks for reporting!

**Closed by sfmskywalker** 2021-06-23 19:38 UTC
