### ISSUE TITLE
Child workflow input / ouput parameters cannot be persisted within parent workflow activity due to parameter naming

### ISSUE THREAD

**Issue by JochenSteinbrenner** [elsa-workflows/elsa-core#4202] opened 2023-07-07 08:14 UTC
Setting:
Demo server & designer (SqlLite)

Repro steps (bad):
- Create workflow `ELSA_Child`
   with input `PIN1` (string) & `PIN2` (string)
   with output `POUT1` (string) & `POUT2` (string)
- Create workflow `ELSA_Parent`
   with activity `ELSA_Child`
   set parameters `PIN1`, `PIN2`...
   publish workflow `ELSA_Parent`
- bad, parameters not persisted

Repro steps (good):
- Create workflow `ELSA_Child` 
   with input `Input1` (string) & `Input2` (string)
   with output `Output1` (string) & `Output1` (string)
- Create workflow `ELSA_Parent`
   with activity `ELSA_Child`
   set parameters `Input1`, `Input2`...
   publish workflow `ELSA_Parent`
- good, parameters persisted correctly

with kind regards
Jochen Steinbrenner
AZO

**Comment by sfmskywalker** [comment] 2023-08-12 17:13
Hello,

Thank you for reporting this issue.

I've taken the time to investigate the problem you described. However, I was unable to reproduce the issue with both the Stencil implementation of the Elsa designer and the Blazor implementation of Elsa Studio.

It's possible that this issue might have been addressed in a recent update or there might be specific conditions under which it occurs that we haven't encountered.

I'll be closing this issue for now. However, if you can still reproduce the problem with the latest version of Elsa, please don't hesitate to reopen this issue with any additional details or steps that might help us reproduce it on our end.

Thank you for your contribution to Elsa Workflows. Your feedback is invaluable in helping us improve the platform.

**Closed by sfmskywalker** 2023-08-12 17:13 UTC
Labels: bug, core, elsa 3
