### ISSUE TITLE
Javascript Error when trying to update custom activity through dashboard/designer

### ISSUE THREAD

**Issue by Alhammoud** [elsa-workflows/elsa-core#845] opened 2021-04-07 19:01 UTC
**When I am trying to edit a custom activity on a published workflow and click on the button "save" I get an error on console and my changes didn't save on the activity. To set my changes I need to remove the activity and then add it like new activity and then set my changes.**

![image](https://user-images.githubusercontent.com/45689826/113919588-0f4d6480-97e4-11eb-8b72-6c908412406d.png)
****

**Comment by sfmskywalker** [comment] 2021-04-13 08:24
Do you have steps to reproduce this behavior? I didn't get any errors when I clicked "save".

**Comment by Alhammoud** [comment] 2021-04-23 10:19
When I open my custom activity , change some fields and then click "save" I get this error. 
We integrated Elsa.Dashboard in our asp.net core 5 project and we use Elsa NuGet package also.

**Comment by sfmskywalker** [comment] 2021-05-25 12:40
Since Elsa 2 is around the corner (to be released this week) and there's a workaround (however annoying), I'm closing this issue. Thanks for reporting!

**Closed by sfmskywalker** 2021-05-25 12:40 UTC
Labels: dashboard, help wanted, question
