### ISSUE TITLE
Cron doesn't trigger at the right time v3

### ISSUE THREAD

**Issue by truthz03** [elsa-workflows/elsa-core#3924] opened 2023-04-18 12:01 UTC
Hi,

I'm currently try to get v3 working but I have some problems and I don't know if it is a bug or not finished yet.
I have checked out your source code to get all fixes and updates.
The described problem was tested with the commit: be7cee71662a97597995f8c09db888a4a804028b

The first "problem" is that the Cron activity doesn't trigger by default.
It only triggers with "Can start workflow" checked but I don't know what the purpose of this options is.
What should this option do with normal activities if they are not able to trigger something?

The second problem is that the Cron activity with "Can start workflow" checked triggers the workflow but doesn't go to the next activity.
I have configured the Cron activity with "0 0/1 * * * ?" so it should start every minute.
I seems that the Cron activity starts the workflow with the given expression but than blocks until the expression triggers again.

Here you can see the strange behaviour:
![image](https://user-images.githubusercontent.com/14071920/232770341-8f2588b7-5731-4c23-947c-0f8d100d9824.png)

**Comment by truthz03** [comment] 2023-04-18 12:40
Ok, I found the problem.

The problem is the DefaultTriggerScheduler.
The behaviour above will be active if I ony call:
`elsa.UseScheduling()`

With this the Cron activity triggers correctly:
`elsa.UseQuartz();
elsa.UseScheduling(scheduling => scheduling.UseQuartzScheduler());`

**Comment by sfmskywalker** [comment] 2023-04-18 12:41
Thanks for reporting! I’m reopening this for further investigation in the default scheduled behavior.

**Comment by truthz03** [comment] 2023-04-18 13:14
I found more problems and maybe it comes from the same code parts.

The problem is that everytime I publish a new version, the newer version will be triggered more than once at the same time.
So after the first publish the Cron activity triggers one every minute.
After the second publish it triggers twice every minute.
After the third publish it triggers three times every minute.
![image](https://user-images.githubusercontent.com/14071920/232784882-0d68b49f-53d1-4061-9a3f-3df75ac3ef5f.png)

This happens with the "DefaultTriggerScheduler" and the "QuartzWorkflowScheduler".
The only way to ge this fixed is to restart the backend but this results in the next problem.

If I restart the backend nothing will be triggered even if the workflow is published.
To get it starting again I have to click "Publish" on all workflows again.
**This will call "ScheduleWorkflows.HandleAsync" which was not called on a restart!!!**

**Comment by sfmskywalker** [comment] 2023-04-21 10:12
Fixed via #3938

**Closed by sfmskywalker** 2023-04-21 10:12 UTC
Labels: bug

**Comment by sfmskywalker** [comment] 2023-04-21 10:24
@truthz03 Thanks again for reporting your findings.

I merged a PR that fixes two issues:

- CRON activity no longer spawns new workflow executions when application restarts.
- CRON starts new workflow execution, but then gets "stuck"

As for the workflow executing multiple times, depending on the number of times you publish the workflow, I could not reproduce this behavior. At the same time, I didn't try it before I made the changes, so it's possible it got fixed implicitly. If you still do see this behavior after updating to the latest source code, then please let me know.

Regarding yuor question about the "Can start workflow" setting - when this is set, the system extracts triggers from the activity. These triggers will then automatically invoke the associated workflow.

When this setting is not set, the workflow will not start automatically. The behavior then will be like this:
- Invoke the workflow manually will cause the CRON activity to create a bookmark.
- The bookmark will be used to create a CRON schedule using the current scheduler provider (default, Quartz or Hangfire).
- When the schedule runs the associated job, the workflow gets resumed.

When using this setting for activities that don't represent triggers, e.g. WriteLine, the setting doensn't have any effect currently, but I might change this to help the Flowchart activity understand which activity to schedule first, in case there are multiple root nodes. I might also remove this setting altogether (at least for non-trigger activities) to make it a little bit less confusing.

Ideally, we don't need this setting at all. The reason it exists is because the workflow engine supports different kinds of activities: Flowchart and Sequence, to name two examples,

With a Flowchart graph, it is easy to just extract triggers from the root nodes.
But we also have to consider Sequence activities and custom composite activities, where the desired trigger may not be the first activity in the graph. For this reason, I opted to require the user to mark the activities to use as a trigger until a smarter solution comes to attention.

**Comment by truthz03** [comment] 2023-04-24 11:30
@sfmskywalker Thanks für your fix.
I have tested it now and it seems to work correctly now (tested with QuartzWorkflowScheduler only).

1. The workflow starts at the right time
2. It starts after a backend restart
3. It only starts once at the same time after publishing a new version

**Comment by sfmskywalker** [comment] 2023-04-24 11:52
Great, thank you for confirming!
