### ISSUE TITLE
Expired messages in Workflow Inbox should be ignored

### ISSUE THREAD

**Issue by martinmanfar** [elsa-workflows/elsa-core#5549] opened 2024-06-07 07:10 UTC
## Description
When a bookmark is created the library tries to find existing messages in the Workflow Inbox but it should exclude expired ones.

## Steps to Reproduce
1. Publish an event in the Workflow Inbox.
2. Wait until that event is expired (by default 1 min).
3. Start a workflow with the Event activity that waits for the same event.
4. The activity bookmark matches with the previous expired event.

## Expected Behavior
The activity was suspended waiting for a new event because the existing one is expired.

## Actual Behavior
The activity was resumed because it used the expired event.

## Environment
ELSA 3.2

**Comment by sfmskywalker** [comment] 2024-06-07 16:55
Thank you for reporting this issue. Your findings are correct, the issue is similar to what has been reported via #5203 and #5409

The WorkflowInbox API is being deprecated as of the future 3.3 release and its implementation will have been updated to use the new Stimulus API, which does not suffer from the reported issues.

**Comment by sfmskywalker** [comment] 2024-06-10 19:33
Closed via https://github.com/elsa-workflows/elsa-core/pull/5444

**Closed by sfmskywalker** 2024-06-10 19:33 UTC
Labels: bug, elsa 3
