### ISSUE TITLE
JSON bug

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#2426] opened 2021-10-29 08:09 UTC
Problem:
- Converting input to a JS object in JS activity and returning it
- Using the output of the JS activity in a HTTP activity to send it as JSON
- Sent request does not contain the right JSON.

![image](https://user-images.githubusercontent.com/1503577/139397750-94455ac5-59e3-4eed-a442-c12d3345a700.png)

JS activity called `process`
```
const raw = activities.webhook.Output().RawBody;
const body = JSON.parse(raw);
const items = body.Event.Control.Items;
let output = [];

for (const item of items) {
    for (const value of item.Values) {
        output.push({
            Item: item.Id,
            Values: {
                ListItem: value.Title,
                Value: value.Value
            }
        });
    }
}

return output;
```

Transfered data between the steps:
```
[
 {
  "Item": "e991f17a-246b-4d7d-a4b6-abbf54bd6911",
  "Values": {
   "ListItem": "Name",
   "Value": "Test"
  }
 },
 {
  "Item": "e991f17a-246b-4d7d-a4b6-abbf54bd6911",
  "Values": {
   "ListItem": "E-mail",
   "Value": "test@test.com"
  }
 }
}
```

POST content (generation) of the HTTP activity
```
return JSON.stringify(activities.process.Output());
```

Received data at my endpoint
```
[
  {
    "Item": "e991f17a-246b-4d7d-a4b6-abbf54bd6911",
    "Values": {
      "Count": 2,
      "IsReadOnly": true
    }
  },
  {
    "Item": "e991f17a-246b-4d7d-a4b6-abbf54bd6911",
    "Values": {
      "Count": 2,
      "IsReadOnly": true
    }
  }
]
```

**Note:** Stringifying the JS object in the JS activity and then just using it in the HTTP activity (`return activities.process.Output();`) returns the correct JSON.

**Comment by sfmskywalker** [comment] 2021-11-01 21:21
I can reproduce with the following (simplified) workflow:

![image](https://user-images.githubusercontent.com/938393/139743649-fb34d108-ee35-4bf4-9280-004315ebccf9.png)

JSON version of the workflow for testing:
[js-serialization-workflow.zip](https://github.com/elsa-workflows/elsa-core/files/7456190/js-serialization-workflow.zip)

The issue lies with the serialization of the JavaScript object returned from the RunJavaScript activity.
Looking into that next.

**Comment by sfmskywalker** [comment] 2021-11-01 21:25
The problem is not the output of the first activity (which is an array of ExpandoObjects), but with `json.Stringify` being unable to properly stringify the list of expandos to JSON.

**Comment by sfmskywalker** [comment] 2021-11-01 21:31
Interestingly enough, Newtonsoft Json can properly serialize the expandos to JSON. Sample result:

```json
[
{
   "Item": "e991f17a-246b-4d7d-a4b6-abbf54bd6911",
   "Values": {
      "ListItem": "Name",
      "Value": "Test"
    }
  },
  {
    "Item": "e991f17a-246b-4d7d-a4b6-abbf54bd6911",
    "Values": {
      "ListItem": "E-mail",
      "Value": "test@test.com"
    }
  }
]
```

What I suggest we do is add a custom serialization JS function that we use instead of `JSON.stringify` *which is provided by Jint, so maybe not a good idea to try and replace it).

**Comment by sfmskywalker** [comment] 2021-11-01 21:38
The following JS expression can now be used:

```javascript
return jsonEncode(activities.process.Output());
```

The result will look like this:

```json
[{"Item":"e991f17a-246b-4d7d-a4b6-abbf54bd6911","Values":{"ListItem":"Name","Value":"Test"}},{"Item":"e991f17a-246b-4d7d-a4b6-abbf54bd6911","Values":{"ListItem":"E-mail","Value":"test@test.com"}}]
```

**Comment by jwillmer** [comment] 2021-11-02 08:57
It works but with this solution you might want to interfere with `JSON.stringify` and automatically use your function (in the backend) when a user write this. Since it is not obvious that `JSON` is supported but `stringify` is broken.

**Comment by sfmskywalker** [comment] 2021-11-02 09:18
Yea maybe. But, barring whether it's even possible or not, I don't know that JSON stringify is actually broken. For all I know it's expected behavior when serializing `ExpandoObject`.

Would be good if someone could do a little investigation and look at Jint's JSON stringify implementation.

**Comment by jwillmer** [comment] 2021-11-02 14:08
Tracking upstream: https://github.com/elsa-workflows/elsa-core/issues/2426

**Comment by sfmskywalker** [comment] 2021-11-03 18:38
The ExpandoObject serialization issue was fixed in https://github.com/sebastienros/jint/pull/996.

**Closed** 2021-11-03 18:41 UTC
Labels: bug, activity
