### ISSUE TITLE
Bug: Elsa 2.0 MongoDb Deserializing

### ISSUE THREAD

**Issue by Rafael94** [elsa-workflows/elsa-core#552] opened 2021-01-04 15:01 UTC
When loading workflow instances I get the following error. 

`An error occurred while deserializing the Activities property of class Elsa.Models.WorkflowInstance: An error occurred while deserializing the Output property of class Elsa.Models.ActivityInstance: Unknown discriminator value 'FinishOutput'.`

I already know the cause of this: https://stackoverflow.com/a/43312423

`BsonClassMap.RegisterClassMap<FinishOutput>();` will fix the problem.

But it will probably happen more often. It would be best to register the classes centrally, so that in Elsa.Persistence.MongoDb only the central place has to be read and thus no dependencies to other projects exist.

I just don't know yet where it is nicest and how to name it best.

**Comment by sfmskywalker** [comment] 2021-01-04 15:05
That's a problem. I think I should be storing Output values as JTokens instead. The consuming code needs to know the targt type anyway, so they may just as well deserialize JTokens themselves (using convenience helpers).

**Comment by Rafael94** [comment] 2021-01-04 17:05
That is also a good idea.  Could you see if you can do it with `System.Text.Json` (https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/ `JsonElement`) instead of Newtonsoft? `System.Text.Json` comes directly from Microsoft and might be faster.

**Comment by craigfowler** [comment] 2021-02-22 18:16
@sfmskywalker - would you be opposed to splitting this into two or even three separate issues, so they can be prioritised independently?  We've got:

* This bug - reading from MongoDb crashes
* Revisiting what is stored in the db: A model class or a JSON token object
* Evaluating a switch to `System.Text.Json` from Json.NET

I think that these could be three separate pieces of work and might not _all_ need to go in 2.0.0.  The only concerns about _not doing one or more of these in 2.0.0_ is that I suspect changing what's stored in the DB would force a breaking change (pushing it to 3.0.0).

I'm not against any of these suggestions though; indeed, I think @Rafael94 's idea is a good one.  It does look suspiciously like it would become a solution-wide job though.  I see 89 matches for `using Newtonsoft.Json` at the moment, so it probably wouldn't be a quick swap.

**Comment by sfmskywalker** [comment] 2021-02-22 19:26
@craigfowler Not at all, I think you're spot-on with those suggestions.

* As Craig stated, he only thing that needs to make it for the 2.0 release is the bug described in this issue. The fix might be as simple as making sure the document gets serialized the same way the EF Core provider serializes data into a shadow Data property (making sure that the Output property is serialized with type information which is a setting on Newtonsoft Json, and is used also in the `DefaultContentSerializer`.
* Switching to `System.Text.Json` would be absolutely fantastic, but is an undertaking not te be taken lightly - there are some key features that we use from `Newtonsoft.Json` that are not (yet) available in the framework version. Although I don't believe there would be anything blocking, but I do think it might involve a potentially significant amount of custom code in the form of converters for example.

**Comment by craigfowler** [comment] 2021-02-22 19:56
Two new issues created for those aside-tasks: #650 and #651.

**Comment by craigfowler** [comment] 2021-03-08 12:49
Progress on this is blocked by #728

**Comment by craigfowler** [comment] 2021-03-11 20:51
## No longer reproducible as-described
Hi @Rafael94 - I've been looking into this to try and address it in Elsa 2.0.  After some exploration, I'm not sure that this requires any code change for Elsa 2.0 and has been "fixed by accident" during other work on the various models used to persist information in the database.

I've got [a test-case in Elsa 2.0] which proves that a workflow instance may be persisted and then read-back from MongoDb.  That's a fairly minimal example, but you can see that a workflow may be started, suspended, persisted and then retrieved OK.  The property of a `WorkflowInstance` which is noted in your original issue report: `Activities` no longer exists, and its replacements/conceptual equivalents store only objects that have primitive properties and which are not polymorphic.

I have also had a look around at some of the other models which are persisted into the data store and they have been refactored in similar ways.  If you can create a reproduction case for this in Elsa 2.0 then please share it, but overall I think this one has actually been "fixed for free".

I'll leave this issue open for a while, in case anybody finds a reproduction case, but it's my belief that we don't need to make any code changes here.  If this is still open when Elsa 2.0 is due for release, my recommendation would be to close it.

[a test-case in Elsa 2.0]: https://github.com/elsa-workflows/elsa-core/blob/feature/elsa-2.0/test/integration/Elsa.Core.IntegrationTests/Persistence/MongoDb/MongoDbIntegrationTests.cs

**Comment by Rafael94** [comment] 2021-03-12 06:48
Hi @craigfowler,

thanks for the info. I must confess that I haven't bothered with Elsa since then. I am currently working on other projects at work.

**Closed** 2021-04-02 11:11 UTC
Labels: bug, prio high, question

**Comment by ICodeForJoy** [comment] 2021-05-27 04:09
I am also getting similar error when loading workflow instances using the latest 2.0 stable version. 

`BsonSerializationException: Unknown discriminator value 'HttpRequestModel'.
MongoDB.Bson.Serialization.BsonSerializer.LookupActualType(Type nominalType, BsonValue discriminator)`

`FormatException: An error occurred while deserializing the Output property of class Elsa.Models.WorkflowInstance: Unknown discriminator value 'HttpRequestModel'.
MongoDB.Bson.Serialization.BsonClassMapSerializer<TClass>.DeserializeMemberValue(BsonDeserializationContext context, BsonMemberMap memberMap)`

**Comment by sfmskywalker** [comment] 2021-05-27 08:41
@ICodeForJoy I just tried to reproduce this issue, but I did not get the error. Here's what I tried:

1. Spin up a new MongoDB docker container.
2. Start Elsa Server.
3. Create a simple HTTP Endpoint -> HTTP Response workflow.
4. Invoke the HTTP Endpoint.
5. Inspect the workflow instance.

I did not receive any error.

Question: were you trying with an existing MongoDB database?

**Comment by ICodeForJoy** [comment] 2021-05-27 13:46
@sfmskywalker No, I am not using existing MongoDB database, created a new one.

Also I have tried all the same steps, it does works at first.
But when I stop the application and run again later on then it starts giving me same exception.

**Comment by sfmskywalker** [comment] 2021-05-27 14:07
You're right, I can reproduce now. Will fix.

**Comment by sfmskywalker** [comment] 2021-05-27 14:59
Tricky problem, here's why:

* When using MongoDB, we need to register any and all types that are potentially stored in a workflow instance using `BsonClassMap.RegisterClassMap<T>`. 
* We have many modules with activities that potentially store something within a workflow instance.
* None of these modules should have a dependency on MongoDB.
* The MongoDb provider itself should also not have a dependency on any of the activity modules (such as Elsa.Activities.Http).

One not-so-great solution I can think of is to require the host application to register these types, like so:

```csharp
public class Startup
{
    public Startup()
    {
        BsonClassMap.RegisterClassMap<HttpRequestModel>(cm => cm.AutoMap());
    }
}
```

Which is far from ideal of course, because now the user needs to understand what types to register, depending on what activity packages they use.

So what we might do instead is let Newtonsoft.Json take care of object serialization, which does not require "known types" to be registered.

I tried it and it works wonders, but it also means that it will break existing MongoDB databases where they basically need to wipe their DB.

**Comment by sfmskywalker** [comment] 2021-05-27 15:03
PR #1052 fixes this issue.

**Comment by Juandavi1** [comment] 2021-06-25 21:03
Hi guys,

i have the same issue

`[15:57:10 ERR] flow-engine 06/25/2021 20:57:10 500 Internal Server Error System.FormatException: An error occurred while deserializing the Output property of class Elsa.Models.WorkflowInstance: Unknown discriminator value 'FinishOutput'. ---> MongoDB.Bson.BsonSerializationException: Unknown discriminator value 'FinishOutput'.`
dependency
`<PackageReference Include="Elsa.Persistence.MongoDb" Version="2.0.0.159"/>`

should i update some other dependency?

Thanks, awesome project !!

**Comment by sfmskywalker** [comment] 2021-07-03 19:14
@Juandavi1 This should be fixed with the latest preview packages available on MyGet and of course in `master`. Please feel free to reopen if you can still reproduce this issue with the latest version and repro steps. Thanks!

**Comment by dwevedivaibhav** [comment] 2022-07-26 06:00
Hi @sfmskywalker ,

I am unable to load workflow instances menu (Elsa UI) in elsa 2.8.2 when activity failed while executing workflow. I am using mongo db
please find the below error which i got in code 

An unhandled exception was thrown by the application.", "exception": "System.FormatException: An error occurred while deserializing the Fault property of class Elsa.Models.WorkflowInstance: An error occurred while deserializing the Exception property of class Elsa.Models.WorkflowFault: An error occurred while deserializing the Type property of class Elsa.Models.SimpleException: Specified method is not supported.\r\n ---> System.FormatException: An error occurred while deserializing the Exception property of class Elsa.Models.WorkflowFault: An error occurred while deserializing the Type property of class Elsa.Models.SimpleException: Specified method is not supported.

Please advice how we can fix this issue.

Thanks
