### ISSUE TITLE
CustomActivity and CreateVariable

### ISSUE THREAD

**Issue by berthendrickx** [elsa-workflows/elsa-core#4531] opened 2023-10-13 09:49 UTC
Hi, I'm trying to create and store a workflow variable from within one custom activity, and access this same variable from a custom activity later on in the same flow. I'm using the latest preview version 3.0.0-preview.727

To create the variable, i'm using the following code within the ExecuteAsync method of the "first" activity:
context.CreateVariable("Name", "Value");

When trying to retrieve the value from withing the second activity using:
context.GetVariable<string>("Name");

It returns null. Furthermore, when I inspect the context object, the Variables property is an empty enumeration.
It's even an empty enumeration right after calling CreateVariable() in the first activity.

I have also tried following variations, without success:
SetVariable("Name", "Value");

var test = new Variable<string>() { Name = "Name", Value = "Value" };
context.DynamicVariables.Add(test);

I would like to state I'm otherwise impressed with Elsa as a whole and keep up the good work!

**Comment by sfmskywalker** [comment] 2023-10-18 13:06
Hi @berthendrickx,

Thank you for the detailed description of your issue and for providing the code snippets. It sounds like the variable context might be getting lost or reset between the two activities.

We'll definitely dive deeper into this scenario to see if there's an underlying issue. I'll keep you posted on our findings, and if needed, we'll push an update to address it. We'll also aim to provide a working example to guide you.

We really appreciate your positive feedback on Elsa. We're always working to enhance its capabilities and your feedback plays a crucial role in that.

**Comment by sfmskywalker** [comment] 2023-10-20 11:44
I tried to reproduce the problem, but it seems to work fine for me. I also added [an integration test](https://github.com/elsa-workflows/elsa-core/tree/v3/test/integration/Elsa.IntegrationTests/Scenarios/SetGetVariablesFromActivities) to capture this scenario, perhaps you can take a look and see if you spot anything different from what you are doing?

**Comment by sfmskywalker** [comment] 2023-10-20 11:48
I'll paste in the code that I tested with here as well:

```csharp
public class CreateVariableActivity : CodeActivity
{
    protected override void Execute(ActivityExecutionContext context)
    {
        context.SetVariable("Foo", "Bar");
    }
}

public class ReadVariableActivity : CodeActivity<string>
{
    protected override void Execute(ActivityExecutionContext context)
    {
        var foo = context.GetVariable<string>("Foo");
        Result.Set(context, foo);
    }
}

class SampleWorkflow : WorkflowBase
{
    protected override void Build(IWorkflowBuilder workflow)
    {
        var variable1 = new Variable<string>();

        workflow.Root = new Sequence
        {
            Variables =
            {
                variable1
            },

            Activities =
            {
                new CreateVariableActivity(),
                new ReadVariableActivity
                {
                    Result = new(variable1)
                },
                new WriteLine(variable1)
            }
        };
    }
}
```

- The `CreateVariableActivity` activity sets a variable called "Foo" to a value of "Bar".
- The `ReadVariableActivity` activity reads a variable called "Foo" and provides the value as its Result outcome.
- The workflow captures the output of the `ReadVariableActivity` activity and stores it in a workflow variable called `variable1`. This is not mandatory, but I am doing it here so that the `WriteLine` activity can display the value.

When running the workflow, the console will print "Bar" - which is the value that the first activity assigned to the "Foo" variable, which was then read by the second activity.

**Comment by sfmskywalker** [comment] 2023-10-20 11:50
I'll close this issue as "cannot reproduce", but please do feel free to continue the conversation. If you want, you can share a sample application with me that reproduces the issue you're seeing. It's possible that there's some nuance that I am missing here.

**Closed by sfmskywalker** 2023-10-20 11:50 UTC
Labels: bug, elsa 3

**Comment by berthendrickx** [comment] 2023-10-20 12:32
Hi @sfmskywalker ,

I managed to fix the issue. My activities inherit from a base activity class, and I forgot to call base.ExecuteAsync at the start of the ExecuteAsync method.. Adding that line fixed it. Stupid oversight on my behalf, sorry to waste your time.

**Comment by sfmskywalker** [comment] 2023-10-20 12:49
No worries, I'm always here to assist, and it's great to know you've resolved the issue. Your feedback is invaluable, as it not only helps us improve but also aids others who might encounter similar challenges in the future. Keep the questions and insights coming! 😄
