### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by Juandavi1** [elsa-workflows/elsa-core#1551] opened 2021-09-18 20:22 UTC
Hi guys, 

im trying to resume a workflow from a request using the IWorkflowInstanceExecutor but I can't do it

![image](https://user-images.githubusercontent.com/18731612/133907517-3ff27277-4a4a-4377-ac03-18488c1d5e56.png)

![image](https://user-images.githubusercontent.com/18731612/133907527-92c86368-0ee0-432e-94b1-f1429bc7804f.png)

I would appreciate any suggestions

thanks

**Comment by sfmskywalker** [comment] 2021-09-19 10:42
It looks like you might be resolving certain services from an incorrect scope. Is there any way you can provide full context? Ideally in the form of a project reproducing this issue.

**Comment by Juandavi1** [comment] 2021-11-17 13:20
It works. Thanks

**Closed** 2021-11-17 13:20 UTC

**Comment by VictorioBerra** [comment] 2022-05-02 16:19
I am having this issue too. @Juandavi1 how did you solve this?
