### ISSUE TITLE
Workflow visualizer is not working as intended on the latest Chrome (110.0.5481.178)

### ISSUE THREAD

**Issue by uyarbtrlp** [elsa-workflows/elsa-core#3733] opened 2023-02-23 12:55 UTC
Hi,

I've updated my chrome version to the latest and I have the same issue which was described on [3621](https://github.com/elsa-workflows/elsa-core/issues/3621). I've upgraded the latest version of Elsa.Designer.Components.Web (2.10.2.2). It does not work for me. When I click on one of the workflow definition, I can only see the connections of the workflows (like previously). When I click on the area of the designer, I am able to see the whole flow. 

Thanks in advance for the fix!

**Comment by mohdali** [comment] 2023-02-23 13:02
This issue is supposed to be fixed in the latest release.

Could you please try a hard refresh (Ctrl+F5) to confirm?

**Comment by uyarbtrlp** [comment] 2023-02-23 13:29
I am using the designer in the MVC project. There is a specific layout. I am not able to refresh the page. Here is the process:
![2023-02-23 16-24-34](https://user-images.githubusercontent.com/59877078/220920046-d26817a9-8518-48c8-8fe9-cb2820c6971b.gif)

**Comment by mohdali** [comment] 2023-02-23 13:49
> I am using the designer in the MVC project. There is a specific layout. I am not able to refresh the page. Here is the process: ![2023-02-23 16-24-34](https://user-images.githubusercontent.com/59877078/220920046-d26817a9-8518-48c8-8fe9-cb2820c6971b.gif) [ ![2023-02-23 16-24-34](https://user-images.githubusercontent.com/59877078/220920046-d26817a9-8518-48c8-8fe9-cb2820c6971b.gif) ](https://user-images.githubusercontent.com/59877078/220920046-d26817a9-8518-48c8-8fe9-cb2820c6971b.gif) [ ](https://user-images.githubusercontent.com/59877078/220920046-d26817a9-8518-48c8-8fe9-cb2820c6971b.gif)

Yes, the old library might be still cached by the MVC app, sometimes hard refresh of the page (Ctrl+F5) forces reloading of the new JavaScript library.

Please check if that resolves the issues as the root cause was already identified and hopefully resolved.

**Comment by uyarbtrlp** [comment] 2023-02-23 14:40
It was about the caching.. Clearing the cache worked. Thanks!

**Closed** 2023-02-23 14:40 UTC
